### ISSUE TITLE
[Mobile] - Block link not visible 

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#102]
**Description**
Once  screen size is that small that the header moves to the footer no more block information/ link is shown. 

**How to Reproduce**
1. Go to CowSwap 
2. Reduce Screen size
or open on mobile device

<img width="711" alt="Bildschirmfoto 2021-08-04 um 08 54 24" src="https://user-images.githubusercontent.com/34510341/128135859-78deaf44-d56c-4477-a6b0-86a86707f0c7.png">

> Original issue https://github.com/gnosis/cowswap/issues/1167 by @MareenG

**Comment by elena-zh** [comment]
no longer relevant
