### ISSUE TITLE
FAQ links broken

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#104]
**Description**
If you try to link to a specific FAQ question, it website won't navigate for you
This used to work in the past, so probably we broke it recently.

**How to Reproduce**
1. Go to https://cowswap.exchange/#/faq#does-cowswap-have-a-token
2. Observe that the automatic scrolling didn't happen.

**Expected behavior**
Scroll automatically

> Original issue https://github.com/gnosis/cowswap/issues/1170 by @anxolin

**Comment by elena-zh** [comment]
FAQ section has been removed
