### ISSUE TITLE
ETH flow: Wrap modal is changed to Swap when amount to wrap>amount in the balance

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1051]
Edge case

1. Turn ON the expert mode
2. Run a wrap transaction
3. While the TX is ruining, specify the 100% amount of ETH and press on the Wrap button again
4. Wait till the 1st TX is executed

**AR**: 'Wrap your ETH' section turns to Swap WETH section
![empty modal.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/37354add-00d5-4cbd-ae18-eaf08cbd1ab2)

**ER**: 'Wrap your ETH' section remains to be displayed

**Comment by W3stside** [comment]
weird i can't get this to reproduce, it hangs, also happens in prod

**Comment by elena-zh** [comment]
@W3stside , I recorded a [video ](https://watch.screencastify.com/v/tM7McmQ91r9InIfE4f3Q)for you with steps to reproduce the issue .

It can't be on prod now as we don't have these additional modals there when we wrap tokens.
