### ISSUE TITLE
Lots of quote requests  in Console (network tab) when Tokens page is opened

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1059]
Originally reported in #1057 (cases 5,6)

5. I see Quotes requests in the console when I select eth/weth token pair (should not appear)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/24fb977f-7644-4125-af58-8668d10591d2)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3d162cc6-7d83-4699-a0eb-d24e07ffeb35)

6. Tons of 'quotes' requests in Console (network tab) when Tokens page is opened
![image](https://user-images.githubusercontent.com/70885163/189145512-65f1b577-c665-476a-9a92-04057d9ed6b8.png)

**Comment by elena-zh** [comment]
I thought that it was related to new refactoring PRs, but it appears that these issues were reproducible in #889 PR
![image](https://user-images.githubusercontent.com/70885163/190991068-733ddd41-8931-463b-865e-456b661ab550.png)

@W3stside , could you please take a look at it?

**Comment by nenadV91** [comment]
Regarding point 5, its not actually a bug, instead its request to get USDC price for the tokens you have balance greater then 0
