### ISSUE TITLE
Price calculation hangs when trade ETH/token with insufficient liquidity for a trade

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1061]
1. OPen the app
2. Switch to Rinkeby
3. Change WETH token to ETH
4. Select USDC token in the To field
5. Fill in ETH amount

**AR**: the app hangs in calculating price state
![hang.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/46869b6a-c5ed-45c3-a624-2dcae325a0de)

**ER**: Insufficient liquidity error should be displayed

**Comment by W3stside** [comment]
I dont see this:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/21335563/190121412-3ffb19d9-0435-46e3-9be4-4bfe3b44757b.png">

**Comment by W3stside** [comment]
yes i had also tried it with usdc and subs with zero issues. but today i see it intermittently as well

**Comment by elena-zh** [comment]
@W3stside , I can reproduce the issue by following the steps in the description. See the video: https://watch.screencastify.com/v/Ha2Zkcg0CMQrwfcWP4c3
