### ISSUE TITLE
Error JSON URL

### ISSUE THREAD

**Issue by iragsraghu** [cowprotocol/cowswap#1063]
**Description**

1. [SetList](https://raw.githubusercontent.com/SetProtocol/uniswap-tokenlist/main/set.tokenlist.json)

Structure of JSON in the above URL is incorrect
Incorrect Format from Line number 614 to 629

<img width="1065" alt="Screenshot 2022-09-13 at 6 23 51 PM" src="https://user-images.githubusercontent.com/100752246/189906779-8754c1d1-84eb-40ef-a21b-99d2da39b801.png">

Corrected Format is

<img width="1050" alt="Screenshot 2022-09-13 at 6 25 26 PM" src="https://user-images.githubusercontent.com/100752246/189906998-51445ebf-e8ed-4a6d-bcab-124e5a8c2126.png">

**Comment by anxolin** [comment]
Hi @iragsraghu thanks for posting this issue.

The file is not maintained by us, it belongs to Set Protocol. I did the fix as a PR to their project, but that's all I can do. If you want, you can try to reach them so we make sure this is merged ASAP

**Comment by iragsraghu** [comment]
Issue Fixed thank you
