### ISSUE TITLE
Add an additional  'Confirm ETH/XDAI wrap' modal when wrap MAX qty 

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#107]
It would be nice to add an additional  'Confirm ETH/XDAI wrap' modal when wrap MAX qty of ETH/XDAI token using SWAP from. 
**To reproduce:**

1. Select max ETH token value in the From field
2. Select WETH token in the To field
3. Press on the Wrap button

**AR**: request to confirm the transaction is sent to the connected wallet
![add an additional warning.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/535274c8-3512-4d8d-892a-65e8438fc86f)

**ER**: add an additional warning like it is implemented for 'Wrap your ETH first or switch to WETH9!' flow
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e1b39b06-1978-4f7f-920a-c595f400bd95)

> Original issue https://github.com/gnosis/cowswap/issues/1185 by @elena-zh

**Comment by elena-zh** [comment]
Closed in favor of changes that will be implemented in #889
