### ISSUE TITLE
User is able to sign transaction when insufficient balance/token is not approved

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#109]
I'm not sure if the issue is reproducible on the current Stage/Prod environment, due to there are no performance issues currently. 
 On the https://barn.cowswap.exchange/#/swap balances are loaded too long, and while balances are loaded, I'm able to specify ant amount to sell/buy and run the transaction even if my token is not yet approved OR I do not have enough balance in my wallet. 
See the video: https://drive.google.com/file/d/1OjBhr4noljT65zzvt-biQ4Eocw9WOJam/view

Luckily, transaction submission ends with an error: 
![image](https://user-images.githubusercontent.com/70885163/128505886-afb45dd0-781d-43cd-8a6c-ed37776be754.png)

**Expected**: to not enable Swap button when balances are not yet loaded

> Original issue https://github.com/gnosis/cowswap/issues/1193 by @elena-zh

**Comment by elena-zh** [comment]
Due to improved performance, I have not faced this issue for a long time. 
Closing it for now.
