### ISSUE TITLE
[Token list] Common tokens tooltip is in light-blue color in the dark mode

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#110]
See the image
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3307e405-7cbe-443f-9e4a-7485477deaf6)

**Expected**: tooltip should be in the dark color
Example: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3173b685-c7e6-4a5c-b982-184b2dffa682)

> Original issue https://github.com/gnosis/cowswap/issues/1194 by @elena-zh

**Comment by elena-zh** [comment]
Fixed
