### ISSUE TITLE
Animate favicon

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1104]
Add laser eyes, or some fun animation when loading (having pending orders)

https://cowservices.slack.com/archives/C03HREFVBU4/p1664054622908809

**Comment by elena-zh** [comment]
Hey @anxolin , should we still keep it opened? :)

**Comment by anxolin** [comment]
Yes! We are actually doing it this quarter together with the rebranding, but is part of a bigger task, so I will close
