### ISSUE TITLE
Change COW token icon

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1114]
Discussion: https://cowservices.slack.com/archives/C0361CDG8GP/p1664356608688319

1. Open Account pages: Tokens page and Overview
2. Check the Cow token logo

**AR**: the old token logo is displayed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fac16d61-4582-454d-8fd5-ec4f0da3c672)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3a14bedb-5b0e-418c-b380-e1e41d34ed9d)
Token lists: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/55bcde3a-9903-44f3-8815-e63b2ba7d3b4)

**Should be:** 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5a7c882b-3185-4e73-86b5-e6661fc46a26)

**Comment by shoom3301** [comment]
A new logo: https://drive.google.com/drive/u/0/folders/1LvoYA0qMa58DWxZMxgtia_sS7lrp8cBU

**Comment by alongoni** [comment]
Progress bar svg graphs updated:
![cow-graph](https://user-images.githubusercontent.com/622217/193126573-e31e95e7-dea9-4ffd-8784-7be5353c6d7f.svg)
![amms-graph-gc](https://user-images.githubusercontent.com/622217/193126581-f1d8e47c-0cbb-4480-914f-b2713d48b492.svg)
![amms-graph](https://user-images.githubusercontent.com/622217/193126584-a02a31f3-ef8e-408d-9270-5f69970abdbd.svg)

cc @shoom3301

**Comment by alfetopito** [comment]
@alongoni I don't think the image with the text looks very good on this size.
What about using only the cow head instead? (Like it was with the former logo)

**Comment by alongoni** [comment]
> @alongoni I don't think the image with the text looks very good on this size. What about using only the cow head instead? (Like it was with the former logo)

Right!
After the rebranding, the only difference among the logos (swap and protocol) is the background colour, so I felt the need to add the CoW protocol text.  
However, I agree that the text looks small (also I tried to make the cow protocol logo bigger) so It's ok if we use these graphs: 
![cow-graph](https://user-images.githubusercontent.com/622217/193338016-f69b94d0-f0f2-4016-885c-d88932d7fe65.svg)
![amms-graph-gc](https://user-images.githubusercontent.com/622217/193338022-a91b7aeb-a8a2-487e-be86-03c04481b126.svg)
![amms-graph](https://user-images.githubusercontent.com/622217/193338024-c0a05952-4a87-49f8-8ef7-85b77e88ce0c.svg)
