### ISSUE TITLE
[Dark Mode]- Consistent colouring of warning modals

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#114]
**Description**
In Dark mode the warning modals are currently not equally coloured and vary between light blue to dark blue. 

In the light mode this is more consistent.

**Examples**
Confirm Expert mode:
<img width="593" alt="Bildschirmfoto 2021-08-10 um 12 48 33" src="https://user-images.githubusercontent.com/34510341/128854380-d6f9bcbb-4bc6-4d47-a111-d059a82df6cd.png">

Import tokens: 
<img width="601" alt="Bildschirmfoto 2021-08-10 um 12 48 25" src="https://user-images.githubusercontent.com/34510341/128854431-9c01d165-733d-4d5d-a4c2-f091217dcd30.png">

Unsupported Tokens: 
<img width="605" alt="Bildschirmfoto 2021-08-10 um 12 46 43" src="https://user-images.githubusercontent.com/34510341/128854502-5d209cfa-6cc6-4192-906f-9d7dd7043f48.png">

Light mode: 
Expert mode
<img width="659" alt="Bildschirmfoto 2021-08-10 um 12 49 11" src="https://user-images.githubusercontent.com/34510341/128854556-18ff4f91-dc9b-43fc-957e-3637a1616664.png">
Import Tokens:
<img width="627" alt="Bildschirmfoto 2021-08-10 um 12 49 37" src="https://user-images.githubusercontent.com/34510341/128854574-d3ae6e27-4d72-406b-947d-59dd188df950.png">
Unsupported Tokens
<img width="591" alt="Bildschirmfoto 2021-08-10 um 12 49 20" src="https://user-images.githubusercontent.com/34510341/128854578-36705ebf-b5ea-4053-995a-2cc2a1c99f67.png">

**Proposal**
Might be good to be more consistent with the shades of blue as done in the light mode. 
I personally prefer the light blue as it sticks out a bit better which highlights the warning mechanism of the modal. 
This would also match with the light mode where the modals are mainly white. 

**Additional context**
Also refers to #1177 

> Original issue https://github.com/gnosis/cowswap/issues/1214 by @MareenG

**Comment by elena-zh** [comment]
Fixed
