### ISSUE TITLE
[1.23] Lots of 'Render swap button' logs in the console

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1146]
Originally reported and discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1664444122568869
 Lots of 'Render swap button' logs in the console

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/27c09098-680f-400c-ad79-fee9f5084909)

**Expected**: we should remove, probably part of the refactor to check how many times were re-rendered the UI

**Comment by shoom3301** [comment]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/7122625/193509119-32421999-1553-4c0f-a658-7e19dd035cd3.png">

It's ok when `Verbose` log level is enabled

**Comment by elena-zh** [comment]
Thanks!
Closed then!
