### ISSUE TITLE
function getAllPrices still depends on legacy api-endpoint

### ISSUE THREAD

**Issue by josojo** [cowprotocol/cowswap#1178]
Hi guys,

not sure, whether I fully understand everything, but it seems that the the function 'getAllPrices' depends still on the legacy API. We really would like to kill this API endpoint and hence ask you guys kindly to change it.

I think the best endpoint for these requests  would be the `/quote` endpoint with a PriceQuality set to "fast". (Though i am not sure)

**Comment by alfetopito** [comment]
It has been removed https://github.com/cowprotocol/cowswap/blob/0a726582db7b64fff5f758ae8680ba3888165293/apps/cowswap-frontend/src/legacy/utils/priceLegacy.ts#L96-L95
