### ISSUE TITLE
[Mobile] - Swap modal not loading all the time

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#118]
**Description**
Every now and then the swap modal is not loading and you only see the background and the header and footer. After pressing swap or the home button it appears. 

**How to Reproduce**
1. Go to https://barn.cowswap.exchange/#/swap in MM browser
2. might happen that the swap modal is not visible

**Expected behavior**
swap modal should be visible from the begining

**Screenshots**
![IMG_0006](https://user-images.githubusercontent.com/34510341/128876404-972d90fb-949a-4ee5-a890-f5ddf2f2d915.PNG)

**Additional context**
In app MM browser
Iphone 11
iOS 14.6

I wasn't able to 100% reproduce it but it appears to be connected with switching between networks.

> Original issue https://github.com/gnosis/cowswap/issues/1223 by @MareenG

**Comment by elena-zh** [comment]
No longer reproducible
