### ISSUE TITLE
[ETH-FLOW V2] Confirm order with ETH modal appears in Expert mode

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1255]
Originally reported in https://github.com/cowprotocol/cowswap/pull/1241#issuecomment-1290337797

1. Open the app
2. Switch ON Expert mode in the settings
3. Connect to a wallet
4. Select ETH as a sell token, an amount < balance
5. Select To token
6. Press on Swap

**AR**: Confirm order modal appears

**ER**: Confirm order modal should not appear in Expert mode

**Comment by anxolin** [comment]
I think this one probably does't apply now we are doing the v2 of the Eth Flow. 

It's possible this issue will affect smart contract wallets, but for normal EOA it will follow the ETH Flow (it won't do this wrapping helper flow)

**Comment by alfetopito** [comment]
This has been addressed by Anxo and is live on prod
