### ISSUE TITLE
Success notification and balances are not in sync

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#126]
**Description**
Reported by @fleupold 

![image](https://user-images.githubusercontent.com/2352112/129910727-277b3b94-6196-4b78-b685-88a4cacba2a7.png)
![image](https://user-images.githubusercontent.com/2352112/129910740-9f592320-de6b-4055-8024-27fbbc9220e7.png)

Minor issue I just noticed when trying to sell all of one token for two other tokens consecutively:
I made a trade and the notification showed me that the trade had been successful. However, it took a good amount of time (~1min in my case) for this information to be reflected in the sell balance. When I tried to sell MAX in the I was getting an error that I don’t have enough funds (because I had already sold a part). Is there a way to update the balance as soon as we get the successful trade notification?

Ironically, on my second trade the sell balance updated first but the notification still showed pending for another 30s.
Is it possible to sync the “sell balance update logic” with the notification logic?

## Context: 

https://gnosisinc.slack.com/archives/CSGLUC1BN/p1629289823156800

> Original issue https://github.com/gnosis/cowswap/issues/1280 by @anxolin

**Comment by elena-zh** [comment]
The issue is still reproducible. 
@anxolin , are we going to address this issue in the near future?
