### ISSUE TITLE
Safe nonce not updated on sequent orders

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#1275]
**Description**
When placing 2 orders in sequence on a 1/N Safe, the Safe nonce is not updated and the status of both orders are mirrored

**How to Reproduce**
1. With a Safe that has 1/N signers (only 1 signer required to execute a transaction), connect to the CoW Swap app
2. Select a token pair for which you have funds. Allow the sell token if you haven't yet
3. Place two orders for the same pair in sequence
4. The Safe nonce, number and state of signatures is the same for both orders

**Expected behavior**
Each order should increment the Safe nonce
Each order should have the signature state match the corresponding Safe transaction

**Screenshots**

![Screen Shot 2022-11-03 at 10 52 18](https://user-images.githubusercontent.com/43217/199702883-0c704c95-3472-460e-9492-8b1970d9eeca.png)

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by elena-zh** [comment]
I have been able to reproduce the issue with nonce on Prod, however, I was not able to get 'the same' statuses for the signing block
![mot mirrir](https://user-images.githubusercontent.com/70885163/203630612-8d09a07a-2658-4029-8f53-a0b9cb131a17.png)

**Comment by elena-zh** [comment]
Hey @alfetopito , looks like the issue is fixed. Could you please check it on your side?

**Comment by elena-zh** [comment]
@alfetopito , could you please check whether this issue is still reproducible for you?

**Comment by alfetopito** [comment]
Nope, I get the correct nonce. Tested on prod

![image](https://github.com/cowprotocol/cowswap/assets/43217/46f2998c-fa33-42e4-a64b-ee2f509e7927)
