### ISSUE TITLE
Safe: Increase slippage tolerance and time for Safe Flow

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1278]

**Comment by MindyCoW** [comment]
We have clear feedback that letting Safe users set a custom expiration time (or at least increasing the default order expiration time) is a desired feature.

**Comment by elena-zh** [comment]
> We have clear feedback that letting Safe users set a custom expiration time (or at least increasing the default order expiration time) is a desired feature.

Hey @MindyCoW , there is another task #208 that is currently WIP. There is another solution to implement this. Could you please take a look at it?

**Comment by elena-zh** [comment]
I'm closing this task in favor of #208 and #4321
