### ISSUE TITLE
Slightly more WETH unwrapped than requested

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#128]
**Description**
I wanted to unwrap 0.5 WETH but 0.5025125 ETH was unwrapped. 
https://rinkeby.etherscan.io/tx/0xa5209572c3610cac85b7a25864588deaf12c96deae66281090932d57422e145f
This happened on Rinkeby in production.
I submitted another request to unwrap right after and the exact amount was unwraped.

<img width="1019" alt="Bildschirmfoto 2021-08-19 um 15 24 37" src="https://user-images.githubusercontent.com/34510341/130077742-809b0633-76a1-4177-b59a-51117b2249a3.png">

**Expected behavior**
Exact input amount should be unwrapped

> Original issue https://github.com/gnosis/cowswap/issues/1286 by @MareenG

**Comment by elena-zh** [comment]
I'm no longer able to reproduce this issue. 
Closing it for now, will reopen if I face it once again.
