### ISSUE TITLE
[ETH] Handle Order Rejection states

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1294]
Integrate stepper and order status with the rejection of orders.

![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/7d0bdadf-e5ca-4472-b1f4-fa96309e34fb)

Needs some context (enum of possible reasons). 
- The reason will be translated into a message and shown under the “Create Order” step

## Tasks 
- [ ] Handle rejected orders: Show status, and set state in the stepper
- [x] Show link to Explorer

**Comment by alfetopito** [comment]
Covered on https://github.com/cowprotocol/cowswap/pull/1724 when addressing #1299

**Comment by alfetopito** [comment]
Actually, haven't tested the error conditions by the backend (invalid quoteId, price quote expired, etc), so maybe not be done at all
