### ISSUE TITLE
Buy/sell URL Link on CowSwap

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#130]
This was feedback from one user:

![image](https://user-images.githubusercontent.com/2352112/130360595-2ca694e0-8f36-4589-a3bb-736ea82bfa40.png)

However, we already suport it. 

I think we should do 2 things:

1) Create some documentation in the dev portal on how to pre-fill the orders by creating your own link.
Relevant also for letting projects. For this part, we could have something very similar to https://uniswap.org/docs/v1/frontend-integration/custom-linking/ 

2) Have a nice set of small images, saying "Buy in CowSwap", with a placeholder for a token project. It could also be a snippet of HTML. Projects could use it in their home pages to let their users buy a token.

@avsavsavs @biocom WDYT? 

> Original issue https://github.com/gnosis/cowswap/issues/1299 by @anxolin

**Comment by elena-zh** [comment]
Seems that these changes have been implemented in #1703
