### ISSUE TITLE
[ETH] Cancelations: Toast Notifications

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1300]
Make sure the user gets notified once the cancelation is effective

## Tasks
- [ ] Handle toast notifications

## Context
- [Hard Cancelations](https://docs.google.com/document/d/1PvLHosAj2ZTkIFfBLRv_St-IsVtOgpwYDWnFhAJyE7Q/edit#heading=h.mazpu036s3yf)
-  [Figma Wireframes](https://www.figma.com/proto/sUwumNFlcslHzShSZJHVsS/2022_COW-Native-ETH-Flow?page-id=1201%3A382&node-id=1210%3A1334&viewport=-96%2C1616%2C0.19&scaling=min-zoom&starting-point-node-id=1204%3A674)

**Comment by alfetopito** [comment]
Works mostly out of the box.

![Screenshot 2022-12-14 at 17 54 20](https://user-images.githubusercontent.com/43217/207670753-7b61757e-b395-435a-b58e-92987c1f79dd.png)


Just need to address the case when the order is cancelled without it being created by the backend.
