### ISSUE TITLE
[ETH] Ensure unique orderId (edge case)

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1301]
> 🚨 Probably doesn't need any front-end work any more

There’s a technical issue that would make two orders receive the same orderId if they have the same parameters (token selection, amount, price)

## Open discussion
There's an open discussion, it's very likely this will be handled already by the quote API, so nothing will be needed in the Front-end: https://cowservices.slack.com/archives/C049GSMCTMW/p1667837475014909

## Context
- See more details on [this edge case](https://docs.google.com/document/d/1PvLHosAj2ZTkIFfBLRv_St-IsVtOgpwYDWnFhAJyE7Q/edit#heading=h.xelm6ufp0jfs)

**Comment by alfetopito** [comment]
FYI, @elena-zh already managed to reproduce this use case :)

See points 1 and 2 in this comment https://github.com/cowprotocol/cowswap/pull/1372#issuecomment-1316771495

**Comment by anxolin** [comment]
There's some development on the collision issue for ETH Flow.
Good thing: It turns our is not a big issue any more
Bad thing: we will need to add some checks in the FE (a bit of overhead)

CTX:
https://cowservices.slack.com/archives/C0361CDG8GP/p1669754873491389
