### ISSUE TITLE
[ETH] Use different contract for Barn

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1302]
In order for the backend to know if the order was created in production or in barn, there will be two contracts.

They will index both contracts, and they will know if the order is for barn/prod depending on which contract was used as the destination address.

## Tasks
- [ ] Adapt contract instantiation to detect if we are in barn/prod and use the right address

**Comment by alfetopito** [comment]
Implemented on https://github.com/cowprotocol/cowswap/pull/1509
