### ISSUE TITLE
[ETH] Address feedback from user sessions

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1308]
After launch, or near it, we expect to get some more user feedback.

This task is to address the relevant ones.

## Tasks
Pending defintion.
- [ ] Improve styles for “Switch to WETH” button in the banner. See https://cowservices.slack.com/archives/C049GSMCTMW/p1667236922842299
- [ ] Any other feedback or improvement??

**Comment by alfetopito** [comment]
Addressed the one from here https://docs.google.com/document/d/1BiDfEl1dtYTI8tIkC7yEXkRG0v9g1CZ8fMji3OWZ4I4/edit
