### ISSUE TITLE
[ETH] Hanle Automatic Refunds

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1314]
Get the automatic refund tx from the order details, and feed it to the stepper.

**Blocked**: Receive refund tx in the order details (API)

## Additional information
Handle states:
- REFUND_INITIATED
- REFUND_COMPLETED

* Updater:  Once the order is in expired state, we periodically check the API until we get the transaction
Represent the state change from expired to refund initiated

# Related 
Related to https://github.com/cowprotocol/cowswap/issues/1309

**Comment by alfetopito** [comment]
Partially handled.
App is now checking when the `isRefund` is changed to `true`.

Changes are coming that'll include in the response the `refundTxHash`

Will close this task once that's implemented

**Comment by alfetopito** [comment]
Actually, implemented on https://github.com/cowprotocol/cowswap/pull/1796

I tagged #1294 instead of this issue
