### ISSUE TITLE
Title on the Limit price modal shows incorrect value for the price

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1318]
1. Open Limit orders in regular mode
2. Select a token pair 
3. Hover on Price
4. Press on Review Limit order
5. Hover a mouse on the Limit Price value

**AR:** title shows value incorrect token value
![image](https://user-images.githubusercontent.com/70885163/202255420-e685a78f-9123-40cf-a5cb-caf911122590.png)

**ER**: title shows corect token value

**Comment by shoom3301** [comment]
@elena-zh I think we shouldn't link limit-orders issues to a release, because Limit orders module is not availabe for users
