### ISSUE TITLE
[1.24]Network switcher is hidden when change URL to an unsupported one, user is not connected

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1324]
Open the app as a not connected user
Change `chain=rinkeby` in the URL

**AR**: Networks warning appears, but there is no network switcher
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c1dcc583-232b-483e-aa2e-62460c86756b)
**ER**: Network switcher should be displayed, a user should be able to switch a network

**Comment by elena-zh** [comment]
A similar issue is related to the #1317 , originally reported in https://github.com/cowprotocol/cowswap/pull/1384#issuecomment-1314990553 (case 1): when change a network to 4 (former Rinkeby), he app does not show an error pop-up, no network switcher, and it does not appear when I change a network indicator to a supported network again (1, 5, 100)

![image](https://user-images.githubusercontent.com/70885163/201910938-6e9677ce-ee5d-406e-ad47-3ac77ec419bd.png)

**Comment by anxolin** [comment]
It's bad, and I think we should fix, but given that the user needs to do it

@nenadV91 maybe you can keep an eye, and see if this is a quick fix we could do. If no, we fix it after we are done with the current releases. Let's just not forget about it

**Comment by elena-zh** [comment]
No longer reproducible
