### ISSUE TITLE
Amount is not cleared out when press on Home button 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1327]
Related to #1317

1. Fill in the From fields, an amount
2. Switch to any page/disconnect a wallet
3. Press on the Home page

**AR**: the amount appears in the field each time when press on the Home button (even if the field has been empty before)
See the video:

https://images.zenhubusercontent.com/475419392/eee4e07b-c34e-43f0-8178-d99900445a1a/screenrecorderproject1.mp4 

**ER**: reset the form when press on Home button?

**Comment by shoom3301** [comment]
I'm nor sure that we need this feature. What is the goal of clearing the amount field?
@anxolin @elena-zh what do you think?
P.S. this issue is related to https://github.com/cowprotocol/cowswap/issues/1325

**Comment by elena-zh** [comment]
Hey @shoom3301 , I recorded a video that was not good to me in this case: 
1. I open Swap page, specify an amount
2. I open Account page, go back, **and see empty swap form**
3. I press on the Home page, and **see an amount again**. 

I agree that we can store tokens' info and amounts when we refresh page, navigate back to swap page (will be fixed in #1325), but it would be always great to have a possibility to reset a form, so I wrote it as a expected result.

**Comment by anxolin** [comment]
I would think this one is fine. Most of it, is a feature and not a bug :)  (I like we remember now the parameters)

I understand the issue you described with ETH and also the xDAI one. But it's not to problematic in my eyes. I think we can go without fixing this.
