### ISSUE TITLE
[1.24] apply the same pattern for URLs across the app

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1329]
Related to #1317 #1270

1. Open any content page (FAQ/About/Account/4040 page)
2. Check the URL 

**AR**:  `?chain=mainnet` presents there
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5467ac05-c249-490a-aaa8-7905068fdbc6)
check the Swap page: 
![image](https://user-images.githubusercontent.com/70885163/201361311-916d2f7c-9744-4630-a5d2-7235a1974296.png)

**ER**: it would be great to have the same pattern for URLs across the app

**Comment by shoom3301** [comment]
@elena-zh it should be there, we don't use `?chain=mainnet` only on Swap and Limit orders pages

**Comment by elena-zh** [comment]
@shoom3301 , I also thought that it might be acceptable, but then I became confused by this question: why do we have 2 network indicators in the URL for content pages? 
![image](https://user-images.githubusercontent.com/70885163/201038649-9e21da07-c73a-4303-8345-5591cab49b9f.png)

I think, 1 indicator is enough, that is why I created the issue.

**Comment by shoom3301** [comment]
/1/sgfdg/WETH - it's not a valid route. We can have as much as we want "network inidcators" :) Like that: `/1/1/1/1/1/1asdads/swap/sdf/1000/?chain=mainnet`

**Comment by elena-zh** [comment]
But anyways I would vote for applying the same pattern for all URLs in the app and keep this issue opened with a low priority.

**Comment by anxolin** [comment]
Why content pages have this network? In principle they don't need it.

 I agree with @elena-zh the URLs should be consistent.
If we change how we specify the network, we should keep it coherent.
