### ISSUE TITLE
Import token modal does not appear for the 2nd time when it was accidentally closed

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1330]
1. Open the Swap form on Mainnet
2. Paste into the URL token address /0x3B1f8CA43e04Abf5B867dBEF273B0CE1541AB0BD
3. Close the impot modal (press outside the modal)
4. Paste into the URL token address /0x3B1f8CA43e04Abf5B867dBEF273B0CE1541AB0BD once again

**AR**: there is no Import token modal
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fcd156ab-e0bd-4cb9-a695-e5db03c8d258)
**ER**: import token modal should appear

**Comment by shoom3301** [comment]
P.S. the bug is reproducible on prod as well:
https://swap.cow.fi/#/swap?chain=mainnet&outputCurrency=0x3B1f8CA43e04Abf5B867dBEF273B0CE1541AB0BD
