### ISSUE TITLE
 Mobile -Tooltips pointing is incorrect on the Swap form/Confirmation modal

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#134]
Reported in https://github.com/gnosis/cowswap/pull/1176#pullrequestreview-722442724

**Android** - all the time on the Swap form and on the Confirmation modal: 
![image](https://user-images.githubusercontent.com/70885163/128210066-c38724c1-0cbb-4c85-b4be-10daba88f111.png) 
![image](https://user-images.githubusercontent.com/70885163/128210097-3bbd106b-618b-4c3e-adc1-fcf4df412596.png)

**iOS** - when switch between regular mode and expert mode, and do not refresh the page, issue with 'flashing' tooltip appears again. Or tooltips are shifted:
![image](https://user-images.githubusercontent.com/70885163/128210351-d55842ed-eb20-4bc6-b630-f573c9134ad8.png)

> Original issue https://github.com/gnosis/cowswap/issues/1322 by @elena-zh

**Comment by elena-zh** [comment]
Still relevant, but has a tiny impact. Plus there was no any user complaints on this
