### ISSUE TITLE
[LIMIT] [7-Explorer] Show Fee for Executed Orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1348]
Once the order is executed, the backend will be able to calculate the actual fee.

We should make sure it is properly displayed in the order details.

Also, because the fee is taken from the surplus, we should make sure the surplus also reflects this.

## Implementation details
I would assume, that the fee could be part of the Order Details, so probably for the explorer, there's no change/work required, it will just work.  Maybe we have to see if we need to adapt the surplus calculation though.

**Comment by anxolin** [comment]
@nlordell are we still planning to do this one?

**Comment by nlordell** [comment]
Yes.

**Comment by anxolin** [comment]
Related to https://github.com/cowprotocol/services/issues/643

**Comment by nlordell** [comment]
Also worth referencing is the PR that introduces a new `executedSurplusFee` field which is the surplus fee that the order was settled with: https://github.com/cowprotocol/services/pull/828
