### ISSUE TITLE
[1.24] ETH token is not displayed in the Swap form when type it into the URL

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1351]
Related to #1317, #1270

ETH token is not displayed in the Swap form when type it into the URL
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1b8c3f02-8c13-4f10-a2b5-d966bd1ba3cb)

**Expected**: pick ETH token (or XDAI for GC)

**Comment by shoom3301** [comment]
@elena-zh looks like it's the same issue: https://github.com/cowprotocol/cowswap/issues/1321

**Comment by elena-zh** [comment]
@shoom3301 , nope. 
#1321 issue has been fixed in #1336 , and I created this issue on top of the changes in #1336 .

**Comment by shoom3301** [comment]
@elena-zh I mean, if you type ETH in uppercase, then it will be displayed correctly, won't it?

**Comment by elena-zh** [comment]
@shoom3301 , 
![image](https://user-images.githubusercontent.com/70885163/201047322-648ae927-027b-4f4e-a42e-4d08994eebd0.png)

**Comment by elena-zh** [comment]
Fixed
