### ISSUE TITLE
[1.24] 'WXDAI' icon is not correct in the Swap form

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1366]
Related to #1317

Open the app in Gnosis chain and check the WXDAI icon in the Sell/To fields

**AR**:  'WXDAI' icon is not correct
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e347487e-4fba-44c8-bffe-e74bd4e8f501)

**ER**: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e2ac0b9c-0f55-4765-ad0c-1c7ffa767048)

**Comment by shoom3301** [comment]
The wrong icon comes from https://tokens.honeyswap.org:
```
{
      "name": "Wrapped XDAI",
      "address": "0xe91d153e0b41518a2ce8dd3d7944fa863463a97d",
      "symbol": "WXDAI",
      "decimals": 18,
      "chainId": 100,
      "logoURI": "https://raw.githubusercontent.com/1Hive/default-token-list/master/src/assets/xdai/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d/logo.png"
    },
```

**Comment by shoom3301** [comment]
https://github.com/1Hive/default-token-list/blob/master/src/assets/xdai/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d/logo.png

**Comment by shoom3301** [comment]
PR: https://github.com/1Hive/default-token-list/pull/189
