### ISSUE TITLE
ETH flow: slippage tolerance is not returned back to the default value when turn ETHflow flag off

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1378]
Related to #1239
Reproducible **on the 1st time app opening only**

1. Open the app as a not connected user
2. Clear out your locak storage and do a hard reload of the app
3. Turn on eth flow localStorage.setItem('enableEthFlow', '1')
4. Turn off eth flow localStorage.setItem('enableEthFlow', '0')
5. Verify the slippage

**AR**: it is displayed as 2%

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9d3a61e3-60a8-4211-acc7-ec1c10ae7d58)

**ER**: it should go to the default value for the ERC20 orders

**Comment by alfetopito** [comment]
I'd say this is not a problem since we don't expect users to ever set the flag manually. Or even know about the existence of the flag at all

**Comment by elena-zh** [comment]
Closed then!
