### ISSUE TITLE
[1.24] Cow token with not correct address is displayed in Favourites in Gorli

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1380]
Related to #1317 

1. Open Tokens page in Gorli
2. Compare token addresses for the COW token in the Favoutrives and All tokens tables

**AR**: token addresses are different, incorrect one is in the Favourites tab

![correct.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/10316d25-75fe-4da2-93aa-3dbc9ea784f8)![not correct.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2e7a5a40-4eee-48a7-89d0-2b198eb6b009)

**ER**: token address should be the same  https://goerli.etherscan.io/token/0x3430d04E42a722c5Ae52C5Bffbf1F230C2677600

**Comment by anxolin** [comment]
This is weird, because is goerli is not super bad, bad the fact they don't match is concerning (looks like we have some code duplication or something?)

@nenadV91 can you look at this?

**Comment by elena-zh** [comment]
Fixed in #1387
