### ISSUE TITLE
[1.24] Network is changed to Ethereum when disconnect a wallet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1386]
Related to #1317

1. Open the app and connect a wallet in GC
2. Disconnect a wallet

**AR**: the network is changed to Ethereum

**ER**: the networks is not changed (GC remains)

**Comment by anxolin** [comment]
This is not ideal, I would only solve now if this was introduced in this version. Is this happening in PROD?

**Comment by elena-zh** [comment]
> This is not ideal, I would only solve now if this was introduced in this version. Is this happening in PROD?

@anxolin , no, this is not happening on Prod/Barn. Only in this version
