### ISSUE TITLE
'Fees exceed from amount' error on the Limit orders page 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1398]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1668435154080819

Should we display 'Fees exceed from amount'  error on the Limit orders page? We can't know the Fee that will be taken when an order is executed. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9e20393c-fc1d-428c-8b3d-c2b32c5b3cd7)

**Expected**: hide this error

**Comment by shoom3301** [comment]
1. Change text to "Sell amount is too small"
2. When trade is too small (for example less than fee amount), then show a banner like a "Your trade is too small and might not trade"
<img width="495" alt="image" src="https://user-images.githubusercontent.com/7122625/204762759-2aee4e49-7a93-46b3-b100-07d4ec37f5a1.png">
