### ISSUE TITLE
[1.25] Issues related to Swap container and orders

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1408]
Related to #1277

- [ ] Light and dark modes: arrow between swap fields is blurred
 ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/30d90ed2-98c7-433b-b7ec-a6fc9ea3b93b)

- [ ] Loader on the Approve button is almost invisible in the light mode: 
![loader almost invisible](https://user-images.githubusercontent.com/70885163/203062052-10f681c4-4ff1-45f2-8cd5-c0818c628f44.png)

- [ ] Max button is overlapped by the arrow in a Mobile view:
![image](https://user-images.githubusercontent.com/70885163/206219521-1ae0dd72-9e28-4799-9f6d-cde0950814fb.png)

- [ ] Warnings don't look good on classic ETH-flow modals
![warning](https://user-images.githubusercontent.com/70885163/205084482-2f6042ad-f7dc-4695-97ec-1e54ef514053.png)

- [ ] C O W buttons on the Order Submitted modal have different color in comparison with colors on the About page
![cow color](https://user-images.githubusercontent.com/70885163/206221300-bce18104-3e03-42d8-93a6-a3aa29030883.png)
![cow](https://user-images.githubusercontent.com/70885163/206221306-5694cf6d-bf93-406c-839b-4acaae410ce7.png)

**Comment by elena-zh** [comment]
Cases 1, 2, 3, 5, 8, 9 are fixed in #1416

**Comment by elena-zh** [comment]
I removed fixed cases from the issue description

**Comment by fairlighteth** [comment]
@elena-zh 

> Light and dark modes: arrow between swap fields is blurred

In what browser and device/viewport size this happens? As I can't reproduce it on Chrome or Firefox.

**Comment by fairlighteth** [comment]
@elena-zh 

> Light and dark modes: arrow between swap fields is blurred

In what browser and or device/viewport does it happen? As I can't reproduce it in Firefox and Chrome.

**Comment by elena-zh** [comment]
> @elena-zh
> 
> > Light and dark modes: arrow between swap fields is blurred
> 
> In what browser and or device/viewport does it happen? As I can't reproduce it in Firefox and Chrome.

Hey @fairlighteth , Win 11 +Chrome, Brave, screen 1920x1080

**Comment by fairlighteth** [comment]
This is Chrome 109 on Windows 11. I don't think it looks blurry compared to the other icons?

<img width="998" alt="Screenshot 2023-01-20 at 13 28 20" src="https://user-images.githubusercontent.com/31534717/213705954-897244e9-0f4f-4833-b749-564479d87be7.png">

**Comment by elena-zh** [comment]
This is how I see it: from my point of view it is a bit blurred
![image](https://user-images.githubusercontent.com/70885163/213723778-7a42be78-4eb7-4115-8695-220f10833ae1.png)
![image](https://user-images.githubusercontent.com/70885163/213723859-3f02b5d8-5899-4417-bc55-3605f5eb39a6.png)
It looks better in the light mode: 
![image](https://user-images.githubusercontent.com/70885163/213723927-7a9ab04c-a763-45df-80f1-a7c9aa3bce6e.png)

However, if it is takes too much time to fix, I vote for leaving it as it is ;)

**Comment by elena-zh** [comment]
Interesting fact is that the arrow begins look good to me when the scale is 120% :)
![image](https://user-images.githubusercontent.com/70885163/213724449-bfb8585b-88e4-4d97-b484-21d699df1d0c.png)

**Comment by fairlighteth** [comment]
Interesting. Let's make a low prio issue for this to investigate later?

**Comment by elena-zh** [comment]
> Interesting. Let's make a low prio issue for this to investigate later?

Reported #1919 issue for this
