### ISSUE TITLE
Lots of console logs, amounts are jumping when the page is opened in 2 tabs

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1415]
Might be related to #1390 

1. Open https://dev.swap.cow.fi/#/5/limit-orders/WETH in 2 tabs
2. Connect to a wallet
3. Unlock the page on one of the tabs
4. Open console logs
5. Change a token amount

**AR**: Lots of console logs, amounts are jumping on the Limit orders page
https://www.loom.com/share/c0255481fd6f40e99a0374006ce1c2cf
**ER**: no logs, amounts are not jumping

**Comment by shoom3301** [comment]
The source of problems: https://github.com/pmndrs/jotai/pull/1004/files
