### ISSUE TITLE
[ETHflow]: Order is changed to 'Filled' status without 'Open' phase

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1426]
Reported in https://github.com/cowprotocol/cowswap/pull/1372#issuecomment-1316771495 (case 6)
Discussed in https://github.com/cowprotocol/cowswap/pull/1372#issuecomment-1317446726

The issue is not always reproducible. Usually it can re reproducible on the 2nd trade

**Steps:** 
1. Enable new eth flow: on the console type localStorage.setItem('enableEthFlow', '1')
2. Select ETH token as a sell token in Gorli, an amount to sell
3. Select any ERC20 token in the To field
4. Run transaction and wait till it is executed
5. Change Sell amount and run ETH order once again
6. Open Account modal and trace the order statuses

**AR**: when the TX is executed (onchain), the order blinks in the Account moda, but stays in the 'Executing' state. The order is not in 'Open' status, and goes to 'Filled' when it is executed. `Valid to` is not changed to `Filled on`
![6 case.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9a4d226e-3277-40a9-8008-be8c6924a2c7)' ![6 case 1.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ed7c7cfa-95c6-4d15-b533-db27699f9164)

**ER:** Once executed, order goes to 'Open' status, The to 'Filled(if filled)

**Comment by alfetopito** [comment]
Should be fixed on https://github.com/cowprotocol/cowswap/pull/1724

**Comment by elena-zh** [comment]
Hey @alfetopito , I have just faced this issue when testing changes for #1739 PR
![hang](https://user-images.githubusercontent.com/70885163/207951449-1393cc88-39e6-42c9-9a84-6d2f976a3e84.png)
So I'm leaving the issue opened.

**Comment by elena-zh** [comment]
I have also noticed this behavior in the release branch #1740 :(
More often this happens when Order confirm modal is opened.

**Comment by alfetopito** [comment]
😞 

It's really hard to reproduce. Haven't managed to do so locally so far :/
When not on expert mode, either with the order placement modal or the activity details, the state updates fine.
I haven't seen it moving from creating to filled

We check every 2s for new info from the API

Could it be that for some reason you were testing with another browser window and/or several pending orders at the same time? And then the backend was throttling your requests (erro 429), causing it to fail some, until your IP was unblocked and eventually the response came through?

**Comment by elena-zh** [comment]
Hey @alfetopito , seems that I face the issue so often due to the app is opened in 2 tabs: in the 1st one I trace the stepped in Account modal, on the 2nd one - Order Confirm modal. 
When the app is opened in 1 tab only, it works fine.

**Comment by elena-zh** [comment]
I changed the issue priority to Low, as I don't think end users will face this issue too often.
