### ISSUE TITLE
Default price is incorrect when select a token pair

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1435]
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1668704302761189

1. on Gorli, open Limit orders page
2. Select WETH-DAI token pair

**AR**: price is 432183...(+163%). when press on the Market price is becomes 164265...
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/21204a41-1360-4f4e-9cba-5fb46ac7ae97)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7d793825-fb85-4370-abca-71f39ef10e32)

**ER**: price should more or less correspond to a market price

**Comment by nenadV91** [comment]
Asked BE about this since I think this is more related to the API response.
