### ISSUE TITLE
Approve button is clued to the Review button

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1446]
1. Open Limit orders page
2. Specify From token that is not approved, an amount to sell (< than the balance in the connected wallet)
3. Specify To token, price
4. Verify the Approve button: 

**AR**: Approve button is clued to the Review button
![allow button is clued.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/30c778cf-9cfe-492b-af39-4077095dab44)

**ER**: the button is not clued to the Review button

**Comment by shoom3301** [comment]
@elena-zh it seems to be already fixed
