### ISSUE TITLE
Spacing in the menu changes with different screen sizes

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#146]
**Description**
The spacing i the menu changes with different screen sizes

**How to Reproduce**
1. Go to Cowswap
2. Open menu
3. Change screen size

**Expected behavior**
Spacing should be equal for all screen sizes

**Screenshots**
Normal
<img width="1168" alt="Bildschirmfoto 2021-09-03 um 10 52 02" src="https://user-images.githubusercontent.com/34510341/131980379-b5edc597-d211-4bba-b254-ae3f700c915d.png">
Reduced
<img width="1064" alt="Bildschirmfoto 2021-09-03 um 10 52 16" src="https://user-images.githubusercontent.com/34510341/131980410-9b57de8b-5d7d-4f4f-b674-c3d5f79c31a5.png">
Mobil
<img width="776" alt="Bildschirmfoto 2021-09-03 um 10 52 34" src="https://user-images.githubusercontent.com/34510341/131980421-cce0e3e8-94e3-4da3-9569-018cd252bfac.png">

> Original issue https://github.com/gnosis/cowswap/issues/1384 by @MareenG

**Comment by elena-zh** [comment]
No longer reproducible
