### ISSUE TITLE
Checking texts in Limit orders page

### ISSUE THREAD

**Issue by shoom3301** [cowprotocol/cowswap#1462]
1. Tooltip text with explanation:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/7122625/203322654-9ef75d72-0f1f-4e40-9377-8daadae2b722.png">

2. Tooltip texts for Expiry/MEW protection/Order type items:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/7122625/203322847-1cb08360-cd5d-4c5f-9da7-2ec6efb561f3.png">

3. Text for the whole container and the link for "Learn more..."
<img width="522" alt="image" src="https://user-images.githubusercontent.com/7122625/203323032-e8a9a68f-7c97-47ae-9a8a-4c2fcc74b2f5.png">

4. Link for "Learn more..."
<img width="503" alt="image" src="https://user-images.githubusercontent.com/7122625/203323103-623c22a6-7848-4d20-b0a9-cacb27a75ca5.png">

5. Link for "Read more..."
<img width="494" alt="image" src="https://user-images.githubusercontent.com/7122625/203323177-ee891b9b-02ef-4a7d-8dd9-a10e054a450b.png">

6. Text of the tooltip
![image](https://user-images.githubusercontent.com/7122625/203324414-8e3cd386-f6da-432a-b40d-c6276de0751f.png)

7. Text of the tooltip
![image](https://user-images.githubusercontent.com/7122625/203324454-01b62d83-14ba-495f-863e-1b3c66f48ee1.png)

**Comment by elena-zh** [comment]
It would be great to add a text to the 'Recipient' field on the Order confirmation modal 
![image](https://user-images.githubusercontent.com/70885163/203324313-f60a3339-d51c-4122-9b90-e23b94d16fc3.png)

**Comment by elena-zh** [comment]
It is also would be great to have updated messages on the Orders table when: 
 - a user is not connected
 -  a user is connected to an unsupported network (I second: 'Please connect your wallet to one of our supported networks: Ethereum, Gnosis Chain, Görli')
 - a user does not have opened orders
 - a user does not orders at all (order history)
![image](https://user-images.githubusercontent.com/70885163/203347078-b711a749-5b64-4593-a837-7aeaceb0e7d2.png)

**Comment by elena-zh** [comment]
For the 6 and 7 cases I would like to suggest to add a bit more explanation how to proceed when such situation happens https://github.com/cowprotocol/cowswap/pull/1437#issuecomment-1323891328

**Comment by shoom3301** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/7122625/205016268-1c390401-bae2-49fc-8bd5-6587cc630438.png">
@MindyCoW I'm very sorry for the late call, but we also need texts for these tooltips

**Comment by elena-zh** [comment]
Hey @MindyCoW , could you please take a look into this message and clarify whether is sounds good to you? 
![image](https://user-images.githubusercontent.com/70885163/205029756-6bd354e4-1f5e-40d8-9945-bdd34bbb7342.png)

We show this message to warn a user that his trade amount is too small and will not cover fees, so we prevent him from this trade. 
Implemented in https://github.com/cowprotocol/cowswap/pull/1553#issue-1469479510

**Comment by MindyCoW** [comment]
@elena-zh For this message, could we write "Fees are greater than order amount"? Is that too long? Eventually we need to keep the "Swap" text but disable the button, and show this error elsewhere. Users don't expect to see error text on the Swap button.

As for the order receipt tooltips, I'm trying to get more information about those in this Slack thread: https://cowservices.slack.com/archives/C0361CDG8GP/p1669887355578709

**Comment by elena-zh** [comment]
> @elena-zh For this message, could we write "Fees are greater than order amount"? Is that too long? Eventually we need to keep the "Swap" text but disable the button, and show this error elsewhere. Users don't expect to see error text on the Swap button.

The point is that it sounds a bit illogical on the Limit orders page to show "Fees are greater than order amount", as we don't know the exact amount of fee that will be taken from the Surplus at a moment of an order execution. 
Also, we don't take fees at a moment of an order placement. 
So that is why we decided to rewrite this message.

**Comment by MindyCoW** [comment]
"Sell amount is too small" also sounds quite illogical though from the user's standpoint. Why is it too small? 

For now, let's leave "Sell amount is too small." We'll change this later as part of a general improvement.

**Comment by MindyCoW** [comment]
@shoom3301 I shared the receipt modal tooltip messages in Slack, but sharing here as well: 

**Status**
N/A (there shouldn’t be a tooltip here)

**Limit price**
You will receive this price or better for your tokens.

**Execution price**
An order’s actual execution price will vary based on the market price and network fees.

**Filled**
CoW Swap doesn’t currently support partial fills. Your order will either be filled completely or not at all.

**Order surplus**
The amount of extra tokens you get on top of your limit price.

**Fee**
CoW Protocol covers the fees by executing your order at a slightly better price than your limit price.

**Created**
Your order was created on this date & time. It will remain open until it expires or is filled.

**Expiry**
If your order has not been filled by this date & time, it will expire. Don't worry - expirations and order placement are free on CoW Swap!

**Order type**
Orders on CoW Swap can either be market orders (which fill at the market price within the slippage tolerance you set) or limit orders (which fill at a price you specify). 

All orders are currently fill or kill, but support for partially fillable limit orders is coming soon!
