### ISSUE TITLE
Balances are not updated in the translated app

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#147]
Related to #1385, #1372

1. Translate the app using google translator
2. select a token pair , enter an amount
3. then swap tokens (change in From-To)

**AR**: balances are not updated
![balances.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/144f056a-19de-4022-bf73-7d745d8eb137)
![balance](https://user-images.githubusercontent.com/70885163/131692321-68a1a84c-211e-4df9-a7e2-b9b1f0a3110b.jpg)

**ER**: balances are updated

> Original issue https://github.com/gnosis/cowswap/issues/1387 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
