### ISSUE TITLE
UI issues with translated app + not translated areas

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#149]
Not all areas can be translated:
1. Manage token list
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/60dffd30-2a9b-44a3-8a4c-d9a427737dd7)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3b62641a-0d15-433d-bdcc-00bad3709ddc)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/21b4e43a-9de6-4fd7-904a-5179f4da8ad6)
2. Waiting for confirmation modal
![image](https://user-images.githubusercontent.com/70885163/209171490-cf9d11f2-5146-447a-b82e-c18059a07e35.png)
![image](https://user-images.githubusercontent.com/70885163/209171521-5bff3944-1f93-4e32-b224-87b28373ca8d.png)

3. Import token/Import token list
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/38ea283e-8d93-48b2-99c7-ee481e350e21)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/500b0f13-a4d6-48e4-86d4-e403dbfc421c)
4. Cancel order warning
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3755facd-23e0-4b11-947b-337a4f522d9e)

> Original issue https://github.com/gnosis/cowswap/issues/1398 by @elena-zh

**Comment by elena-zh** [comment]
Closing for now
