### ISSUE TITLE
Update messages on classic ETH flow modals

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1491]
It would be great to update texts on classic ETH flow modals when we launch native ETH support:
![message.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/95a9e6b4-8d18-497e-afab-f5a0cbfbca47)![messa 1.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7b693d9f-3ffc-4eb7-8918-dbc9d7a879be)![mess 3.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f51e01d9-d324-429e-a9a9-840aa9683214)![mess 4.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f4f2a850-97b3-4d8f-bc27-11e073ccdad2)

**Comment by anxolin** [comment]
Good point! Adding it for the lists of musts

**Comment by elena-zh** [comment]
Fixed in #1738
