### ISSUE TITLE
Mobile: Refreshing leads to disconnected Wallet 

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#15]
# Description 

If I am connected to a wallet in a mobile device, I'm disconnected when I refresh the page

# Reproduce
Open the app in a mobile device
Connect to a wallet
Refresh the page

**AR**: wallet is disconnected

https://user-images.githubusercontent.com/70885163/146341289-497e118a-f1a0-4d59-9ac4-602943d13fee.mp4

**ER**: wallet should remain to be connected

> Original issue https://github.com/gnosis/cowswap/issues/297 by @MareenG

**Comment by elena-zh** [comment]
No longer reproducible
