### ISSUE TITLE
Your orders table to not connected user

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1503]
Reported in https://github.com/cowprotocol/cowswap/pull/1470#issuecomment-1326600143 (case2)
Currently, the table looks this way: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ac135ca9-b5ef-4cbc-be36-030293df49ca)
It would be great to add a specific icon/message there.

**Comment by anxolin** [comment]
See also https://github.com/cowprotocol/cowswap/issues/1566#issuecomment-1332498392
