### ISSUE TITLE
Issues with price impact banner

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1515]
-- [ ] 1.  **There should be NO checkbox on the warning in the Expert mode:** ![no box.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/4dc239d1-6bcf-4fb0-a60f-55dbd214a297)

_____________________________________________

- [ ] 2. Impossible to uncheck the Price impact on Swap form in regular mode
![should not be checked](https://github.com/cowprotocol/cowswap/assets/70885163/2d0002f9-c9db-4056-9c5a-6b8081823f80)

**Comment by elena-zh** [comment]
One more issue is related to Limit orders form: 
When I check the banner on the form and open Order confirm modal, the box becomes unchecked: 
![keep checked](https://user-images.githubusercontent.com/70885163/214043514-c6f3b043-368a-4709-bc3c-0453d197aa11.png)

It would be great to keep the box checked unless the trade is placed.

**Comment by shoom3301** [comment]
Fixed in https://github.com/cowprotocol/cowswap/pull/3418
