### ISSUE TITLE
No warning when MAX ETH is selected to sell

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1523]
Discussion: https://cowservices.slack.com/archives/C0361CDG8GP/p1669642067245999

There is no warning now when I select an amount of ETH equal (or close to equal) to the ETH balance in the wallet. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f2137c6f-e809-4a5e-8b64-ae10152a93eb)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6a53cf68-62c7-4360-ad67-b715a24b7767)
It would be nice to add it (like we do for a classic ETH flow now) to the Order Confirmation modal

**Comment by anxolin** [comment]
This is a great idea, good catch 👍
