### ISSUE TITLE
MM injected browser: message to sign transaction appears again and again when cancel transaction

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#154]
1. Open the app in the injected MM browser
2. Specify tokens to sell/buy, amount to swap
3. Press on the Swap button
4. Cancel signing transaction in the MM modal

**AR**: message to sign transaction appears again and again
https://drive.google.com/file/d/1mgXx0V5SqU28OU9GH6SwJI15g7v7vzbM/view?usp=sharing

**ER**: message to sign transaction is not displayed after cancelling

> Original issue https://github.com/gnosis/cowswap/issues/1444 by @elena-zh

**Comment by elena-zh** [comment]
Still reproducible.
