### ISSUE TITLE
[LIMIT] [10-Analytics] Metadata: Type of Orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1542]
**Description**
Include order type for onchain analytics.

CoW Protocol supports three type of orders – market, limit and liquidity:
- **Market order**: Buy or sell at the current market's best available price.
- **Limit order**: Buy or sell at an arbitrary price specified by the user.
- **Liquidity order**: Source of liquidity provided by Market Makers.

This information will be part of the JSON data include as an IPFS hash in the order's `appData`

The spec will be provided here:
https://github.com/cowprotocol/app-data

The proposal will be to include a new metada type (just like we do with `quote`  and `referrer` ([see schemas](https://github.com/cowprotocol/app-data/tree/main/src/schemas))

The new metadata will be called `class` and it will look like:

```ts
class: {
   type: 'market' | 'limit' | 'liquidity',
   version: 0.1.0
}
```

## Deprecated
Initial proposal, only kept just to don't loose the context of the thread. 
```json
 "orderType": {
      "type": "sell",
      "class": "limit",
      "partiallyFillable": false,
      "version": "0.1.0"
    }
```

where:

* `type`: sell | buy
* `class`: limit | swap | liquidity

cc/ @bh2smith @gentrexha @nlordell

**Comment by nlordell** [comment]
Oops, this is the `orderType` schema.

I'm not sure why we need to include `type` and `partiallyFillable`. They are already part of the order.

**Comment by bh2smith** [comment]
Looks good to me. I suppose this will require a version bump on the app data object.

**Comment by nlordell** [comment]
I would propose just adding:
```json
    "additionalParameters": {
      "class": "limit",
      "version": "0.1.0"
    }
```

I would call it `additionalParameters` as this is probably where we want to add soft `validFrom`s to orders if we do so in the future (since this *needs* to be signed somewhere, otherwise you can open to some kinds of attacks).

**Comment by anxolin** [comment]
> I would call it additionalParameters as this is probably where we want to add soft validFroms to orders if we do so in the future (since this needs to be signed somewhere, otherwise you can open to some kinds of attacks).

I'm not sure I understand this. 

For `validFrom` I understand there will be a custom integration, maybe that deserves a new metadata, or we can always version and add fields to `orderType` if needed. But I'm not sure I understood the point

**Comment by nlordell** [comment]
My point is that we should use the new field for additional parameters for controlling orders and not just order type information.

Why should we add `"type": "sell"` and `"partiallyFillable": false` if these are already part of the order that the appData is from? It feels counter-intuitive to me to duplicate this data.

**Comment by alfetopito** [comment]
1. Definitely there should be a version bump on parent (0.4.0 -> 0.5.0)
2. Agree `orderType` and a nested `type` property are redundant (as well as `partiallyFillable`). After all this info is already part of the order
3. While I do agree `additionalParameters` is better, isn't everything in the appData technically additional parameters to the order? What about just:

```
class: {
   type: 'market' | 'limit' | 'liquidity',
   version: 0.1.0
}
```

**Comment by anxolin** [comment]
Perfect! Makes sense to me. 

I'm more inclined to call it `class ` than `additionalParameters`. Reason is, technically everything is "additionalParameters".  It's meta-data to complement the info of the order. 

For a `validFrom` we can look later where it fits. 

So everyone cool with Leandro's proposal?  I will update the description

**Comment by bh2smith** [comment]
I notice that we keep adding new "versioned" objects to the metadata. Are we ever actually going to edit the existing objects? I mean whats the point of having all these different versions of sub-objects if we never actually plan to extend them.

**Comment by anxolin** [comment]
> Just discovered this repo (I do not know how I got there): https://github.com/cowprotocol/app-data

One theory is that you found it in the description of this issue :P

**Comment by bh2smith** [comment]
This is 8 months old. Is this actually a thing that happened or not?
