### ISSUE TITLE
Join discord window is not center-aligned in big screen resolutions

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#155]
Reproducible in Prod/Stage/Barn/Dev

1. Open the app on the screen with 1920x1080 resolution
2. Press on the Feedback icon
3. Press on the 'Contact us' link in the Feedback modal (or press on any invitation link to discord from the app - https://discord.com/invite/MHmz3knm2X)

**AR**: join discord window is not center-aligned 
![ff shifted.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9ead35cd-d2db-4504-84da-abfe7d464fff)

**ER**: join discord window is center-aligned 

> Original issue https://github.com/gnosis/cowswap/issues/1459 by @elena-zh

**Comment by elena-zh** [comment]
The issue is not on our side: it appeared, that the behavior is exactly the same when follow invitation URLs from different projects.
