### ISSUE TITLE
Don't show approve button when error is displayed

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1559]
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1669812205358909

**Approve button:**

1. is not displayed on the Swap form when an error message is on the form.
2. is displayed on the Limit order page in the same conditions
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bc676070-e33f-4bba-8322-f4d105895039)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e7c4b7f9-feaf-4691-ac72-8d7333101fbc)

**Expected**:  use the same behavior on both forms and hide Approve button from Limit orders page in this case.

**Comment by anxolin** [comment]
Agree, better to hide the button. Low prior though

**Comment by elena-zh** [comment]
Fixed
