### ISSUE TITLE
Show in the orders table the connect button

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1566]
**Description**
Nitpic request to make the message of connecting your wallet more visual

<img width="2040" alt="image" src="https://user-images.githubusercontent.com/2352112/204863013-36c2e3bf-5b39-4530-8316-d8bb1bd0d9ac.png">

It could be more something in line of what we show when we don't have orders:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2352112/204862805-630d7adc-8f8c-4e8f-9922-9d44a1ceb42a.png">

Idea (Kidding!)
![image](https://user-images.githubusercontent.com/2352112/204863779-76b4af65-5896-449e-a967-73586554436c.png)

**Comment by elena-zh** [comment]
Duplicates https://github.com/cowprotocol/cowswap/issues/1503
