### ISSUE TITLE
Add possibility to hover cursor to a tooltip content

### ISSUE THREAD

**Issue by shoom3301** [cowprotocol/cowswap#1573]
Context: https://docs.google.com/document/d/1au3_QDBkzo4CgW9TlmHcQWMEnsQUaH7m0UItgnFEke0/edit#heading=h.k5r88fsd9cme

<img width="606" alt="image" src="https://user-images.githubusercontent.com/7122625/205035544-dc27c0c1-7f65-47ef-a6a1-46e590ec705b.png">

Change text of the tooltip to:
>This order is still open and valid, but you haven’t given CoW Swap sufficient allowance to spend [TOKEN]. The order will become executable when you approve [TOKEN] in your **account token page**.

account token page - add a link to `/account/tokens`

To do this, firstly we must improve tooltips. Currently, the tooltip hoddens when you lose focus from the element.

**Comment by elena-zh** [comment]
Related to #194
