### ISSUE TITLE
Better error handling - switching between networks in confirm swap modal

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#158]
**Description**
When switching between networks while already the confirm swap modal is open there is no proper error message

**How to Reproduce**
1. Go to cowswap
2. Place a swap
3. Click on swap
4. Instead of confirm swap change network

**Expected behavior**
An error message should appear 
Best case the desired swap remains( input token and sell/buy amount) and is adjusted to the new network 

**Screenshots**
https://user-images.githubusercontent.com/34510341/134506627-b3a1af89-fc5a-44b6-8ba1-a8c3b1ecdeee.mov

> Original issue https://github.com/gnosis/cowswap/issues/1464 by @MareenG

**Comment by elena-zh** [comment]
Duplicates #1052
