### ISSUE TITLE
Slippage rounding issues when calculating  Min Received and Max sent amounts

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#159]
When we set slippage 0,5%, in most of cases amounts are calculated based on 0.4975% slippage.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/893867be-93b9-43b5-bc9e-2479f375b9c5)

for 1% slippage amounts are calculated based on 0.99% slippage
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0fb65080-ed60-46aa-8879-dfe3dd83a16a)

The issue is: when sell/but amount is greater, the difference is more visible. 

**Expected**: amounts should be recalculated based on the exact slippage?

> Original issue https://github.com/gnosis/cowswap/issues/1465 by @elena-zh

**Comment by elena-zh** [comment]
closed as logic of slippage calculation is changed in #739
