### ISSUE TITLE
App doesn't allow to pick ETH when ERC token selected in To field

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1592]
Discussed in https://cowservices.slack.com/archives/C044B50A02F/p1669910141382009

The app auto-reverts ETH to WETH in the Sell field when an ERC20 token (but WETH) is already selected in the TO field, so it makes an impression that a user can't wrap a token. 

> I think the ETH wrapping doesn’t work on the limit interface (not referring to the native flow but the wrapping)?

**Expected**: not auto-revert ETH to WETH, but show a warning and auto-replace it with WETH at a moment of an order placement?

**Comment by MindyCoW** [comment]
This should be fixed now.
