### ISSUE TITLE
Issues with Approve button when a token is partially approved

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1594]
Approve button is still displayed when a token's amount is approved: 
1. Approve a certain amount of a token to spend (e.g.100)
2. Select this token in the Sell field
3. Select a token to Buy, specify a buy order (sell amount is < than approved amount, e.g.99)
 **AR**: the Approve button appears: 
![image](https://user-images.githubusercontent.com/70885163/214079230-8b3d37d9-2fb0-4342-8428-0902d22a63e4.png)
![image](https://user-images.githubusercontent.com/70885163/214079325-4296eabc-7baf-4968-ad2e-985d99ce1901.png)

**ER**: Approve button is not displayed. 

This issue was reported in Discord as well https://discord.com/channels/869166959739170836/869170873033166868/1067031125735768114

**Comment by anxolin** [comment]
This looks bad indeed
