### ISSUE TITLE
Limit price is lower than specified for Buy order

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1595]
I placed a Buy Limit order with limit price =  13. 
When I [signed](https://protocol-explorer.dev.gnosisdev.com/gc/orders/0x518434c960c4435275555a885238525769961628113152001b70f9ced7ecd42f9fa3c00a92ec5f96b1ad2527ab41b3932efeda586389f682) an order, limit price became 12,999999999
![13.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ff50caf3-44e0-4107-894e-46c959eca923)![less.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/855216b3-9d70-4883-90fd-5c32de71397d)

**Expected**: price should be the same

**Comment by anxolin** [comment]
Although the price difference is not a lot, I find it bad that we modify the user's price in the actual order.

Here you can see how although the user selected 13, the price is smaller in the order they sign.

![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/e1965992-a3eb-4813-8e28-8938cff8bf44) 

Worth reviewing if this is covering up some bigger rounding issue.
