### ISSUE TITLE
Improve presentation of error messages

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#16]
Might be cool to add some cow theme to the error messages (e.g. sad cow or cow tipping image, spilled milk...) 
<img width="405" alt="Bildschirmfoto 2021-03-25 um 10 50 40" src="https://user-images.githubusercontent.com/34510341/112456399-075ce180-8d5b-11eb-9136-dd9e8c02612f.png">

> Original issue https://github.com/gnosis/cowswap/issues/339 by @MareenG

**Comment by elena-zh** [comment]
Closing this. Will reopen or create a new task if we decide to implement this
