### ISSUE TITLE
Slippage field is lost in Regular mode

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1609]
Introduced in recent PRs
Reproducible in DEV/BARN

Open the Swap page in  in DEV/BARN
**Modify a slippage in Regular mode** --> no slippage field in the bottom of the form
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c9018e8e-259e-4375-a09b-ab8a4ae109a6)
**Press on Swap in the regular mode** --> no slipage on the Order confirm modal
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0d8d27f8-6eb7-4241-b822-d6bb30fe4b1d)

**Expected**: Slippage field should present:
 - Expert mode: at the bottom of the Swap container when a trade is specified
 - Regular mode: at the bottom of the Swap container when modified
 - Regular mode: in the Order confirm modal (always)

**Note**: The issue is not reproducible in #1514 (RC 1/25)

**Comment by fairlighteth** [comment]
Can't reproduce this on release/1.25

<img width="521" alt="Screenshot 2022-12-06 at 12 12 33" src="https://user-images.githubusercontent.com/31534717/205909530-4957e369-d233-4ddf-a1fa-028510642ba3.png">
<img width="498" alt="Screenshot 2022-12-06 at 12 12 13" src="https://user-images.githubusercontent.com/31534717/205909546-ddeb32f6-84b9-40e2-a9c8-5030f77e0111.png">

**Comment by elena-zh** [comment]
> Can't reproduce this on release/1.25
> 
> <img alt="Screenshot 2022-12-06 at 12 12 33" width="521" src="https://user-images.githubusercontent.com/31534717/205909530-4957e369-d233-4ddf-a1fa-028510642ba3.png">
> 
> <img alt="Screenshot 2022-12-06 at 12 12 13" width="498" src="https://user-images.githubusercontent.com/31534717/205909546-ddeb32f6-84b9-40e2-a9c8-5030f77e0111.png">

Yes, I mentioned about it in the issue description: 
![image](https://user-images.githubusercontent.com/70885163/205911145-000f1b6e-90df-45f4-b75d-49950016cc25.png)

The issue is reproducible on Barn/Dev.
