### ISSUE TITLE
Gnosis Safe issue approving tokens

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#1638]
**Description**
Stucked in pending

From @fleupold 

> Probably less pri than limit orders and ETH flow but I’m having problems with approving tokens from my [Safe](https://app.safe.global/gor:0xABd7085B88f67a6b6589dC4e3E2b6f72A275C716) via WalletConnect (signer threshold of 2). All approvals get stuck in pending state (see screenshot).
I believe this is because the app is waiting for the SafeTxHash and not the actual transaction hash to mine. When I click on “view details” in the screenshot I get taken to https://goerli.etherscan.io/tx/0x1fd6680e8231cdae9fc850a01b70a0281e8003021c6e8f0c8e3bab8a87a70c0a but the real tx hash after executing was 0x0c3df7dc66252f3d1ea43ca0bd63b6283c81fb7f74743585e6e865d41974ac92 (see 2nd screenshot)
Getting out of this “pending” state is really tricky (it blocks me from trading). I tried removing local storage and so on, but really the only thing that helped was reloading the site in a new browser and reconnecting WalletConnect from there.
It’s working fine when using the Safe App (however, because I don’t have signer keys on my phone that are funded to execute, using WC signing on mobile and executing in the Safe Web UI is my preferred process over using the Safe App in the browser where I would have switch back and forth to execute the tx).

**Context**
https://cowservices.slack.com/archives/C036G0J90BU/p1670405506132579

**Comment by fleupold** [comment]
I'm pretty reliably able to repro

1. Go to swap.cow.fi
2. Connect a Safe via their Web UI & Wallet Connect
3. Approve a token

This will cause the UI to look for the "Safe tx hash", which is different than the actual hash of the tx that will get mined. In the example, safe tx hash was 0xe55dcf98d47ffd7b42bc7d3e17b93a311809ec80720aa6bd8896a4a203bbd830 but the tx mined was https://goerli.etherscan.io/tx/0x71d96faaeeb5fd287eed88920e402cbc9878bb56dcbe4cabfc774679aa6229fc

<img width="957" alt="image" src="https://user-images.githubusercontent.com/1200333/223504882-b3c761a6-89c8-460c-8dd0-32c1a1d60c96.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/1200333/223504989-5ba73db6-8ded-470b-9fad-fdd2b722bd9b.png">
