### ISSUE TITLE
[EthFlow] Update Fees tooltip

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#1647]
# Summary

Update feel tooltip when on ethflow to reflect the fact that it does cost gas to place the order

<img width="456" alt="image (1)" src="https://user-images.githubusercontent.com/43217/206196526-6c82eed8-a3f4-4dfb-b880-ad645c849ee1.png">

**Comment by MindyCoW** [comment]
For ETH orders, the user pays a gas fee in ETH + the fee in their buy token listed in the UI? Is that right?

**Comment by MindyCoW** [comment]
Got it. So where it says "Fees (incl. gas costs)" that doesn't actually include the gas costs in this scenario?

We should probably instead have something like: 

> Fees: SELL TOKEN AMOUNT + ETH AMOUNT

and in the hover we'll say something like: 

> Trades on CoW Swap usually don't require you to pay gas in ETH. However, when selling ETH, you do have to pay a small gas fee to cover the cost of wrapping your ETH.

**Comment by alfetopito** [comment]
> where it says "Fees (incl. gas costs)" that doesn't actually include the gas costs in this scenario?

I believe the rationale for this is that the fee taken (in the sell token) is for (1) protocol fees (which we don't charge) and (2) gas costs incurred by solvers to execute your trade.

So no, does not cover the gas costs of the Ethflow transaction as you pointed out.
