### ISSUE TITLE
GIV price is way off and is making the slippage look very bad.

### ISSUE THREAD

**Issue by GriffGreen** [cowprotocol/cowswap#1653]
**Description**

I wanted to change the link to Cowswap (instead of honeyswap) in the Giveth Dapp... but i can't with this issue. :-/

The slippage for GIV doesn't make sense, and dissuades people from trading... maybe it is a rounding error? Or maybe we are using the price from mainnet instead of gnosis chain?

Either way when buying $1 of GIV, there shouldn't be hardly any slippage.

<img width="691" alt="Screen Shot 2022-12-07 at 2 54 38 PM" src="https://user-images.githubusercontent.com/14945613/206282319-b7df0d5c-d219-44a6-a13c-b6668284d5ae.png">

**How to Reproduce**
1. Go to https://swap.cow.fi/#/100/swap/WXDAI/GIV
2. put in 1 wxdai
3. See slippage

**Expected behavior**
The price should be the market price on gnosis chain, and given our deep liquidity, for $1 the slippage should be very small, like sub 1%

**Comment by fairlighteth** [comment]
I successfully reproduced and also compared with other DEXes. It seems like a USDC estimation error of GIV?

**Comment by elena-zh** [comment]
> I successfully reproduced and also compared with other DEXes. It seems like a USDC estimation error of GIV?

Should be, as values in tokens are more or less the same 
![image](https://user-images.githubusercontent.com/70885163/206403900-256fa61e-6a51-45a3-8ce6-a986b427e3c6.png)

**Comment by anxolin** [comment]
According to Coingecko our USD estimation is very wrong. 


<img width="650" alt="image" src="https://user-images.githubusercontent.com/2352112/206474133-49285097-2922-4fe6-9941-0974a494aebb.png">

Aren't we using Coingecko?

**Comment by GriffGreen** [comment]
I think the problem is that you are using coingecko. 

The price on Gnosis Chain should be the price of the GNO-GIV pair on honeyswap (Our largest pool)
