### ISSUE TITLE
Token list: 'Broken' token icon looks like a white circle in the light mode

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#167]
Proposal https://cowservices.slack.com/archives/C0361CDG8GP/p1663932082960319
 In the dark mode missing icons look like 'forbidden' icons, in the lignt mode these icons look like white circles. 

See images: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d689b80b-7c45-41cc-8e4f-8dd4cf42d5c1)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/49c05517-61b4-4835-9be5-6cb98df67f6b)
![image](https://user-images.githubusercontent.com/70885163/191959944-3295762e-eba4-4ec0-a1e7-d0cf84c08e25.png)

It would be great to change the icon to a better one.

**Comment by elena-zh** [comment]
The icon looks nice on hover action
![image](https://user-images.githubusercontent.com/70885163/169279262-b1435dc6-67ab-4240-97b1-2d4c852d8b21.png)

**Comment by elena-zh** [comment]
No longer reproducible
