### ISSUE TITLE
[1.26] Price label may be shifted

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1675]
Price label may be shifted. See the image: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0c76563a-ab0c-48e3-ab78-75ea87da9e4d)

**Expected**: label is not shifted

**Comment by shoom3301** [comment]
@elena-zh I don't see the problem now:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/7122625/207542065-32e32801-9819-44ed-a83e-82886ac93f12.png">
