### ISSUE TITLE
[1.26]Amount color is changed when price updated warning displayed

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1681]
1. Specify **Buy** order, an amount to trade
2. Switch ON the dark mode
3. Press on the Swap button
4. Do not close the modal until Price Updated warning appears

**AR**: Sell amount color is changed
![color.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f79854bf-2c03-476e-ae18-26764111288f)
**ER**: Sell amount color is the same

**Comment by shoom3301** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/7122625/207514948-158e6c3e-25b6-406e-9de6-1d079eb332dd.png">

I don't see the problem now. P.s. it's not related to Limit orders.
@elena-zh
