### ISSUE TITLE
TX expiration label does not show decimals

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1719]
1. Set TX expiration time to 2.5 minutes
2. Check the label on the Swap form

**AR**: TX expiration label does not shoe decimals
![tx expiration.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c906cc95-2877-4034-a6c5-0c6cb9d768af)

**ER**: 2 options: 
 1. Show decimals on the form
 2. Disable decimals for the deadline field

**Comment by alfetopito** [comment]
That's because the value input is rounded to an integer
Maybe we should just prevent decimals from being inserted

**Comment by elena-zh** [comment]
Agree! Anyways, trivial priority for now :)
