### ISSUE TITLE
Issues with order confirm modals in Android 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1755]
Tested on Huawei P20 (Android 12):
1. Scroll appears on the Order confirmation modal, and it is hidden under the modal name
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a0e3c9e1-d5c3-4cf6-bd11-6b144a420770)

2. Cancel order modal does not cover the whole screen
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f7fa63ac-0020-4c63-abdb-583d2aef95ce)

**Comment by fairlighteth** [comment]
This should be fixed in https://github.com/cowprotocol/cowswap/pull/1769

**Comment by elena-zh** [comment]
@fairlighteth , yes. 
In order to make issue auto-closed, could you please connect them to a PR where they are fixed? So fixed issues won't remain opened. 
![image](https://user-images.githubusercontent.com/70885163/208909500-8d4f40c8-eba9-4974-8521-2acda3ed7713.png)

Thanks!
