### ISSUE TITLE
[1.27] Include gas into fees USD estimation for ETH orders

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1760]
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1671448086123639

USD estimation here does not include the gas estimation:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f1595202-727d-48ae-b524-b208cf572135)

**Expected**: it should include gas USD estimation

**Comment by anxolin** [comment]
Yes, it's a good point. We also don't show it when you wrap, or for pre-sign.

I haven't heard many complaints, but it makes sense to me to be as transparent as possible
Maybe this should be done not just for ETH Flow, but a complete revisit of how we show the transactions and the fees

**Comment by elena-zh** [comment]
Closing for now
