### ISSUE TITLE
[1.27] ETH orders are not included into Total trades calculation 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1761]
Reported in https://cowservices.slack.com/archives/C049GSMCTMW/p1671449138396399

ETH orders are not taken into account for  the Total trades calculation. Relevant for both Staging and Prod APIs
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/46f00fcb-f74f-46f0-af86-7212288f4657)

Account details from the screenshot https://explorer.cow.fi/address/0xd9D244DF6992E930169703A3b2ee005eCE834692

**Expected**: trades should be included into the Total trades, and they should be reflected in Affiliate flow

**Comment by anxolin** [comment]
@josojo, it is not urgent, but can you involve the data team for this one?

**Comment by josojo** [comment]
I made a thread over here: 
https://cowservices.slack.com/archives/C0361CCTFD5/p1671450757611819

**Comment by elena-zh** [comment]
Closed as Total trades card was removed from the Account page
