### ISSUE TITLE
Statuses are not left-aligned on the Your orders table

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1783]
1. Create some limit orders
2. Cancel one of them
3. Check statuses

**AR**: Statuses are not left-aligned on the Your orders table![statuses.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5aa03b38-a348-41af-9c60-c3e38b73fb17)

**ER**: statuses are left-aligned

**Comment by Sahad-09** [comment]
Hey i would like to work on this
