### ISSUE TITLE
Possible to cancel ETH order after its expiration

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1788]
Reported and discussed in https://github.com/cowprotocol/cowswap/pull/1756#issuecomment-1362652763

Cancel order button is still enabled when an order is cancelled on Explorer, but not in CoW Swap yet. And it calls onchain transaction.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/aee4a073-1489-42bc-ba4c-4c78997fc1ef)

**To reproduce:** 

1. Pick ETH as sell
2. Make sure deadline and slippage are set to the minimum possible (10min and 2% respectively) to make your life easier
3. Pick as buy a token that you have enough funds to move the liquidity a few %
4. Fill in a significant ETH value, for example 0.5 ETH per BAT token to cause 5% in the price impact
5. Place 2 the same orders one after another
6. One order should match and move the price enough so the other order becomes out of market
7. Open order details on Explorer and wait until the pending order expires
8. Go back to Explorer and check the order

**AR**: The order is in Open status up to 1 minute. It is possible to call 'Cancel' TX request from there

**ER**: Hide cancel button? OR do not wait up to 1 minute before changing the order's status to Expired.

**Comment by anxolin** [comment]
According to Leandro this can only happen for a few seconds. Has to do with the updaters, so we put this in the freezbox until we deal with the refactor of them. Also, has a low impact, since it's a unlikely that the user will want to cancel precisely after its expired, and if they do they will just get the money back (so not terrible)

**Comment by anxolin** [comment]
We had in fact one case where a user canceled days after 🙈

It happened only once. But anyways... let's see if it happens again. 
Hopefully, this one will disappear when we finish the updater's refactor
