### ISSUE TITLE
Expert mode toggle has different colors for ON/OFF option

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#184]
Related to #1594, #1645

1. Open settings
2. Observe Expert mode toggle
3. Switch on/off expert mode

**AR**: Expert mode toggle has different colors for ON/OFF option
![off.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9ea3cada-5dba-4b7e-a6ab-93a8aa6d78ce)
![on.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3cba99ed-79fa-494d-b140-afd4773ec1be)
![off black.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9e32a6c3-3e34-4bd7-81a1-28490c660258)
![on black.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bc430c8a-6f84-4718-a8b4-f83121513570)

**Expected**: color should be the same (orange)

> Original issue https://github.com/gnosis/cowswap/issues/1646 by @elena-zh

**Comment by elena-zh** [comment]
No longer relevant in 1.21.0
