### ISSUE TITLE
Enhance Limit order form when token name is long

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1852]
Reported in https://github.com/cowprotocol/cowswap/pull/1843#issuecomment-1378742950

To reproduce: On limit orders, load token https://etherscan.io/token/0x2E2A42fbE7C7E2FfC031BAF7442dBE1F8957770a
See the form:
![image](https://user-images.githubusercontent.com/70885163/211816372-c075b46a-62a1-4129-a3b0-dbe540c992ef.png)
![image](https://user-images.githubusercontent.com/70885163/211817570-ce1a1746-7814-4218-b2ee-585c315445bc.png)

**Expected**: Enhance Limit order form when token name is long

**Comment by fairlighteth** [comment]
When I test this token on release/1.29.0 https://swap-dev-git-release-1290-cowswap.vercel.app/ it crashes. This happens consistently:

<img width="1056" alt="Screenshot 2023-01-11 at 16 46 54" src="https://user-images.githubusercontent.com/31534717/211865941-b412cbc0-765e-410a-a06d-f33ef7bea10f.png">

<img width="1375" alt="Screenshot 2023-01-11 at 16 47 14" src="https://user-images.githubusercontent.com/31534717/211866029-dfebdd60-9588-4375-bcdf-e9a77de9788f.png">

<img width="1374" alt="Screenshot 2023-01-11 at 16 47 24" src="https://user-images.githubusercontent.com/31534717/211866073-a2f4b8cb-3ccf-43ee-9ef6-4ab712f9f2c2.png">

<img width="1359" alt="Screenshot 2023-01-11 at 16 47 33" src="https://user-images.githubusercontent.com/31534717/211866110-7dcbf5ab-33e2-4790-b0be-dc62f592535d.png">

**Comment by alfetopito** [comment]
@fairlighteth the fix wasn't in the release branch, sorry for that!
I have now added it
