### ISSUE TITLE
The app broke when type anything instead of # in the URL

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#189]
A real edge-case: the app broke when type anything instead of # in the URL

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/cd8ec317-4beb-4f74-8283-36ba23e54316)

**Expected**: show 404 error page?

> Original issue https://github.com/gnosis/cowswap/issues/1674 by @elena-zh

**Comment by elena-zh** [comment]
similar to #4582
