### ISSUE TITLE
Rounding in fee overview

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#19]
**Describe the bug**
The displayed **to** value does not always follow rounding rules. 
In some cases it was just cut and in other cases it is rounded

**How to Reproduce**
1. try different values and tokens for trading 
2. observe fee overview

**Expected behavior**
A consistent approach should be followed. Either cut off the numbers after a certain amount of significant digits or apply rounding rules. 

**Screenshots**

<img width="528" alt="Bildschirmfoto 2021-04-07 um 13 18 15" src="https://user-images.githubusercontent.com/34510341/113858183-bbbb2680-97a3-11eb-8337-acddeb2f4098.png">

**Additional context**
Could this be due to the fact that the **before fee** value is a cut/ rounded value and the **to** value is calculated with the exact amount?

> Original issue https://github.com/gnosis/cowswap/issues/389 by @MareenG

**Comment by elena-zh** [comment]
Should be fixed in #1885
