### ISSUE TITLE
Allow "," when inserting a slippage value

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#191]
**Description**
When using "," instead of "." for the slippage the inserted value is detected as 0. 

**How to Reproduce**
1. Go to Cowswap
2. open settings
3. Insert slippage using like 0,5 or 0,1 click anywhere
4. Click outside of the modal
5. see that slippage is set to 0%

**Expected behavior**
It should also work if a user uses "," instead of the "." as it is done eg when inserting a tokem amount

> Original issue https://github.com/gnosis/cowswap/issues/1685 by @MareenG

**Comment by elena-zh** [comment]
I'd propose to make the input locale-dependable and show a comma or a period for a decimal amount according to it.

**Comment by elena-zh** [comment]
One more enhancement is that it would be nice not to allow input periods/commas into the field in the decimal part: 
![image](https://user-images.githubusercontent.com/70885163/209927659-d5a65164-37d4-4c90-b106-c936af9895da.png)
