### ISSUE TITLE
Change price impact tooltip text

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1921]
Price impact tooltip/explanation is not clear to users. So it would be great to change it.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a3d5e63b-7f71-4288-8a8c-23e5f2bf1c44)

Currently is displayed on: 
 - Swap form
 - Swap order confirm modal
 - Limit order form
 - Review limit order modal.

@MindyCoW , could you please provide the text?

**Comment by MindyCoW** [comment]
The price impact indicator should be **removed entirely** from the Limit Order interface. 

In the Swap interface, the new text should be: 
**Price impact due to current liquidity levels**

Did we ever implement the ability to put clickable links inside tooltips?

**Comment by elena-zh** [comment]
> Did we ever implement the ability to put clickable links inside tooltips?

Not yet. We had [an attempt to implement this](https://github.com/gnosis/cowswap/pull/1761) . 
And currently, there is a task #1573  for this in the backlog

**Comment by MindyCoW** [comment]
Ideally if we get that implemented, we would then enhance this tooltip with a link to an article to educate the user about price impact.

**Comment by shoom3301** [comment]
@MindyCoW Hi! Do we have a link for the tooltip?

**Comment by elena-zh** [comment]
Text LGTM in #2935 .
As for the Limit orders page, we have a separate task #1627 for the indicator (and logic) improvement. 
As for the link, @MindyCoW , please let me know, so I will create a separate task for this.

**Comment by MindyCoW** [comment]
We could link to this page: https://help.crypto.com/en/articles/7891394-what-is-price-impact

**Comment by elena-zh** [comment]
I opened #2989 issue for this. 
cc @shoom3301
