### ISSUE TITLE
Swap button remains to be displayed  in the clicked state when cancel order/quit a confirmation modal

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#193]
The video is recorded when testing a PR, but it is reproducible on **Prod/Stage/Barn/Dev**

https://watch.screencastify.com/v/REksaI3mG7bm8GeHSzPe

**Steps**: 

1. Open Swap page
2. Connect to a wallet
3. Specify tokens to sell/buy, an amount
4. Press on the swap button
5. Close the confirmation modal/cancel an order signing
6. Trace 'Swap' button behavior.

**AR**: the button is in 'clicked' state
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/661761be-ca4a-4f9e-87ef-ef2e3ce1b3e8)
**ER**: the button in the regular state 

> Original issue https://github.com/gnosis/cowswap/issues/1742 by @elena-zh

**Comment by elena-zh** [comment]
No longer relevant in v1.25
