### ISSUE TITLE
[MEV Slicer] Text on the 'Play MEV Slicer' button is white-colored

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#196]
Light mode
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a85098c9-0dcb-4729-8506-914dcafe568d)

Dark mode: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/95da9b7a-570d-4e88-ba13-c003bbd65ac3)

I think that text color on the button should be similar as in other app's buttons (connect wallet/swap/etc)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c7496990-d739-4188-849a-0343c469da0a)

> Original issue https://github.com/gnosis/cowswap/issues/1763 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible. 
![image](https://user-images.githubusercontent.com/70885163/161519088-ed96618c-9108-4a55-8adf-54f92fcd382f.png)
