### ISSUE TITLE
Missing areas for amounts refactoring

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1975]
Reported in https://github.com/cowprotocol/cowswap/pull/1907#pullrequestreview-1285252360 (case 14)
No formatting for: 
 -  ~~cancel and cancelling modals~~
 - ~~fees~~
 - Account details
![not formatted](https://user-images.githubusercontent.com/70885163/216991069-6e92d892-f2cd-4f79-9286-eb4944f4860f.png)

**Expected**: use the same formatting rules as elsewhere in the app

**Comment by tukantje** [comment]
On develop, formatting on these parts seem correct to me (as opposed to on swap.cow.fi). Not super sure if I am missing something, but feels like a stale ticket.

As far as I can tell in the code, relevant places have formatter calls. I think these ended up being updated when @shoom3301 's _Amounts formatting refactoring (#1907)_ was merged.

**Comment by elena-zh** [comment]
Hey @tukantje , I have retested the app in Dev. 
Indeed, fees and amounts on confirmation modals look good now. However. amounts are still not formatted on the 'Account overview' page in the Affiliate Program section. 
![image](https://user-images.githubusercontent.com/70885163/218433587-64cc3d0c-0852-42fe-9f0e-b844fcabafe6.png)

To reproduce: 
1. Using this wallet https://www.impersonator.xyz/ , connect to this address 0xFF714b8b0e2700303eC912BD40496C3997ceEa2b on Etherscan to CoW Swap using WC
2. Open https://dev.swap.cow.fi/#/account?chain=mainnet and verify amounts.

**Comment by elena-zh** [comment]
Hey @shoom3301 , just to confirm: I can see that amounts on the wrapping/unwrapping/order confirm/cancel/cancelling modal, and on fees look like refactored ones and correspond to the rules you described in https://github.com/cowprotocol/cowswap/pull/1907#issue-1550466287

Does that mean that not highlighted amounts should not be refactored?
