### ISSUE TITLE
The app is crashed when connect to Coinbase extention

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1985]
Win11+Chrome

1. Install Coinbase Chrome extension
2. Open CoW Swap and  connect it to the Coinbase wallet Chrome extension
3. Call the Coinbase extension: 

**AR**: the app is crashed![crash.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/077d3a88-279f-4a08-ad82-04fa14723c34)

See the video: https://www.loom.com/share/5ae3fb79b2a94e5dbc081bb74287d611

**ER**: the app is not crashed.

**Comment by alfetopito** [comment]
What was the version of the extension?

I just tried with v 3.7.0 (updated today, Feb 14 2023) both on MacOS and Win11 and it works

![image](https://user-images.githubusercontent.com/43217/218715194-1cdbf172-5dd7-4da5-b08f-1f7b81ca30cc.png)

Although there's a scary warning from the wallet about cowswap...

**Comment by elena-zh** [comment]
So I'm closing the issue for now, as it is not related to our changes. Thank you @alfetopito for checking it.
