### ISSUE TITLE
App icon looks like a broken one for some wallets

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#201]
The issue is reproducible on Prod https://cowswap.exchange/#/swap

When I connect to TrustWallet, TokenPocket, MM, Safe (mobile) I see a 'broken' icon
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3ca54d1b-5759-45ca-90d4-c6410a74906c)

imToken: no icon at all
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9706a8dc-41f9-4db8-a45d-4dcd3c5069be)

> Original issue https://github.com/gnosis/cowswap/issues/1792 by @elena-zh

**Comment by elena-zh** [comment]
no longer reproducible
