### ISSUE TITLE
[1.34] 'The app is loaded outside safe context' error in the console

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2018]
When I load the Swap page, I see 'The app is loaded outside safe context' error there. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6c178f6d-dfa6-4a97-8ae4-4846ba528a59)
Discussion: https://cowservices.slack.com/archives/C0361CDG8GP/p1676463512153429

**Expected**: no such error

**Comment by tukantje** [comment]
As far as I can tell this seems to be happening because of `@gnosis.pm/safe-apps-sdk`

https://github.com/safe-global/safe-apps-sdk/issues/265 as per this discussion;

> If you want to use the dApp outside the Safe web app, you can use the WalletConnect protocol. It’s impossible to use the Safe App SDKs without loading the app inside the Safe interface.

**Comment by alfetopito** [comment]
As mentioned in the thread, this issue is limited to: Safe wallets connected via Wallet Connect

**Comment by elena-zh** [comment]
Hey @alfetopito , turns out that the issue with not finalizing transactions is reproducible on Prod as well. So I created a separate issue for this https://github.com/cowprotocol/cowswap/issues/2022
Hence, the error reported here does not affect anything, so it is not a blocker for the release

**Comment by elena-zh** [comment]
The issue is reopened as the error is displayed on Staging.swp.cow.fi
![image](https://user-images.githubusercontent.com/70885163/233648366-a78bba1f-cc7c-42d1-b26a-7db2cd2974ba.png)
