### ISSUE TITLE
404 page appears when enter a slash after the URL

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#202]
It might seem as an expected behavior, but, seems to me, we can do something with this.

When I enter an URL https://cowswap.exchange/#/swap/ I get the 404 error

It would be nice to handle this case somehow and do not show 404 page for an URL with the slash as we do for cases: 
https://cowswap.exchange/#/swap?
https://cowswap.exchange/#/swap#

> Original issue https://github.com/gnosis/cowswap/issues/1794 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
