### ISSUE TITLE
[Pre-sign]: Open gnosis safe mobile app when press on 'View Gnosis Safe' link in a mobile app version

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#203]
1.  open the app in a mobile browser
2. Connect to a Gnosis safe
3. run a transaction
4. Press on the 'View Gnosis Safe' link

**AR**: user is navigated to the Gnosis safe web app
https://images.zenhubusercontent.com/192335743/f8a181d4-2097-4780-8a24-3c9503a5133b/rpreplay_final1636390659.mp4

**ER**: it would be nice to navigate a user to the mobile app

> Original issue https://github.com/gnosis/cowswap/issues/1801 by @elena-zh

**Comment by elena-zh** [comment]
Fixed
