### ISSUE TITLE
[Affiliate]local storage data may be deleted when switch between accounts

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#204]
Originally reported in 
https://github.com/gnosis/cowswap/issues/1821#issuecomment-966213717

I noticed, that local storage data may be deleted at a moment. 
Try to catch at which exactly one

I have done several transactions with this accout: wrap/unwrap/approve token, then I have had cancelled and expired transaction. 
https://protocol-explorer.staging.gnosisdev.com/address/0x7bc89822e9353b0b1cffcd61b73e32b848bb2caf
Afterwards I switched to another account, returned back and placed a successful order.
So you can see that transactions history is empty, no referral code is stored in the local storage
![local.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/202c6f09-7492-4693-9840-680f2462c3b6)

**Steps:** 
1. share a referral code to an account
2. switch to another account
3. go back to the 1st account
4. navigate to the profile page

**AR**: local storage is cleared out, transactions history is missing

> Original issue https://github.com/gnosis/cowswap/issues/1822 by @elena-zh

**Comment by elena-zh** [comment]
No longer relevant as the affiliate section is removed
