### ISSUE TITLE
Swap page remains open after wallet is disconnected

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#205]
**Description**
After I disconnected the WC connected wallet the swap page with all the inserted details remained open:
<img width="1439" alt="Bildschirmfoto 2021-11-16 um 10 13 15" src="https://user-images.githubusercontent.com/34510341/141957465-7ff053b7-3251-48d6-81df-d025adea9d06.png">

In Production the input is cleared if the wallet is disconnected: 
<img width="1404" alt="Bildschirmfoto 2021-11-16 um 10 16 36" src="https://user-images.githubusercontent.com/34510341/141957360-caf1c776-6d45-4800-a02a-60b2b7102fa7.png">

> Original issue https://github.com/gnosis/cowswap/issues/1840 by @MareenG

**Comment by elena-zh** [comment]
Fixed in v 1.23
