### ISSUE TITLE
Wrap/Unwrap/Approve transaction is pending forever when reject it in the Safe

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#207]
1. Connect to a Gnosis safe
2. Create a Wrap/Unwrap/Approve transaction 
3. Sign the transaction as the 1st owner
4. As the 2nd owner, reject the transaction
5. As the 1st owner, execute rejection transaction
6. Verify the Cowswap transaction's log when the transaction is executed

**AR**:  transaction is pending forever (up to 24 hours or until the local storage is cleared out)

![pending forever.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d3aaa610-4ec2-456d-a694-a9cb441bcd27)

**ER**: handle this case better.. as an example, add something like a 'rejected' status

> Original issue https://github.com/gnosis/cowswap/issues/1852 by @elena-zh

**Comment by elena-zh** [comment]
closed in favor of #2393 and #245
