### ISSUE TITLE
[Develop] Possible to select 2 tokens in the From/To fields on Limit orders page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2122]
1. Open Limit orders page
2. Select FROM/TO tokens, an amount and a price
3. Open TO field and select the same token as in the From field

**AR**: it is possible to select the same token
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/100c08cc-6363-4484-b8cc-a6344686f043)

**ER**: it is impossible to select the same token

**Comment by anxolin** [comment]
Why are we getting so many regressions? I don't remember we changed many things that would impact there.
