### ISSUE TITLE
Thousand separators in all formatted amounts

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#213]
**Description**
Large numbers are hard to read.

It would be good to use thousand separators.

This applies to formatted amounts texts, but also amount inputs. 
Some UIs uses spaces as a thousand separator for the input fields. 

Some other issue to solve is that is currently imposible to copy/paste an amount that has thousand separators directly to the sell/buy input field. This is very inconvenient. 

**Proposal**
One option is to use the locale of the users, other approach echanges like 1inch use, is to use a space.

> Original issue https://github.com/gnosis/cowswap/issues/1897 by @anxolin

**Comment by elena-zh** [comment]
Closed for now
