### ISSUE TITLE
Price out of market message after an order placement

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2134]
I have noticed that  'Price out of market' message appears right after an orderr placement in Barn API.  In Prod it works fine.

However, orders are executed
 ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/804e127f-813c-4a78-acc8-1b16abb636ca)

Order details: Buy: https://dev.explorer.cow.fi/orders/0x77c13299e1b0b7a699e41208ffe3179795aae808d029d95b988a0e15eb64a70e9fa3c00a92ec5f96b1ad2527ab41b3932efeda58640a006c
Sell: https://dev.explorer.cow.fi/goerli/orders/0xf4112d38d49ea968728e91d53d2765a1f07402f5a4c8c1eff9d6273d53712d369fa3c00a92ec5f96b1ad2527ab41b3932efeda586419d56b

**Comment by elena-zh** [comment]
The issue is also reproducible on Prod. To reprpoduce: place an order 1000 COW per USDC
![image](https://user-images.githubusercontent.com/70885163/226916598-e6716790-4068-4ee9-9e89-a42ade69136c.png)

**Comment by shoom3301** [comment]
I did some investigation, please contact me before fixing it

**Comment by shoom3301** [comment]
A new idea for the issue:
We should add an event to Sentry log each time when we get "Open Price out of market message" message
