### ISSUE TITLE
A lot of errors in console when switch wallet from Gnosis safe to EOA

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#215]
1. Connect the app with EOA wallet
2. Connect the app with Gnosis safe wallet
3. Open Activity modal and press on the Change Wallet button

**AR**: a lot of errors appear in the console
Video: https://watch.screencastify.com/v/4giVBoBtnu4fWbAc8iTO
![safe errors.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c0df5ebf-a8ee-410f-bc89-af1d0eaade29)

**ER**: hide these errors

> Original issue https://github.com/gnosis/cowswap/issues/1902 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
