### ISSUE TITLE
Unsupported token message is not removed from Limit orders page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2158]
1. Open Limit orders page
2. Select Gnosis chain network
3. Select token pair: WXDAI-AST
4. Change AST token to XDAI

**AR**: Unsupported token message is still displayed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/029c49d6-2d40-4372-9c12-0d9630cdab60)
**ER**: Unsupported token message is no longer displayed

**Comment by elena-zh** [comment]
One more case: Sell amount is too small message is not removed from the form. 
**To reproduce:** 

1. Open Limit orders page
2. Select token pair: WETH-USDC
3. Set too small value for WETh token (0.0001)
4. Change USDC to ETH

**AR**: Sell amount is too small message is not removed from the form. 
![unwrap](https://user-images.githubusercontent.com/70885163/227498180-0dc5821e-46b0-45a6-82c2-3d38efb4e9cd.png)

**ER**: the message should be removed.

**Comment by anxolin** [comment]
@tukantje are we planning to fix this one?

**Comment by elena-zh** [comment]
Fixed
