### ISSUE TITLE
[1.31] Zengo: can't sign transaction when connect to iOS ZenGo app

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2159]
1. Update ZenGo wallet to the latest version in iOS
2. Open CoW Swap and connect to the ZenGo wallet
3. Try to run any onchain transaction/place an order

**AR**: no order confirmation modal apears in the wallet
in iOS it forces to download an empty file
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/91917b0f-5aca-4b63-93a7-c1e5096e8d66)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f80aa1ea-ae32-4edf-8064-1709fd09e67c)
**ER**: it should be possible to confirm an order

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.
