### ISSUE TITLE
stETH token: search by a name and address return tokens with different names

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2181]
Reported in https://cowservices.slack.com/archives/C04R908KBTR/p1679906604619879

1. Open CoW Swap
2. Expand a token list
3. Search steth token by name, check its descrtion
4. Search this token by address https://etherscan.io/address/0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84, check its desription

**AR**: token is found in the list when search for it by name, and is not found (proposed to import) when search for it by address. 
Tokens have different description
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a27d9adf-adee-4b6b-b72f-d1c681e2b756)![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fdf9f7c2-1927-4c59-8cce-9df6d92f108f)
**ER**: only 1 token should be present in the the list and have the same description

**Comment by elena-zh** [comment]
One more case that might be related to the issue https://github.com/cowprotocol/cowswap/pull/2235#pullrequestreview-1368669636

**Comment by tukantje** [comment]
Upon further research, I've noticed that this is the behaviour that UniSwap exhibits as well.

The main difference for them, is that they don't show an Import button, ever. Behaviour is shown when you click on it; and you get an import popup.

I'll draft a PR on this however please do note that this will represent a change from the behaviour of uniswap vs. us.
