### ISSUE TITLE
[1.32]Enhance 'Will execute soon' message when not enough balance/allowance

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2193]
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1679992088702599
Related to #2139 
It would be nice not to show 'Will execute soon' when not enough balance/not enough allowance warnings are  displayed.
OR it would be nice to change a message to 'Top up your balance, and the order will executes soon' and 'Give permission to spend you token, and the order will executes soon'

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/49b210b4-64e8-4fde-8fe0-a6c62796949e)

**Comment by alfetopito** [comment]
Addressed on https://github.com/cowprotocol/cowswap/pull/2225

Right?

**Comment by elena-zh** [comment]
@alfetopito , yup!
