### ISSUE TITLE
Lot of Metamask errors in the console after accounts changing

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#220]
1. Connect to a MM
2. Change a connection to WC
3. Disconnect the WC wallet

**AR**: the app's connection comes back to MM, but there is a lot of running MM errors in the console
![mm errors.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5926356d-114e-44b5-a998-c195124cb539)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/afa392e5-90d8-453d-af1a-ea1d121c7d4a)

**ER**: no errors in the console

**Note**: errors are not displayed after the app reload

> Original issue https://github.com/gnosis/cowswap/issues/1931 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
