### ISSUE TITLE
[1.32] Add Price out of market warning to the Your orders table

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2205]
1. Place two Market orders that can affect a price (I placed 2 orders to sell 50 GNO per BAT). Make sure that you get more than 5% of the price impact
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3854c96f-c22d-49c7-b94a-6f31033ef65a)
2. Wait till 1 of them is executed --> 2nd order cant be executed as Price is OOM
3. Check the Your orders table on the Limit orders page

**AR**: there is no Price OOM message
![OOM.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/52c185e3-62ff-4882-881e-4b2744389a4f) ![OOM2.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/4cca4a90-1a59-4f06-a91b-590052b98a6e)

**ER**: it would be great to add it

**Comment by alfetopito** [comment]
I think this no longer applies:
1. Swaps are no longer in this table
2. If the prices move, the executes at will show the order as out of the market already

I followed the steps in this issue and the indicator shows the order as out of the market
![image](https://github.com/cowprotocol/cowswap/assets/43217/fab4f0f0-791f-4821-9dce-deded2a03fea)
