### ISSUE TITLE
User interface suggestion: if recipient address is set, clear it after the trade

### ISSUE THREAD

**Issue by vbuterin** [cowprotocol/cowswap#2215]
Cowswap has a feature that allows you to set the recipient address for a transaction. This is really useful for payments: if someone expects me to send them 1800 USDC and I don't have USDC, I can send a single transaction where I just send WETH or some other asset, and they get the USDC.

However, in my experience it makes it easy to make a particular mistake: if my most recent use of cowswap was for a payment, and the next use is for a trade for personal use, then I might forget to remove the recipient address, causing the previous payee to get the funds of the next trade.

I propose a simple fix: the recipient address, if set, should be cleared after the trade in the UI (or at the very least, it should not persist between sessions). I don't think there are any uses of a persistent recipient address that are anywhere near as common as the swap-to-pay use case I mentioned above, so I expect the safety and convenience gains of making this change should greatly outweigh the downsides.

**Comment by anxolin** [comment]
Hi @vbuterin! 

We appreciate your feedback, and we want to let you know a new version has been released improving the Recipient logic. 

Let us know if this works for you and if you have any other improvement requests that would make your experience in CoW Swap better.

For the release notes https://github.com/cowprotocol/cowswap/releases/tag/v1.32.1

Cheers
