### ISSUE TITLE
[1.33]Order receipt: order type does not show if it is a partially fillable

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2244]
Reported in https://cowservices.slack.com/archives/C044B50A02F/p1680519213679879?thread_ts=1680519125.760059&cid=C044B50A02F 
Order type (on receipt) is not clear it’s a partially fillable order
![image](https://user-images.githubusercontent.com/70885163/229556118-29c01780-a909-4cb7-853b-f1d553fce0f4.png)

**Expected**: show Partially fillable in the order type

**Comment by alfetopito** [comment]
Addressed on https://github.com/cowprotocol/cowswap/pull/2269
