### ISSUE TITLE
[1.33]Unfillable orders when reload the page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2246]
Reported in https://cowservices.slack.com/archives/C044B50A02F/p1680519818986669?thread_ts=1680519125.760059&cid=C044B50A02F

When refreshing the page with pending limit orders, unfillable and low balance warnings are displayed (quickly) until the data is loaded. 
This also happens if the web refreshes for updating the price
See the video: https://www.loom.com/share/8e609226321e449b9fc916863f41b7b3

**Expected**: Show a loader or a table skeleton effect when the data is being loaded?

**Comment by alfetopito** [comment]
Thanks for looking at this @fairlighteth
I addressed it on https://github.com/cowprotocol/cowswap/pull/2331
