### ISSUE TITLE
Can't switch to GC using network selector

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2278]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1681124650034249

 I can't switch to Gnosis chain in MM using the network selector. This happens both on Barn and Prod
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a7401535-a9ff-4a24-b466-355a46eaed84)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fc7cb999-e260-4de7-bee1-b1e603d35db4)

**Expected**: it should be possible to switch to the GC network.

**Comment by nenadV91** [comment]
Its a [Metamask issue](https://github.com/MetaMask/metamask-extension/issues/18509) and they are aware of it and are working on fixing it. So doesn't require any action for us.

**Comment by elena-zh** [comment]
Closed then.
