### ISSUE TITLE
Different text colors on Price impact and fee warnings

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#228]
Reported here
https://github.com/gnosis/cowswap/issues/1961#issuecomment-985530096

Still, Text color in warnings is different
![image](https://user-images.githubusercontent.com/70885163/144396816-267d5554-6203-4345-9b25-cbb17fbe52f9.png)
![image](https://user-images.githubusercontent.com/70885163/144396867-bbc44b4a-65f0-4d49-bcce-e9fb622a8fca.png)

> Original issue https://github.com/gnosis/cowswap/issues/1963 by @elena-zh

**Comment by elena-zh** [comment]
No longer relevant
