### ISSUE TITLE
'0 COW' is missing on the 'Available COW balance' card

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2282]
1. Open https://swap.cow.fi/#/account page as a not connected user
2. Check the  'Available COW balance' card

**AR**: '0 COW' is missing 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/484b8ef3-d5f5-4b8d-8d63-c3a02ccbcf8b)
**ER**: '0 COW' should be displayed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d607cbf3-0278-4d50-b671-d7e2a0b2b6d2)

**Comment by shoom3301** [comment]
@elena-zh the bug is not reproducing anymore

**Comment by elena-zh** [comment]
Reproducible to a not connected user. 
![image](https://user-images.githubusercontent.com/70885163/234841581-83252754-5f97-46da-b7c2-f2a822380819.png)
