### ISSUE TITLE
[presign] Need help signing?

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#229]
**Description**
![image](https://user-images.githubusercontent.com/2352112/144629676-59965896-089d-45c8-bc3d-8a5d63ecdfba.png)

Current version has a little problem with orders that are created, but they are not in the Wallet pending to be signed.

This can easily happen when we send an order to the Safe, and you reject it.
The order will be already in the API (no way to delete it for now), but the wallet doesn't have it any more

**Proposal**
The porposal is to show a `Need help signing?` link, that would open a help modal.

The help modal could show something like:

**I can’t sign it because it doesn’t show up in my Wallet?**
Is possible the order is created, and in a state of pre-sign, but the transaction is not in the wallet.
You can re-send the order to be signed in your wallet by clicking in the following button:
`[ ✍️ Sign order ]`

**Alternatives**
NA

**Additional context**
https://gnosisinc.slack.com/archives/C025G521XQD/p1638529981016400
OR https://altoros.slack.com/archives/C025G521XQD/p1638529981016400

> Original issue https://github.com/gnosis/cowswap/issues/1965 by @anxolin

**Comment by anxolin** [comment]
It should also have a way to hide/delete the order.

**Comment by elena-zh** [comment]
Hey @anxolin , should we keep this opened?

**Comment by anxolin** [comment]
It's fine open and in the icebox 🥶
