### ISSUE TITLE
[1.33]'Executes at' column is not aligned on a reduced screen (width is in [1390-1500] px)

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2293]
'Executes at' column is not aligned on a reduced screen (width is in [1390-1500] px)
See the image:![Screenshot_2.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d3dc24fa-a24c-44f5-91a8-11e7d827d8fc)

**Expected**: column values should not be shifted

**Comment by fairlighteth** [comment]
Couldn't re-produce after a few tries. Not sure if this is specific to the 'loader'. I tried by forcing the 'loader' to show up, but that didn't shift the columns either.
