### ISSUE TITLE
[1.33] No Unfillable label for a PF order with no allowance

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2294]
1. Place a limit order, wait till it is partially executed
2. Revoke the Sell token allowance
3. Check the 'Executes at' value

**AR**: it shows a loader, then is changed to the dash
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/56b6357e-8f2b-457a-9aae-6110103eca1c)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fbe28dac-1ce9-4154-86a2-8d566eff4696)
**ER:** Unfillable should be displayed

**Comment by alfetopito** [comment]
Is this still reproducible?

**Comment by elena-zh** [comment]
Nope!
