### ISSUE TITLE
Frame wallet: wallet is recognized as  Injected

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#231]
1. Install Frame wallet https://frame.sh/
2. Make sure that all the rest wallets are switched off in your browser (MM/Coinbase or so)
3. Open connection window, then connect the wallet

**AR**: the wallet is recognized as  Injected
![injected frame.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/36a367a0-271e-4c0c-9c96-6dac1dcf7174)
![frame.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/49deb684-315c-4547-8c3e-958ab666fe3a)

**ER**: the wallet is recognized as Frame

> Original issue https://github.com/gnosis/cowswap/issues/1971 by @elena-zh

**Comment by elena-zh** [comment]
Closed in favor of #221
