### ISSUE TITLE
[1.33] Swap: app hangs on the price loading state when no liquidity

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2311]
1. Open Swap page on Barn/Dev
2. Connect to Goerli
3. Select ETH/ZRX token pair, an amount to trade
4. Check the form

**AR**: the app hangs in loading price state (up to 1 minute)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e6a80354-13a2-42b7-88a1-ac335500b07c)
**ER**: No liquidity error should be displayed without delays

**Comment by tukantje** [comment]
https://cowservices.slack.com/archives/C0361CDG8GP/p1681505372513439?thread_ts=1681469126.770059&cid=C0361CDG8GP
