### ISSUE TITLE
[1.34] Show appropriate safe nonce for Cancel transaction

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2316]
Related to #2277

When open the app inside the safe: we show there a block where we show a number of signatures. I think it would be great to hide the block while cancelling, or update the info (nonce, number of signatures/etc.) when we start cancelling an order. WDYT?

https://user-images.githubusercontent.com/70885163/231510014-5b2d096a-bce1-4643-9c92-4760092b9504.png

**To reproduce:**

1. Open the CoW Swap app inside the safe
2. Place a market order
3. Sight and execute all transactions to get the Open order
4. Press on the Cancel button, sign the request

**AR**: there is a previous block is displayed for the order.

**ER**: show a new block with cancelling status: new nonce, new number of received and required signatures.

**Comment by anxolin** [comment]
Agree this doesn't look good

**Comment by elena-zh** [comment]
Hey @tukantje , it appears that the new TX log is not displayed on the Account modal (fixed in #2329 ), so I updated the issue description to another proposal (with the lower priority)

**Comment by anxolin** [comment]
Mm, i will put in the freeze box until we get feedback. Should be an easy fix though.

**Comment by elena-zh** [comment]
Fixed
