### ISSUE TITLE
'Unsupported token' errors in console when switch network

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2322]
1. Place a limit order on Gnosis chain and in Mainnet for the same account
2. Switch between networks (Gnosis chain-Mainnet and back)
3. Check the console

**AR:** tons of 'Unsupported token' errors with 400 code for Native price requests
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/df9adb63-bde7-49e5-82ee-dafd00b8ab23)
**ER**: should not be unsupported token errors

**Comment by anxolin** [comment]
If this don't break the app in any way, i will put on hold
