### ISSUE TITLE
WalletConnect: Provide a network select UI and set chainId

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#233]
**Description**
With WalletConnect the Dapp tells the wallet which network to connect to on establishing the connection. Currently cowswap just always requests chainId 1 which is Ethereum, if you want to connect to xDai Chain/Gnosis Chain it still connects to Ethereum. Multichain wallets like [Minerva Wallet](https://minerva.digital/) depend on this initial chainId to select the correct network. Having a single network as the active network and switch it from the Wallet side is a logic that was established by MetaMask that isn't followed by every Wallet.

**How to Reproduce**
1. Go to Connect Wallet and select WalletConnect.
2. Scan the QR code with Minerva Wallet or AlphaWallet.
3. It connects to Ethereum but you wanted to connect to xDai Chain/Gnosis Chain.

**Expected behavior**
After selecting WalletConnect there should be a selection for which Network to connect to. There are examples for this: Honeyswap DEX, Superfluid, 1inch.

**Other**
There was already a [discussion on discord](https://discord.com/channels/869166959739170836/869170873033166868/878222480702050314).

> Original issue https://github.com/gnosis/cowswap/issues/1973 by @PeterTheOne

**Comment by alfetopito** [comment]
Quite annoying that the history is not copied over...

> In the meantime you already have a Network selection dropdown menu, now you just need to set chainId to the current selected Networks ChainId here https://github.com/Uniswap/interface/blob/main/src/connectors/index.ts#L34-L38 and update it when the user changes it. /cc: @elena-zh @anxolin

Anyway, based on Peter's last comment, it should be fixed when the latest uni-merge is released https://github.com/cowprotocol/cowswap/pull/374

**Comment by elena-zh** [comment]
@alfetopito , I tried to reproduce the issue in #374, and it is still there..
But I might be wrong with my steps. So: 
1. I select GC network in Minerva/1Inch wallet
2. I open Cowswap app (pr374) and select WC
3. I connect Minerva/1Inch wallet in GC to the app

As a result, I see that the wallet is connected to Ethereum mainnet instead of the GC.

**Comment by alfetopito** [comment]
Oook, so not that easy as I thought 😞

**Comment by anxolin** [comment]
Okay, at least we are one step closer

**Comment by asimashfaq** [comment]
The thing WalletConnect setup the RPC url for the default chain ID. Even though the user select different chain while connecting this leads to correct chain ID but wrong RPC URL. to Fix this I had Patch the package 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/8992522/191427150-9cfbc30c-cf5b-48ba-af87-0a4534dd8210.png">
 Add these 3 lines. So this check if user choose different ChainID other than  expected than it initialise the connection with correct RPC url  (without new prompt) and everything work as expected.

**Comment by anxolin** [comment]
Hei, thanks for the suggestion. 

If this is something that needs to be addressed in WalletConnect I suggest, the best approach is to do a PR to them, and share it here. You can provide some "testing steps" to facilitate the review. 

Once we review, we will patch it in our side if this solves the issue. We will remove the patch once your PR is merged to the official Wallet Connect repository. 

What do you think?
