### ISSUE TITLE
The app is not auto-disconnected with a wallet when remove/switch off  it from the browser

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#234]
The issue is related to injected wallets/browser extensions 

1. Connect the app with MM browser extension
2. Remove/switch off the  extension from the browser

**AR**: the app remains to be connected with the wallet until reload it
Video: https://watch.screencastify.com/v/QtrhhDGTk3cu8b9lcA7S
![image](https://user-images.githubusercontent.com/70885163/144854198-813af1cd-2cb8-42db-b82c-5564320562cb.png)

Switched off Frame wallet: 
![frame dicc.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9a47a97f-ca0c-4b8f-9d02-980326803ba3)

**ER**: the app should be auto-disconnected

> Original issue https://github.com/gnosis/cowswap/issues/1974 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
