### ISSUE TITLE
[1.34]Hide boxes for multiple cancellations when connected to a SC wallet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2347]
1. Open CoW Swap
2. Connect to a smart contract wallet (Safe)
3. Place several orders
4. Open Limit orders --> your orders table

**AR**: boxes for the multiple cancellation are displayed
![boxes.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b6779527-836c-49ed-9a46-c3e4991958b2)
**ER**: remove these boxes

**Comment by anxolin** [comment]
Pls, note than once bundling of tx is implemented we might desire this behaviour

**Comment by anxolin** [comment]
Since for now we won't do the most generic version of bundling, my previous comment unfortunately don't apply
