### ISSUE TITLE
[1.35]Enhance approval modals for the ETH-flow (approve max amount)

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2359]
Reported in https://github.com/cowprotocol/cowswap/pull/2352#issuecomment-1516548273 (case2)

we need to adjust modals for the classic ETH flow. WDYT?
![approve eth flow](https://user-images.githubusercontent.com/70885163/233416340-464f0f2c-d642-42b7-88d0-540eafe17245.png)
![wrap and approve](https://user-images.githubusercontent.com/70885163/233416352-7be71dda-17d7-4247-9355-c32164c2d8d2.png)

Approval modal for the case when a user connected to MM looks this way: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/900f1bfb-7e18-46ed-aeab-42a7bd4e9e54)

**Comment by elena-zh** [comment]
Proposal is in https://github.com/cowprotocol/cowswap/issues/2175#issuecomment-1484914296 (case 2)

**Comment by anxolin** [comment]
Makes sense, but not sure how often the "classic mode" is used. 
If someone can give you a super short estimate, we might do, otherwise is better to move to the freeze-box
