### ISSUE TITLE
Endless quoting loop

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/cowswap#2362]
While trying to get quotes for a sometimes unsupported token I triggered a couple of endless loops calling `/quote` over and over again. This made the website entirely unresponsive and didn't event finish loading the UI (the screen stayed blank).

**How to Reproduce**
I was not able to identify specific steps to reliably trigger this behavior. My best guess is that this trying to get a quote for an unsupported token is important.
At the time of testing I just reloaded <https://swap.cow.fi/#/1/swap/yvUSDC/USDC> a bunch of times but by now `yvUSDC` is supported again so it might no longer be possible to use this exact pair to trigger the error.

**Expected behavior**
The UI should finish loading, not do an excessive number of requests to `/quote` and display some sort of error if quoting fails.

**Screenshots**
Didn't take a screenshot.

**Additional context**
macOS 13.3.0
Firefox 112.0
[quote_loop.har.zip](https://github.com/cowprotocol/cowswap/files/11308496/quote_loop.har.zip)

**Comment by elena-zh** [comment]
Fixed in #2324
