### ISSUE TITLE
[Develop] Offchain option to cancel Safe order

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2392]
Reproducible on https://dev.swap.cow.fi/

1. Place a limit/market order being connected to Safe wallet (no matter if is it a WC, embedded app or a mobile app)
2. Press on the Cancel order modal (in the Recent activity OR from the Limit orders page - Your orders table)
3. Check the cancellation modal

**AR**: the app suggests to cancel the order offchain. 
When press on the offchain, the modal becomes blinking
The button for multiple cancellation is displayed on the Limit orders page - Your orders table
![offchain market.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/88e5a7ba-83e1-4def-8581-d2b865ff17a2)![offchain.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d616b44a-fa0b-4697-a176-e5129c26d074)

**ER**: it should not be possible to cancel order offchain when connected to Safe (+ no multiple cancellations)

**Comment by anxolin** [comment]
Ups! This feels important. 

Let's fix it 🙏
