### ISSUE TITLE
Safe: transactions hang in Signing state when replace them in Safe

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2393]
**Advance user mode**

1. Create a Wrap transaction being connected to the Safe
2. Sign it by a required number of owners
3. Take a look into the Safe nonce, and remember it
4. Then Create another onchain  transaction (like approve)
5. Before signing, change the safe nonce in the TX signing modal to the one you remembered in the step 3
 ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/846ba3ae-f2d2-46c6-9044-e91cf277665f)
6. Sign the last transaction by a required number of owners
7. Execute the last transaction
8. Check the Wrap transaction state on the CoW Swap

**AR**: it is pending in Signing state
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/691644ea-cdca-4a7e-8c83-383a89406e1a)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/88921f40-8b58-409d-9fe4-1da70cf01c6c)
**ER**: TX should be Cancelled

**Comment by anxolin** [comment]
Yes, this situation can be detected, is a fair request. 

We should improve this cases for the safe. Also is super annoying when you don't approve the order and its also pending forever. If we find the time this quarter, would be great to improve UX for safe users. This one is a good candidate.

**Comment by anxolin** [comment]
I believe this one was solved by @shoom3301 when he implemented cancelations (based on nonce)

**Comment by elena-zh** [comment]
Yes, fixed in #4062
