### ISSUE TITLE
'Wrap my ETH' section shows empty amounts for ETH token and To is unsupported token/insufficient liquidity for a token pair

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#240]
**To reproduce:**

1. Select ETH as a sell token
2. Fill in max ETH value
3. Select  an unsupported token in the From field
4. Press on the 'Wrap my ETH' button

**AR**: empty ETH amounts are displayed in the modal and in the 'Wrap my ETH' section
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/aba2ed27-00d9-46c7-b49d-092d9ee2f28f)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/081b2178-a79d-4d7a-b3b2-6e6c1f91e85e)

**ER**: Do not show this section when a token is not supported?

> Original issue https://github.com/gnosis/cowswap/issues/1991 by @elena-zh

**Comment by anxolin** [comment]
Probably not relevant after implementing #418

**Comment by anxolin** [comment]
Probably irrelevant after implementing #418

**Comment by elena-zh** [comment]
Another issue that is connected to the case and will be good to take into account: empty amounts are displayed for ETH/WETH when there is insufficient liquidity for a token pair
![image](https://user-images.githubusercontent.com/70885163/168780422-70476435-7e61-4189-9bf4-f20c05b8815e.png)

**Comment by elena-zh** [comment]
The section is removed from the Swap form in #889
