### ISSUE TITLE
Impossible to switch networks in imToken integrated browser

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#241]
ImToken supports different networks, so it should be possible to switch them in its integrated browser

**Steps:** 

1. Open imToken app --> navigate to the integrated browser
2. Open Cowswap app there
3. Open network switcher

**AR**: networks switch is disabled there. Messages say that wallet does not support it. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a8b305b2-4982-45af-b59b-170f93dc4020)

**ER**: it should be possible to switch networks there (like it works for MM integrated browser)

> Original issue https://github.com/gnosis/cowswap/issues/1992 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
