### ISSUE TITLE
[Gnosis safe in xDAI] transaction response takes too long

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#246]
Related to #2004
Reproducible to wrap/unwrap/approve token transactions: 

I receive tx responses with a delay: up to 2-3 min.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3c314151-c9a0-4d73-a880-3b09d431232d)

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d184b820-3070-4800-9769-41781387897c)

**Expected**: decrease delay

> Original issue https://github.com/gnosis/cowswap/issues/2005 by @elena-zh

**Comment by elena-zh** [comment]
Seems to be fixed.
