### ISSUE TITLE
No ETH image on activity modal

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#247]
**Description**

No ETH image on activity modal

**How to Reproduce**
1. Using an EOA, place an order buying ETH on mainnet
2. Check the activity modal
* The ETH image will be the placeholder for non-existing images

**Expected behavior**

ETH should have it's own image

**Screenshots**
![Screen Shot 2021-12-16 at 17 02 36](https://user-images.githubusercontent.com/43217/146409901-10eefe66-7ae8-4f98-9ff1-ff5072fa1292.png)

> Original issue https://github.com/gnosis/cowswap/issues/2006 by @alfetopito

**Comment by alfetopito** [comment]
I've fixed that in the uni-merge https://github.com/cowprotocol/cowswap/pull/374
