### ISSUE TITLE
Improve limit order panel visibility on small screens

### ISSUE THREAD

**Issue by MindyCoW** [cowprotocol/cowswap#2499]
Many users with smaller computer screens in usability tests have been unable to find their placed limit orders due to the way that the orders panel wraps below the swap box. 

It would be ideal to fix this - perhaps by having the orders panel appear beside the swap box with a horizontal scroll.

**Comment by anxolin** [comment]
Making @fairlighteth aware in case there's a low-hanging idea?

**Comment by elena-zh** [comment]
Should be fixed in #3990
