### ISSUE TITLE
Don't wait for the approval

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#25]
**Description**
Don't wait for the approval to allow the user to sign transaction

**Details**
Technically, you can send the offchain transaction before the approval/allowance is done.

In order to allow a quicker flow, it would be good to allow to send orders right after the user sends the approval. 

**Describe alternatives you've considered**
It would be good to consider how is the best flow. We could make some wireframes, but the rough idea is:
- The "Approval button" is only visible if the allowance. 
- Once signed the transaction, the approval shows the spinner, but also the UI enables the trading button. 
- We could consider have a message that would clear inform, that the order is consider inactive while the transaction is not mined. Note that this might impact in the expire time (20 min by default). 
- Ideally, in the pending transactions, we could see how the order is inactive (while the approve is not mined). We could consider even grouping together the transactions.
- Once the approval is mined, the order becomes active. Open question, would we show this already in the success toast message?

**Additional context**
Feedback:
https://twitter.com/austingriffith/status/1387429951935111171?s=20

> Original issue https://github.com/gnosis/cowswap/issues/556 by @anxolin

**Comment by elena-zh** [comment]
@anxolin , can we close this?

**Comment by elena-zh** [comment]
Approval process has been improved a lot. So I'm closing the issue for now. Can be reopened any time (if needed)

**Comment by anxolin** [comment]
Thanks!
