### ISSUE TITLE
Increase right-left margins for header text on the waiting cancellation pop-up

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#250]
1. Switch ON the expert mode
2. Open 'Add a send' field
3. Place a trade to a recipient
4. Cancel the order
5. Verify Waiting for cancellation modal

**AR**: looks like right and left margins are missing for the test in the header
![Screenshot_2.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9b2e6057-5d78-4b1f-8c0a-494abed13da1)

**ER**: add right-left margins

> Original issue https://github.com/gnosis/cowswap/issues/2033 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
