### ISSUE TITLE
Approve USDT flow for Limit orders

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2506]
reported in https://github.com/cowprotocol/cowswap/pull/2503#pullrequestreview-1436303082

  # To Reproduce

1. Go to CoW Swap on Goerli, 
2. Use Anxo's USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
3. Approve or trade to have some left over approvals (for example 5 USDT)
4. Open Limit orders page
5. Enter an amount higher than the approval amount (for example 10 USDT)
6. You should have the two step approval flow
7. This flow should not be shown if it is not necessary (i.e. most other tokens, if you have enough USDT allowance to begin with etc.)

**Actual result:** there is no banner
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a2d54256-8e31-43ac-81f7-3521ed4de953)

**Comment by tukantje** [comment]
Addressed in https://github.com/cowprotocol/cowswap/pull/2520
