### ISSUE TITLE
Duplicating WETH token on Mainnet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2515]
- [ ] **The 3rd case**: from time to time I get 'duplicating WETH token' pop-up in the Ethererum network (until I clear out the local storage)Local storage logs (for Staging env): 
[1 - duplicating token.txt](https://github.com/cowprotocol/cowswap/files/11564481/1.-.duplicating.token.txt)

**Comment by anxolin** [comment]
The 2nd report has been fixed, the first one could be a backend issue according to the thread, but is hard to tell. 

I will leave this open, in case we get more evidence.
