### ISSUE TITLE
[1.38]Budling: Detect connected wallet and change link according to it on warnings

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2517]
Reported in https://github.com/cowprotocol/cowswap/pull/2493#issuecomment-1557254037

> > I have found that bundling works in [Ambire ](https://cowservices.slack.com/archives/C0361CDG8GP/p1684763024139269) wallet as well. So here is my question: should we navigate users to Safe only, or can change the link according to the connected wallet?
> 
> That's super cool!
> Although, if they identify themselves to us as Safe App, it makes it harder for us to tell who they are.
> I'd say this is a different task to identify Ambire wallet

**Comment by anxolin** [comment]
Not a big issue, after all they are the ones reporting their name as "Safe". However, lets leave it open, maybe we can actually make REAL bundling with them, that would be better than just fixing this link

They could implement the RPC custom method for bundling using  Wallet Connect

**Comment by anxolin** [comment]
Leaving this for the future, it could be a nice collaboration with Ambiare if they are up for it:

- They could change the appName, so they don't report themselves as "Safe App"
- They implement bundling of TX RPC custom method
- We add a link to their "Ambire App"
- We add support for Wallet Connect, so they can bundle TX
