### ISSUE TITLE
Failed 'quote' requests may appear for Wrap/Unwrap 

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#252]
**Steps**:

1. Open the app
2. Specify WETH/Dai token pair (as an example), an amount
3. Open the console, navigate to the Network tab
4. Change To token to ETH

**AR:** Failed 'quote' request may appear.
These failed requests can also appear on networks change request/connect a wallet action
![failed.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3a7eef17-11af-45df-b222-468643eb8549)

**ER**: no 'quote' requests for wrap/unwrap 

> Original issue https://github.com/gnosis/cowswap/issues/2038 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
