### ISSUE TITLE
[Ambire Wallet] Order signing with SC wallets uses pre-approvals instead of EIP1271

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#253]
**Description**
It appears that signing orders with SC wallets uses sig mode 4, pre-signing an order (https://docs.cowswap.exchange/smart-contracts/settlement-contract/signature-schemes) instead of sig mode 3 (EIP 1271 signature)

This issue happens with [Ambire Wallet](https://www.ambire.com)

**How to Reproduce**
1. Go to wallet.ambire.com, create an account
2. Connect via WalletConnect in CowSwap using connect -> WalletConnect -> Desktop -> Ambire
3. Try to make a trade on CowSwap
4. Eventually, after the ERC20 approval, you end up with a transaction to 0x9008d19f58aabd9ed0d60971565aa8510560ab41 that emits PreSignature log, rather than a signing request

**Expected behavior**
CowSwap should be using personal_sign to request an EIP1271 signature from the wallet, to avoid extra gas costs

**Screenshots**
![Screenshot 2021-12-25 at 19-15-48 Ethereum Transaction Hash (Txhash) Details Etherscan](https://user-images.githubusercontent.com/1247629/147390159-52255238-88da-4338-8ce2-49f30de8ca5d.png)
![Screenshot 2021-12-25 at 19-06-00 CowSwap Meta DEX aggregator](https://user-images.githubusercontent.com/1247629/147390162-47c9aa26-d14b-4246-bfc8-91e5d297f5f5.png)

(note: wallet addr was deleted via DevTools in the second screenshot for privacy)

**Additional context**
Ambire Wallet is a smrat contract wallet that supports EIP1271 as evident here https://github.com/AmbireTech/wallet/blob/main/contracts/Identity.sol#L152. This has been verified with multiple dApps such as Opensea

> Original issue https://github.com/gnosis/cowswap/issues/2044 by @Ivshti

**Comment by elena-zh** [comment]
Closed in favour of #2049
