### ISSUE TITLE
[1.38] 2-steps USDT approval using Safe (WC) fails

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2532]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1684922158482919

There is another issue with USDT approval using Safe (connected using WC): once the TX is reset, the 2nd TX (approval) fails due to the TX uses the same nonce. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/dbaa62dc-03f7-4ae4-b975-8668d852ec36)

**To reproduce:**
OPen CoW Swap
Connect to the Safe using WC option
Use Anxo's USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
Approve or trade to have some left over approvals (for example 5 USDT)
Enter an amount higher than the approval amount (for example 10 USDT)
Press on the Approve button and run TX

**AR**: the 2nd step will fail

**ER**: the 2nd step will be successfully executed

**Comment by anxolin** [comment]
Is this because we send the 2 transactions one after each other? are we specifying the nonce ourselves @tukantje ? (i thought we weren't)

**Comment by tukantje** [comment]
@anxolin we are not specifying the nonce ourselves, anywhere. So probably because we send them one after the other. Trying to understand as well.
