### ISSUE TITLE
[1.38] Auto-update the form when USDT is partially approved

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2538]
Edge case

To reproduce: 
1. Go to CoW Swap on Goerli,
2. Use USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
3. Make sure it is not appoved (revoke approval)
4. Open Swap orders page
5. Specify a trade with the Sell token = USDT, an amount, f.e., 20
5. Partially approve the  token amount (e.g.5)
6. Wait till the Approval TX is executed
7. Check the Swap form

**AR**: There is no 2-steps approval' warning. It apepars when I refresh the page or navigate to the Limit orders page and back
![Screenshot_9.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e3a7b9f5-8fde-4ba1-8b63-9ee53d2d4dbb)
**ER**: 2-steps approval should appear immideately (if a Sell amount is still less than an approved amount)

**Comment by anxolin** [comment]
This one was leading to reverted TX
