### ISSUE TITLE
[1.38] USDT approval warning on order confirm modals

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2545]
1. Open the Safe app in Goerli, load the CoW Swap app inside the Safe
2. Use USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
3. Open Swap page in regular mode
4. Approve or trade to have some left over approvals (for example 5 USDT)
5. Enter an amount higher than the approval amount (for example 10 USDT)
6. Press on the Approve and Swap button, check the modal
7. Repeat steps 4-6 on the Limit orders

**AR**: confirm swap
![Screenshot_3.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/21b23439-b835-4692-8698-9ef75a8ce923)
**review limit:** ![usdt warning.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/cac70b14-350f-40b3-a278-ef11e356a975)

**ER**: make the logic consistent: whether to show the warning on both modals, or not to show it on both modals.

**Comment by anxolin** [comment]
@tukantje im moving this to the icebox, not sure if you were planning to do it. If so, you can move it out

**Comment by tukantje** [comment]
@anxolin I'll verify tomorrow, might be already fixed.
