### ISSUE TITLE
Safe: duplicating token pop-up does not appear -> impossible to pick a token

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2551]
Similar to #2365

1. On the Mainnet, open Safe app
2. Open CoW Swap inside the Safe
3. Search for 'AURA' token in the token list
4. Select the one that needs to be imported (!!!)

**AR**: no duplicating token warning, the token is not picked
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c65d9c40-d35d-4657-85c6-7a37a2a226db)
![safe.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/55527c2b-b8df-4dd1-98d7-06a7c526b436)
**ER**: there should be a duplicating token warning

**Comment by anxolin** [comment]
What should we do in this case? Do we want to prevent to use two tokens with the same symbol? Wouldn't we need to offer at least a way to rename them or something to have such a restriction?
