### ISSUE TITLE
[1.38] Limit: the app is crashed with USDT/COW, amount is 0.0000000002 on Goerli 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2557]
1. Open Limit orders page
2. Connect to a wallet in Goerly
3. Select USDT/COW token pair
4. Fill in 0.2 into the Sell field
5. Start editing the sell amount: add 0 into the decimal part until you get a crash

![Screenshot_3.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/615c7da1-9904-469f-8e51-4fe0b8aa2ec1)

**Expected**: the app is not crashed

**Comment by anxolin** [comment]
![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/36609ed0-5b1f-4df8-b625-5efa730bf750)

Not reproducible any more. Maybe this is fixed?

**Comment by elena-zh** [comment]
Closing for now
