### ISSUE TITLE
[1.8.0]No ETH/WETH amounts in Wrap my ETH section when amounts < fee

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#258]
1. Select a token pair: Sell token ETH/XDAI, any buy token (except WETH/wxDAI)
2. Fill in ETH amount that will be < fee (0.005 or so)

**AR**: No amounts are displayed in the Wrap my ETH section
![empty amounts.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/80bdeb95-bbcd-4689-8f18-1ce5e0cb116c)
**ER**: do not show this section when fees exceed from an amount

> Original issue https://github.com/gnosis/cowswap/issues/2128 by @elena-zh

**Comment by elena-zh** [comment]
Hopefully will be fixed in new ETH flow

**Comment by elena-zh** [comment]
The section is removed from the swap form in #889
