### ISSUE TITLE
Transaction hash appears again and again when switch to another account/disconnect a wallet

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#259]
It might be an edge case, and a bit complicated issue, but anyways: 
1. Send unwrap transaction under Account 1
2. Try to cancel it using a [custom nonce option](https://metamask.zendesk.com/hc/en-us/articles/360059836452-Cancel-transaction-with-a-custom-nonce)
3. Switch to Account 2, wait for a while

**AR**: at some moment I started to get notification about a failed TxHash. It appears again and again until I connect the Account 1 and close it
Video: https://watch.screencastify.com/v/BWksOQGzz6mm3taRL8mJ
![Screenshot_1.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ca09cf36-2711-402a-b9be-a5a1847d065d)

Failed TxHash https://rinkeby.etherscan.io/tx/0xb02cdbc91fd2f87ae3685b8e0fb7473dd577c3dd00f22f90b036946092acd8d0

**ER**: no warnings should appear for another account

> Original issue https://github.com/gnosis/cowswap/issues/2131 by @elena-zh

**Comment by elena-zh** [comment]
Another way to reproduce it: 
1. Place an onchain transaction (wrap/unwrap/approve)
2. While the Tx is peding, disconnect a wallet
**AR**: hash appears again and again
![image](https://user-images.githubusercontent.com/70885163/188625607-63bd77cc-db3c-4493-9eb7-b4ca6d7f1ab0.png)

**ER**: hash does not appear when a wallet is disconnected.

**Comment by elena-zh** [comment]
I have not faced the issue for a while, so I'm closing it.
