### ISSUE TITLE
Improve UI feedback when selling ETH for buy orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#26]
**Description**
It can be confusing for the user that the amount being used for wrapping is the MAXIMUN SOLD, in the case of buy orders.

See this example, here:

![image](https://user-images.githubusercontent.com/2352112/116564166-05abae00-a905-11eb-8b02-5fb2afaec4fa.png)

**Describe the solution you'd like**
Give a better feedback to the user. Not sure what's the best option, we could do some wireframes and test it out.

> Original issue https://github.com/gnosis/cowswap/issues/569 by @anxolin

**Comment by elena-zh** [comment]
No longer relevant with the new ETH-flow
