### ISSUE TITLE
[Claim] Use blockies for wallet avatars instead of identicon

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#261]
@alfetopito Tuning in here: I'd personally stick to the 'blockies' avatar for all wallets:
- We can't detect the MetaMask setting the users has (e.g. you can enable/disable blockies in settings). So even with MM users there's a potential mismatch.
- All other external block explorers/wallet managers use Blockies (Etherscan, Zerion, Gnosis Safe, Zapper, etc.).

_Originally posted by @biocom in https://github.com/gnosis/cowswap/issues/2161#issuecomment-1014599678_

> Original issue https://github.com/gnosis/cowswap/issues/2197 by @alfetopito

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
