### ISSUE TITLE
[1.10] Mobile: shifted elements on claim investment screens

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#263]
originally reported in https://github.com/gnosis/cowswap/pull/2295#issuecomment-1021329335

1. Investment amount is shifted towards fields' labels, other values:
![inv amount is shifted](https://user-images.githubusercontent.com/70885163/151010437-f96b9351-2b31-4949-8845-8c90067b2b23.jpg)

2. Set allowance to Buy vCOW screen: Max button is shifted:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7862005d-2ee7-4847-a742-8d47ebd2ddf0)

> Original issue https://github.com/gnosis/cowswap/issues/2307 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
