### ISSUE TITLE
Expert mode for Advanced orders

### ISSUE THREAD

**Issue by shoom3301** [cowprotocol/cowswap#2635]
An option in the form settings that enables a "one click" trade, like in Swap:

<img width="386" alt="image" src="https://github.com/cowprotocol/cowswap/assets/7122625/86efbf91-8973-408f-85bc-eba5a1bedb2e">

TODO: https://github.com/cowprotocol/cowswap/blob/426668c9e405628753ead82cb67ce4429be168af/src/modules/twap/containers/ActionButtons/index.tsx#L38

**Comment by anxolin** [comment]
Happy to have it if it's low hanging, but I its not, i would wait for feedback that this is something people want/care

**Comment by elena-zh** [comment]
Closing this as Expert mode is going to be removed
