### ISSUE TITLE
Deploy smart-contracts to all networks

### ISSUE THREAD

**Issue by shoom3301** [cowprotocol/cowswap#2639]
Currently, TWAP is deployed only on Goerli, need to support all networks.

## TODO
 - https://github.com/cowprotocol/cowswap/blob/426668c9e405628753ead82cb67ce4429be168af/src/modules/twap/const.ts#L30

**Comment by anxolin** [comment]
@shoom3301 , @fleupold is deploying this week the latest version of the contracts and verifying them. It will have support for:
- appData
- startTime based on mining time
