### ISSUE TITLE
[1.10] Placeholder in 'Input address' field is truncated in some Mobile devices

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#264]
1. Open Claim page
2. Press on the Change account
3. verify 'Input address' field in mobile resolutions

**AR**: Placeholder in 'Input address' field is truncated in some Mobile devices
In particular, I can see it in Huawei P20
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f8599da3-b7e2-4713-a936-48c121d206ca)

iPhone 12 mini
![image](https://user-images.githubusercontent.com/70885163/151351187-dedfbcb6-8526-466e-b71d-b7a9fcdc27fb.png)

**ER:** Placeholder is fully visible

> Original issue https://github.com/gnosis/cowswap/issues/2324 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
