### ISSUE TITLE
[1.10] Mobile: 'Select amount(s)' is too close to the 3rd step in some mobile devices

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#265]
Related to #2336

Connect to a wallet in a mobile view
Open Claims page, investment claims should be available
Check stepper

**AR**: description of the 2nd step looks to close to the 3rd step description (iPhone 12 mini)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bb3d4d40-c254-4223-9638-ddae0ce7c53f)

**ER:** move 'amount(s)' to another line

> Original issue https://github.com/gnosis/cowswap/issues/2343 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
