### ISSUE TITLE
[1.40] Safe: Allow to wrap all native on Limit orders page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2651]
The feature was implemented for Swap orders in #2610. 
It would be great to have the same MAX button behavior for a native token on the Limit orders page when connected to Safe wallet.

**To reproduce:** 
1. Connect to the Safe wallet (using WC or inside the safe)
2. Open Limit orders page
3. Select ETH or XDAI in the sell field
4. Select WETH or WXDAI in the To field
5. Press on the Max button on the sell field

**AR**: not the whole amount of ETH token is picked
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c0d16cf2-a1ef-4510-8d2d-a3f3b8ddbf21)
**ER**: the whole balance of ETH token is picked
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fd67fbbf-7a4d-4792-b91f-b57e12924c7f)

**Comment by alfetopito** [comment]
This is a bug, it should have it but I missed it

**Comment by elena-zh** [comment]
@alfetopito , @shoom3301 , I'm adding 'TWAP' label to this issue as it also would be great to apply these changes on the Advanced orders page.
