### ISSUE TITLE
[1.10]Remove link from 'available claims' banner when impossible to change networks in a connected wallet

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#266]
Originally reported in https://github.com/gnosis/cowswap/pull/2313#issuecomment-1023049195 (p.3)

It would be nice to remove links from the banner when it is impossible to switch to another network (wallet does not support OR connected using WC): 
![image](https://user-images.githubusercontent.com/70885163/151342839-ea62c9ab-830c-4957-8a15-88dee0303a34.png)

> Original issue https://github.com/gnosis/cowswap/issues/2344 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
