### ISSUE TITLE
[1.42]Different rounding rules in the To and in the Buy amount per part fields

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2664]
Different rounding rules in the To and in the But amount per part fields. See the image: ![different rounding.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9d8732ab-0357-43e7-838e-a8762774cd37)

'To' field: rounds down
'Buy amount per part' field: rounds up

**AR**: rounding rules should be the same.

**Comment by anxolin** [comment]
I agree is weird and we that we should fix
