### ISSUE TITLE
Price is different from the Swap form on Mainnet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2665]
Reported in https://cowservices.slack.com/archives/C053B0162VD/p1686741790182889

1. Open Advanced orders on Develop
2. Select 1WETH to GNO (or any other token pair)
3. Make sure you have 1 part for the order
4. Check the Current Market price
5. Open Swap page
6. Select the same token pair and an amount
7. Check he price

**AR**: the price does not match
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5a17ce16-7134-43bf-961b-8a7a7e099978)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/dd656f8e-0d44-4e07-8f34-14c436404fc8)
**ER**: the price should match

**Comment by shoom3301** [comment]
@alfetopito could you take a look at the issue please?
