### ISSUE TITLE
[1.42]Implement hard errors handling for Advanced orders

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2670]
If something fails from the BE side while an order creation, nothing happens from the UI part. 

in particular, when #2667 issue happens, I see no any warning and can't understand why my order is not created. 
There is only one BE error log in the console. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/53733645-2fe3-4aa4-802b-32a8226b394d)
**Expected**: add pop-ups with a BE errors when something fails from the BE side.

**Comment by anxolin** [comment]
Looks like we have some uncaught errors, `buildTwapOrderParamsStruct`, I would think has to do with the fact that the BUY TOKEN is ETH


I see we handle the case and add `0xeeeee` address, however in the screenshot shows undefined 
![image](https://github.com/cowprotocol/cowswap/assets/2352112/4eef796c-0492-4c63-867a-986ad0dff5ad)

@shoom3301 any idea?

**Comment by anxolin** [comment]
If we don't do error handling, this is important to fix agree
@nenadV91 is this something you can handle?
