### ISSUE TITLE
Incorrect TWAP order part duration

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2673]
1. Open the CoW Swap app inside the Safe in Goerli
2. Navigate to the Advanced orders
3. Select any token pair to Trade
4. Specify a number of parts (I specified 10 per 1 hour)
6. Place an order

**AR**: order duration should be 6 min, but parts had duration of 5 minutes
![5.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/50a2f62d-2841-4999-a7c4-c306a7a809ab) 

Besides, the 1st order's part is created in 1 min or so after an order is signed and executed
![1st part](https://github.com/cowprotocol/cowswap/assets/70885163/0a7c47da-371b-4aa0-8277-13503c86dde8)

**ER**: order duration is correct (6 min)

**Comment by anxolin** [comment]
Isn't this related to rounding? we don't show the seconds when we display creation and expiration time. 

I think it is by contract, that if we say the duration is 6min, it will be 360 seconds from the start. 
The start is the mining time (by default).

@shoom3301 WDYT?

**Comment by shoom3301** [comment]
@anxolin @elena-zh it's because WatchTower doesn't create part orders instantly, it takes some time to catch blockchain events, run some code and post an order to order-book. I don't think we can fix it.

**Comment by anxolin** [comment]
Fine with me, not a big deal

**Comment by anxolin** [comment]
I think we can fix by using, as creation time the time in which the part becomes OPEN, not when it is created. 

This would also improve the times we should be in the orders table, which I also noticed has some weird values for the creation time.

@shoom3301 does it make sense to display just the `Expiration time - duration` if there's no easier way to get it?

**Comment by shoom3301** [comment]
>we can fix by using, as creation time the time in which the part becomes OPEN, not when it is created

@anxolin we actually do that.
For example:
1. 13:25 - a new TWAP order was proposed to Safe
2. 13:40 - a Safe tx was signed and mined
3. 13:42 - WatchTower created the first part of the TWAP order

In this example, the parent TWAP order will have `13:40` as a creation time.
And the first part will have `13:42` as a creation time.

>does it make sense to display just the Expiration time - duration

Yes, this solution will work, but it's not true, in Explorer you will see the real creation time when WatchTower has posted the part in order-book.

**Comment by shoom3301** [comment]
We decided to display "Creating..." instead of time for Scheduled orders when its creation time already in the past
