### ISSUE TITLE
[1.42]Add tooltip: can't edit To field for a TWAP order

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2677]
TWAP orders support Sell orders only. 
Currently, To field is disabled for editing, however, there is no explanation on hover this field
![tooltip.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f417259e-264d-41a7-ab63-ff88225cdcb7)

**To reproduce:** 
1. Open the CoW Swap app inside the Safe in Goerli
2. Navigate to the Advanced orders
3. Select any token pair to Trade
4. Try editing the To field

**AR**: the field is disabled with no tooltip

**ER**:  It would be great to add it like we do on the ETH-flow orders
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b245187b-0fb9-43be-8806-bc83a9ce356f)

**Comment by anxolin** [comment]
@fairlighteth  this is what we discussed, I think we should show it somehow visually. Maybe by making the background white (non-editable fields are white)

why not doing this?
![image](https://github.com/cowprotocol/cowswap/assets/2352112/eb321c12-60a8-463a-8c0b-7926fb8b1ebd)



cc/ @shoom3301
