### ISSUE TITLE
[1.42]Default token pairs, amounts on the Advanced orders are not correct

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2678]
Currently, default token is WETH (WXDAI on GC) in the Sell field, TO field is empty. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5be0656f-1321-489d-9499-90d31c5150fb)

**Expected**:

- [ ] **Tokens**:  WETH/DAI for all networks

- [ ] **Amounts**: 

 - Mainnet: 100 WETH
 - Gnosis chain: 1 WETH
 - Goerli - 1 WETH ? (not sure, there is no info in the Spec)

**Comment by anxolin** [comment]
What we discussed today, I'd be happy if we add this one, but I heard this will bring some issues in, like show errors, do too many queries, etc (if so, we can delay it until we make a good plan for it and define it better)
