### ISSUE TITLE
[1.10] Broken 'vCOW' token icon is displayed when add it to MM using button on the success modal

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#268]
1. Do a successful claim in Gnosis chain/Mainnet
2. Press on the 'Add vCOW to MM' button

**AR**: the token is added with a broken icon
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/11dda1a0-723f-434d-96a1-d391892bf6ad)

**ER**: the icon is not broken

> Original issue https://github.com/gnosis/cowswap/issues/2371 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
