### ISSUE TITLE
[1.42]Possible to set the handler twice

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2682]
Related to #2669

Currently, there is no 'pending' state for the fallback handler when it is setting up (TX is running). 
So it is possible to send this TX twice when the 1st TX is being executes at the moment.

**To reproduce;** 
 1. Open the CoW Swap app inside the Safe in Goerli (where fallback handler is not set up)
2. Navigate to the Advanced orders
3. Select any token pair, amount to trade, order duration
4. Check 'Modify' box
5. Send the TX to the wallet, sign it but not execute
6. Check the form, press on the Place order butto nonce again

**AR**: there is no 'pending' state for the fallbacn handler set up. When place one more order,  TX detail shows arequest to set up the handler once again
![no pending state.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/79f744e3-cd81-4326-91e5-8a2bd02de5d7)![can be sent 2 times.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0ab338df-2b19-4ef3-a04f-bc49d4a9be8f)

**ER**: show pending state for the handler. 
On the 2nd press, remove this request from bundling.

**Comment by shoom3301** [comment]
I don't know ho to handle this case correctly.
Hypothetically, we could block creating new TWAP orders until the first order with `setFallbackHandler` call is executed.
But, do we really need this?

**Comment by anxolin** [comment]
If the next TX is executed with the next NONCE, in principle we can omit this step (likely they will be executed in sequence, so the fallback-handler will be in place)


I say likely, cause any safe user can replace or cancel a pending TX.

In any case, moving to ICEBOX unless this is something we really want to handle
