### ISSUE TITLE
Display Total Time nicer

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2683]
When select a custom option, and select, for example, 64 min, the Total time field shows 0h 64 min. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/12c0d4b6-6e56-421b-8b39-5f5edc59ce3e)

It would be great to show 1h 4 m instead.

**Comment by shoom3301** [comment]
@nenadV91 can you take this please?
