### ISSUE TITLE
[1.10]No claiming screen when run claim transaction -switch to another account - return back

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#269]
This is an edge case that would be nice to consider. 

There is no Claiming/Success/Failed screens when run claim transaction  and: 
 - switch to another account - return back
 - switch to another wallet - return back
 - switch to another network - return back

See the video: https://watch.screencastify.com/v/YVKaEE2RxTth2F46xavQ

It would be nice to show Claiming/Success/Failed screens when user comes back to the account and navigates to the 'Claim' page 

> Original issue https://github.com/gnosis/cowswap/issues/2374 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
