### ISSUE TITLE
[1.41]The app is crashed on the Limit/Advanced orders page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2690]
The app is crashed on the Limit orders page.

Steps that I did: 
1. Connected to a wallet (MM)
2. Opened Swap page on Gnosis chain
3. Selected WXDAI-COW token pair
4. Switched to Limit orders page

**AR**: the app was crashed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/029c9475-aaf5-4862-9de3-b151a9de5d0b)

**ER**: the app is not crashed

**Comment by elena-zh** [comment]
One more possible way to reproduce the issue: 
1. on the Swap page, run several transactions (I did 3-4 wrapping and unwrapping transactions on Goerli)
2. then I switched to the Limit orders page and got the crash
![image](https://github.com/cowprotocol/cowswap/assets/70885163/81bd9b66-76b9-4d03-a4d9-9b96c3338d74)

**Comment by elena-zh** [comment]
The issue might appear on the Swap page: I caught it after placing a ETH order
![place eth order](https://github.com/cowprotocol/cowswap/assets/70885163/2944baf0-456d-4695-acad-1c99d493175e)

**Comment by anxolin** [comment]
Maybe be related https://mmazzarolo.com/blog/2022-06-25-local-storage-status/

**Comment by alfetopito** [comment]
To check what's "wrong" with Elena's localStorage, I loaded it locally and counted the length of each of the keys:

```
> Object.keys(f).sort().map(k=>`${f[k].length}:${k}`)
[
  "39:6e094679d796dcfdc1b9f1fb5922b3a033b31a05",
  "39:6f1f9b98eda9ad5f1ede43203ed8cbc6d90bfc7c",
  "76:AMP_MKTG_b0807acca5",
  "122:AMP_b0807acca5",
  "2:AMP_unsent_b0807acca5",
  "31:UserDeadlineSettings",
  "27:UserSlippageSettings",
  "32:_uetsid",
  "29:_uetsid_exp",
  "32:_uetvid",
  "29:_uetvid_exp",
  "315:advanced-orders-atom:v1",
  "2:appDataUploadQueue",
  "136:azat-an75n",
  "39:ce8807e0b3408f614164b7a35279ff84defb4e0e",
  "118:eth-flow-in-flight-order-ids:v0",
  "187:followPendingTxPopup",
  "19:ga_client_id",
  "36:ld:$anonUserId",
  "88:ld:6436ce902ac2b812f945ebff:$diagnostics",
  "720:ld:6436ce902ac2b812f945ebff:eyJhbm9ueW1vdXMiOnRydWUsImtpbmQiOiJ1c2VyIiwia2V5IjoiMTZlY2E3YTAtMGFj"... 36 more characters,
  "514:ld:6436ce902ac2b812f945ebff:eyJhbm9ueW1vdXMiOnRydWUsImtpbmQiOiJ1c2VyIiwia2V5IjoiNWI0YjI1NTAtZGQz"... 36 more characters,
  "228:limit-orders-atom:v4",
  "130:limit-orders-settings-atom:v2",
  "4:limitOrders_showInfoBanner",
  "4:loglevel",
  "224:redux_localstorage_simple_gas",
  "656153:redux_localstorage_simple_lists",
  "4555261:redux_localstorage_simple_orders",
  "26:redux_localstorage_simple_profile",
  "137:redux_localstorage_simple_swap",
  "14282:redux_localstorage_simple_transactions",
  "10841:redux_localstorage_simple_user",
  "4:showOrdersExplainerBanner",
  "1673:twap-orders-list:v4",
  "131:twap-orders-settings-atom:v1",
  "2:twap-part-orders-list:v1"
]
```

Too many tokens and waaaaay too many orders.

The first step of course if to prevent the crash when local storage is full, but we also need to take care of trimming a bit what we store, mainly those tokens and orders.
