### ISSUE TITLE
[1.10] Mobile: 'Change account' is shifted outside screen's area when copy an address

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#270]
Originally reported in https://github.com/gnosis/cowswap/pull/2317#issuecomment-1023033917

'Copied!' moves 'Change account' button outside of the screen area in real mobile devices (both in Android and iOS)

https://user-images.githubusercontent.com/70885163/151335379-d8173d8a-4b25-493e-a616-18b58b4a7b15.mp4

**Expected**: 'Change account' is displayed within the screen area

> Original issue https://github.com/gnosis/cowswap/issues/2375 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
