### ISSUE TITLE
[1.41]'Small sell amount' warning does not immediately appear

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2701]
1. Open Swap page
2. Specify a token pair and an amount to get "Fess exceed from amount' error
3. Switch to Limit orders page
4. Specify the same amount
5. Switch to the Swap tab and back to Limit orders again

**AR**: price is recalculated. Review limit orders button is enabled. 
It becomes disabled in 30 seconds or so
![small.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/065a3ad0-e5df-4c91-b770-4b05914bbfdb)![small1.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f8d5e86f-ae24-4413-96b1-b4e9696d6759) ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5d63cdb8-a818-40c1-8578-5afb85a7ec28)
**ER**: Review button is disabled

**Comment by anxolin** [comment]
@elena-zh this one happens only if you do these tab changes? If this is the case, i agree we should fix but with low prior as you stated

**Comment by elena-zh** [comment]
@anxolin , I retested it, and it appears no longer reproducible. 
I will close this. If I face this once again, I will reopen it.

**Comment by anxolin** [comment]
Okay, thanks
