### ISSUE TITLE
[1.10] 'Revoking approval' is displayed when approve TX is confirmed

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#271]
This is a very edge case and I was able to reproduce it using Safe wallet

**Steps**: 
1. Connect to the Gnosis safe wallet
2. Try to claim for an account with GNO/USDC investment options
3. Run approve token transaction, sign it in the Safe wallet but all required owners
4. Trace 'approving' message

**AR**: at some point the message is changed to 'Approved', but 'Revoking' starts to be displayed. It is displayed until 'answer' about Tx result comes from the Safe
![revoking.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/aa00b025-99df-4bfc-8d3a-b01207142ff2)
![approve](https://user-images.githubusercontent.com/70885163/152348322-fb804d2e-e1ff-4f1f-9ac1-0b5795107aa3.jpg)

**ER**: no 'revoking' status

> Original issue https://github.com/gnosis/cowswap/issues/2385 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
