### ISSUE TITLE
'Executes at' says that an order if far from execution, but it is executed. 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2713]
1. Place a TWAP order with several parts (I placed 1 GNO per WETH with 5 parts and 10% slippage)
2. Check the 'Executes at' column

**AR**: blue indicator is displayed saying that a price needs go down. However, an order is immediately executed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/44d80d2b-a359-4034-9185-bfd99dadb1ff)

**ER**: include slippage into the price deviation?

**Comment by shoom3301** [comment]
@alfetopito could you take a look at the issue please?
