### ISSUE TITLE
Increase tokens' icons visibility in the dark mode in the Token list

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#272]
It would be nice to use the same solution as in #2386 for displaying token icons in the dark mode in token lists. 

Token lists:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/99a5e22c-2791-400e-a336-95852595a8a9)

Implemented solution for Activity modal: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/84d2fc75-9e98-42b5-86f9-a5271b1237c0)

> Original issue https://github.com/gnosis/cowswap/issues/2387 by @elena-zh

**Comment by elena-zh** [comment]
Fixed
