### ISSUE TITLE
Implement a better error handling for the Claim page

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#273]
Discussed in https://gnosisinc.slack.com/archives/C025G521XQD/p1644238313006379

Currently, an infinite loader is displayed when something goes wrong when loading the Claim page.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0c17cf49-d6b8-4bf5-8bee-d47cc5b201cd)

It would be nice to create a better error-handling for this  case and show an error message something like 'Something went wrong. Please reload the page or try again later' or so. 

> Original issue https://github.com/gnosis/cowswap/issues/2397 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
