### ISSUE TITLE
Fortmatic: the app does not show an error when cancel a transition signing request

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#274]
Originally reported in https://github.com/gnosis/cowswap/pull/2388#issuecomment-1030129467

**Steps:** 
connect to the Fortmatic wallet
Start any sell/buy order transaction
Cancel (close) signing Fortmatic wallet

**AR:** the Cowswap app still shows 'pending' signing modal
https://watch.screencastify.com/v/4oUhXdp7lBovwyTTYTsq

**ER:** the app should show an error message

> Original issue https://github.com/gnosis/cowswap/issues/2413 by @elena-zh

**Comment by elena-zh** [comment]
Closed as the Fortmatic wallet is going to be removed from the app
