### ISSUE TITLE
Claim: Icons on banners have different size in responsive views

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#275]
Icons on banners have different size in responsive views. 
See these images: 
![bigger.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8c59530b-2410-40b9-89bb-114e8884c5e5)
![warning icons.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/23615db4-3cba-423d-8372-44e8ed7c79ce)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b0f64394-086e-4b4a-b0ce-0d73eb2ac7ee)

It would be nice to make icons' size the same for all types of screen resolutions

> Original issue https://github.com/gnosis/cowswap/issues/2415 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
