### ISSUE TITLE
'ETH/XDAI' in the balance  is cropped in a tablet view

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#276]
'ETH' in the balance in the header is cropped in a tablet view with [720-960] px screen width. See the image: 
 ![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/44b13299-5830-48c2-bd84-2841d5c21593)

**Expected**: ETH is not cropped

> Original issue https://github.com/gnosis/cowswap/issues/2429 by @elena-zh

**Comment by elena-zh** [comment]
The issue is also reproducible in the new header/footer implementation (#607)
![image](https://user-images.githubusercontent.com/70885163/173039241-c74e86f6-9160-4236-a21b-9f0fc5afa897.png)

**Comment by elena-zh** [comment]
No longer reproducible
