### ISSUE TITLE
[1.42]'Presigned' pop-up is missing when a TWAP order is signed and executed

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2787]
Reported in https://github.com/cowprotocol/cowswap/pull/2761#issuecomment-1621279668

1. Open CoW Swap app inside the safe
2. Navigate to the Advanced orders tab
3. Place an order
4. Sign and execute it
5. Check the state when the order changes it states to Open

**AR**: there is no 'presigned' poop-up

**ER**: 'presigned pop-up should be present
https://user-images.githubusercontent.com/70885163/251086707-5eb789ce-81cd-42e9-bfd4-546adf173662.png

**Comment by anxolin** [comment]
If i understand well, probably we should fix. We always inform with a toast when we place orders, in this case, we should do it too. Not sure if we should say `pre-signed` (that might be confusing for users), I think `Swap XXX for at least YYY` should be enough

**Comment by anxolin** [comment]
@elena-zh i think i understood wrong, cause the toast is present (see https://github.com/cowprotocol/cowswap/issues/2809), if this PR is about mentioning changing from posted to pre-signed state, i think is not too important. 

Moving to the freeze box unless @shoom3301 estimates this is sth we want to fix

**Comment by elena-zh** [comment]
Agree. I reported this issue due to this pop-up (pre-signed) presents on Limit/Swap pages. 
So in order to be coherent, it would be nice to have it on the Advanced orders as well (one day).
