### ISSUE TITLE
[Wallet] Add Minerva wallet

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#28]
User request to add support to https://minerva.digital/

> Original issue https://github.com/gnosis/cowswap/issues/577 by @alfetopito

**Comment by elena-zh** [comment]
Closing this for now. 
I've retested the connection: onchain transactions work fine. As for orders, the order type is not supported by the wallet itself 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/4d81c3e7-9c65-4368-bec8-3c60336d7042)
