### ISSUE TITLE
[1.42]Place TWAP pop-up: incorrect name and link

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2809]
1. Place a TWAP order
2. Check the link on the confirmation pop-up

**AR**: the link navigates to 404 page
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8d2271c1-2e2d-4bf1-b7b6-b03bc073abf3)
and text says: 'Swap'
**ER**: the link is: options:
 1. hidden
 2. navigates to Safe Tx details

The text should say 'TWAP order'

**Comment by anxolin** [comment]
@shoom3301 should it take you to the SAFE if the order is not created?
