### ISSUE TITLE
Native Eth workflow: Design

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#281]
Research. Simpler Ether Workflow: Bundle wrap or use contract.

* Needs analysis

> Original issue https://github.com/gnosis/cowswap/issues/2439 by @alfetopito

**Comment by anxolin** [comment]
Bringing @elena-zh comment here too: https://github.com/gnosis/cowswap/issues/2439#issuecomment-1042804763

**Comment by W3stside** [comment]
closing
