### ISSUE TITLE
[1.41] Surplus banner is too big on the Account modal

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2825]
Reported in https://github.com/cowprotocol/cowswap/pull/2776#issuecomment-1620358838

The banner takes to much space on the Account modal. Maybe we should reduce its height a bit?
![image](https://github.com/cowprotocol/cowswap/assets/70885163/467307b9-7414-4118-ac20-fb824aadb42f)

**Comment by anxolin** [comment]
Although I agree, i don't think is a big deal in this case. But I leave it up to @fairlighteth to decide

**Comment by anxolin** [comment]
Closing for now
