### ISSUE TITLE
Add a recipient field into an order receipt

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2841]
1. Place a swap/limit order with a different receiver than a connected wallet
2. Open Limit order page
3. Open the order receipt for the placed order

**AR**: there is no info about a receiver
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d8ad72d7-df30-4e42-9f20-5f800329fc83)
**ER**: it would be great to show this field when a receiver differs from the sender

**Comment by anxolin** [comment]
Important, otherwise DAOs can't verify the funds are not getting out of the safe
