### ISSUE TITLE
[1.42]Scheduled part shows warning when an order is just created

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2879]
Might be related to #2619

1. Place a TWAP order with a token that requires an approval
2. Sign and execute the TX
3. Check statuses on the order's parts

**AR**: they show 'Scheduled'+not enough allowance warning
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/348a292a-940f-4980-b4be-0b192c8c3d1d)
**ER**: don't show a warning unless an order is indeed unfillable 

Note from @shoom3301 : it would be nice to refactor  all warnings on the Your orders table.

**Comment by anxolin** [comment]
@shoom3301 why do you think this happens?
