### ISSUE TITLE
[[1.42] Change isuff.balance/allowance warning's text for Scheduled part

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2880]
Reported in https://cowservices.slack.com/archives/C053B0162VD/p1689246989692399

- [ ]  I think we need to rephrase this warning for 'Scheduled' state, as the order is not yet opened

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6383a105-748f-43ae-b1f4-4f80d44048ed)

- [ ] The same is with Not enough balance warning

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/486a8ba7-af7b-4b09-962c-a04b4e299129)

- [ ] Remove 'Created' timing when a part can't be created doe to these limitations
![image](https://github.com/cowprotocol/cowswap/assets/70885163/757f411b-1606-41a6-954c-173d59eb0958)

**Comment by anxolin** [comment]
>  Remove 'Created' timing when a part can't be created doe to these limitations

Maybe more general. When is scheduled, do we want to show the creation time? Maybe users don't care about that, and we should just show the scheduled time

**Comment by alfetopito** [comment]
> > Remove 'Created' timing when a part can't be created doe to these limitations
> 
> Maybe more general. When is scheduled, do we want to show the creation time? Maybe users don't care about that, and we should just show the scheduled time
> 
> All these are nitpics

@anxolin @elena-zh 

About this, I don't think we should remove the creation time.
Otherwise how can the user know by when they need to fix the warning?

And, scheduled time is equal to creation time to me. No?

**Comment by anxolin** [comment]
I don't know, its strange we show the 2 dates and make it a bit confusing. For scheduled orders, i would think people care just for the time when it will become OPEN (i wouldn't care about the actual creation, just the time it became OPEN)

But we don't need to rush any change here if we are not sure about it.

**Comment by alfetopito** [comment]
> I don't know, its strange we show the 2 dates and make it a bit confusing. For scheduled orders, i would think people care just for the time when it will become OPEN (i wouldn't care about the actual creation, just the time it became OPEN)
> 
> But we don't need to rush any change here if we are not sure about it.

Then it sounds like you want to remove the `expiration` time from orders that are not yet created.
That makes sense and it's trivial
