### ISSUE TITLE
Too many tokens unsupported. Any alternatives?

### ISSUE THREAD

**Issue by bpsib** [cowprotocol/cowswap#2889]
I find Cowswap useless because virtually every single token I try is unsupported. Are there any alternatives?

**Comment by elena-zh** [comment]
Hey @bpsib ,thanks for reporting an issue. 
Could you please clarify which tokens in particular can't be traded for you? 
Thank you in advance.

**Comment by bpsib** [comment]
An example is Pepe 2.0 (0xfb66321d7c674995dfcc2cb67a30bc978dc862ad).

**Comment by elena-zh** [comment]
@bpsib , thanks for providing an address. 
In terms of this token, its contract's code on Etherscan shows that there are a lot of weird conditions that makes impossible allow-listing this tokens in terms of protected trading on our platform. 

Any other tokens?

**Comment by elena-zh** [comment]
Closing this. 
Fell free to reopen the task if you have any clarification/questions.
