### ISSUE TITLE
[1.42]Enhance arrows controls in input fields

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2890]
On the Advanced orders page there are arrows in the No of parts/Price protection/Custom duration fields. 
It would be great to enhance UI for these arrows, especially in the dark mode
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2845be08-8da3-4f87-99c4-e3e7ccb3836f)

Besides, I'd keep the percentage closer to the value
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c48e1661-5188-45f9-a3e4-a68f1d16a233)

**Comment by anxolin** [comment]
Agree, i also noticed that, it doesn't look great
