### ISSUE TITLE
[1.42]Price protection's default value is not changed when click on the downward arrow

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2891]
1. Open the Advanced orders page for the 1st time
2. Press on the downward arrow in order to change 'Price protection' default value

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3705b868-63c1-46c7-bf48-657a9d196e96)

**AR**: nothing happens

**ER**: the value should be changed

**Comment by anxolin** [comment]
We can just set `10` as the default value instead of placeholder, should be trivial fix
cc/ @nenadV91
