### ISSUE TITLE
[1.42] Several Moo sounds and notifications when TWAP part is traded

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2892]
Reported in https://github.com/cowprotocol/cowswap/pull/2884#issuecomment-1635803968 (case 3)

1. Place a TWAP order with several parts
2. Wait till 1 part is executed

**AR**: there are several Moo sounds and 'Traded' notifications

**ER**: only 1 sound and 'Traded' notification

**Comment by shoom3301** [comment]
Can't reproduce :(

**Comment by elena-zh** [comment]
Sometimes a pop-up and Moo sound may not appear at all

**Comment by elena-zh** [comment]
Looks like fixed in #2914
