### ISSUE TITLE
[1.42] Save collapse/expand state for a TWAP order

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2893]
1. Place a TWAP order with several parts
2. Once signed and executed, expand the parent order to see its tabs
3. Switch to the History tab and go back

**AR**: the order  is collapsed

**ER**: the order is expanded

**Comment by anxolin** [comment]
nice to have indeed. I moved it to the icebox, but i agree we could persist the state of the expanded orders in a joitai atom to remember this
