### ISSUE TITLE
[1.42]Order receipt for cancelled part of a TWAP order does not have Explorer link

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2894]
1. Place a TWAP order
2. When its part goes to Open, cancel the part
3. Once the part is cancelled, check its order receipt

**AR**: it does not have a link to Explorer
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b900d414-2f97-42ad-8820-cab835f98e0b)
**ER**: it should have the link to Explorer

**Comment by anxolin** [comment]
@shoom3301 is it possible that is because we cancel before its created? If that's the case, I would say is expected and we should close it

**Comment by elena-zh** [comment]
@anxolin , it is the case when the part goes into the Open state. And it exists on Explorer.

**Comment by elena-zh** [comment]
Still relevant
