### ISSUE TITLE
[1.42] Part hangs in Scheduled state once opened/filled

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2906]
1. Place a TWAP order 
2. Wait till the order is signed and executed
3. Check the part's statuses

**AR**: parts don't go to Open or Filled states. They hang in 'Scheduled' state even if traded
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/44852178-102c-488e-b649-89f35e513707)
Parts disappear from Open orders table once expired

**ER**: parts go to Open state once created on Explorer. And show 'Filled' state as soon as they are filled.

**Comment by shoom3301** [comment]
Works only with prod backend
