### ISSUE TITLE
Investigate an issue with price impacts

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#2958]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1690570839813469

I believe we are introducing a bug in DEV that is not in prod yet, it shows too big price impacts
Even in PROD numbers don't match, but they are actually much better
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/55a6a5ff-fcaf-4c4e-91c6-a5b8aa25d668)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/602f7216-bbce-40e4-a781-f52a4c162aa2)

Also, it would be great to investigate and fix this issue: #2762

**Comment by anxolin** [comment]
Price impact is broken!

![image](https://github.com/cowprotocol/cowswap/assets/2352112/3da63ea8-7944-4d06-aadc-11b024c4e6de)
