### ISSUE TITLE
User Protection: Scam tokens

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#299]
Use deployment time of the contracts, and other heuristic? Backend is also a scam detector, it might be nice. Also if the DAO (using a delegator multisig) can easily add tokens to a black list, we can react.

> Original issue https://github.com/gnosis/cowswap/issues/2462 by @alfetopito

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk
