### ISSUE TITLE
[1.44] Remove 'Create one for free!' from Advanced orders page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3010]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1691077557188889
Remove 'Create one for free!' from Advanced orders page, Your orders table:
 - from Open orders
 - from Orders history
Orders are not for free when place them in Safe. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e629b6c1-3cc1-401f-a5fa-79d3b3892630)

**Comment by fairlighteth** [comment]
Addressed in https://github.com/cowprotocol/cowswap/pull/3019
