### ISSUE TITLE
Share trade button

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#302]
Improve sharing capabilities to encourage users to do CoWs or share in social media some trades. It could also make it easier for projects to create a link to buy their token, so they could list us in their webs

> Original issue https://github.com/gnosis/cowswap/issues/2465 by @alfetopito

**Comment by elena-zh** [comment]
Hey @anxolin , seems that we already have  a link that contains tokens and chain info. Can we close this task?
