### ISSUE TITLE
Limit orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#305]
**Description**

Introduce Limit orders on CowSwap

Detailed background https://github.com/gnosis/cowswap/issues/1297

**Additional resources**

Main component will have 2 tabs: swap & limit.
Will need prototyping/design work to define it.

Refactor needed components to re-use as much as possible

**Feature breakdown**
It includes:
- [ ] Refactor: Extract reusable hooks, components [12] https://github.com/gnosis/cowswap/issues/2433
- [ ] Parametrize swap: Add a swapMode = LIMIT/MARKET [2]
- [ ] Settting: Keep the advance to not confirm. All the others gone. For now no more settings. Future, fill or kill/partial [1]
- [ ] Tabs and 2 pages: Swap, Limit [3]
- [ ] Decide on fee behaviour: [5]
    - Option A: Do as we do with swaps. Fee goes on top, and the price doesn't include it
    - Option B: Include fee in the price.
- [ ] Layout with two inputs, price and expiration [5]
- [ ] Handle sell order or buy order logic: do we want to support buy orders? Refactor parts affected [5]
- [ ] Logic and state depending on the type of order. Reuse price/deadline if posible. Set different deadline default [3]
- [ ] Refactor Receiving amount box: depding on type (market/limit), we do two different actions:  [5]
- [ ] Button to add current market price (or display somewhere the current price) [1]
- [ ] Show slippage and optionally % above market price [1]
- [ ] Placing the order [1]
- [ ] Preview: Add deadline, inform type of order, maybe remove fee [4]
- [ ] Fetch orders for activity: 2 API calls. (1) Last 10 orders (2) Open Orders [2]
- [ ] Recent activity: 2 tabs. (1) Active orders (Open orders both market/limit), (2) History [5]
- [ ] Toasts [1]

Good to have:
- [ ] Partially filable https://github.com/gnosis/cowswap/issues/2458

> Original issue https://github.com/gnosis/cowswap/issues/2468 by @alfetopito

**Comment by MindyCoW** [comment]
Is there any initial research that needs to be done before we jump into prototyping?

**Comment by anxolin** [comment]
@shoom3301 can we go over this one, and define all tasks that are required?

**Comment by shoom3301** [comment]
TODO:

- Get token fiat price from quote
- Valid to input
- Order signing and posting (src/cow-react/modules/swap/services/swapFlow/index.ts)
- From validation (like a SwapButtons component)
- Approve

**Comment by anxolin** [comment]
https://docs.google.com/document/d/1P9I4IkfsNXjyhzahhLGequaNKoGik0jP9lTO4TIBNfw/edit#
