### ISSUE TITLE
'Check claimable vCOW' button overlaps Network warning

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#306]
For time to time I'm able to catch a Network Warning pop-up when ws blocknative api fails  due to this error `WebSocket connection to 'wss://api.blocknative.com/v0' failed: WebSocket is closed before the connection is established.`
![image](https://user-images.githubusercontent.com/70885163/154472693-5b1d5f3d-3208-45ec-adcd-f2a14f590731.png)

I think, we need to whether not to show it at all, or adjust it to look better. 
At least, on the Claim page it is overlapped by 'Check claimable vCOW' button
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a76039aa-06b1-4c0b-aaf8-00b9a77036de)

> Original issue https://github.com/gnosis/cowswap/issues/2469 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
