### ISSUE TITLE
Do not show 'available for claims' banner when the app is opened in several tabs

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#307]
The banner is no longer displayed when we switch to the network and get a data that a user has already claimed (Implemented in #2394)
But it would be nice to extend this logic when the app is opened in several browser's tabs:

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1156af7f-9015-482d-b69d-6cf9888add0b)

> Original issue https://github.com/gnosis/cowswap/issues/2470 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
