### ISSUE TITLE
Incorrect amount of claimed tokens is displayed on waiting modal when re-run claim after failed Tx

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#308]
1. Select select claim options, remember the claimed amount
2. Send the TX to the  connected wallet
3. Change Gas limit in the connected wallet to be at less than a half of the required value
4. Wait till the TX fails
5. Go back, change claimed amount/options
6. Send the TX to the connected wallet

**AR**: claimed amount for the 1st attempt is displayed in the 'Waiting' modal'
See the video: https://watch.screencastify.com/v/GFm16UWzH0k2Nltpzpl9

**Note**: the amount is changed after TX is signed

**ER**: no amount before TX signing should be displayed

> Original issue https://github.com/gnosis/cowswap/issues/2472 by @elena-zh

**Comment by elena-zh** [comment]
Closed as Claim page will be hidden based on the #349 task
