### ISSUE TITLE
Gnosis Safe App issue with READ ONLY

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#311]
**Description**

Issue with Gnosis Safe App when you are in read-only safe. It allows you to create orders, when it shouldn't

See:
https://github.com/gnosis/cowswap/pull/2495#issuecomment-1050774896

> Original issue https://github.com/gnosis/cowswap/issues/2499 by @anxolin

**Comment by elena-zh** [comment]
Precondition: 
1. Open the safe in read-only mode:
 - change a network to another one in the connected wallet address (Safe in Rinkeby, MM in Ethereum)
 - Change an account in the MM wallet to the one that is not the Safe owner

Steps: 
1. Open Cowswap app inside the safe in the read-only mode
2. Connect to a MM (or other) wallet
3. Specify a token pair, an amount to sell or buy

**AR**: the button is enabled, 'pending order' appears when press on the button (however, a user can't sign the order)
**See the video:** https://watch.screencastify.com/v/aOHI3MJI8wXyKl479dYU

**ER**: Disable 'Swap' button (or add 'Read Only' message to it)

Use cases: 
1. Keep in mind that user can open the Cowswap app not only   inside the Safe, but conenct to it using WC fro desktop/mobile versions. Also a user can connect the app to the Safe mobile app in iOS
2. I would vote for disabling not only 'Swap' button, but Wrap/Unwrap/Approve tokens buttons. 
Besides, I would disable Convert button/Claim buttons on the Account page. @anxolin , @alfetopito , WDYT?
![image](https://user-images.githubusercontent.com/70885163/182135053-f92f6f19-3b8e-49d0-94ab-09f4b01a20c2.png)
![image](https://user-images.githubusercontent.com/70885163/182135146-370e1e4f-f5a5-4a1c-b853-98519b519195.png)
![image](https://user-images.githubusercontent.com/70885163/182135283-3de1017f-ebef-414e-8730-5215b9e04db2.png)

**Comment by shoom3301** [comment]
Unfortunately, now we can't detect `readonly` status of the user via WalletConnect and in the IOS app
