### ISSUE TITLE
Fortmatic: difficult to call a keyboard on an iOS mobile device

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#314]
Originally reported in https://github.com/gnosis/cowswap/pull/2166#issuecomment-1046969806

I can't call keyboard in order to connect to the wallet when press on the email field in the connection modal

https://user-images.githubusercontent.com/70885163/154977333-1f9ec859-413f-42f2-bd71-2149efbc0690.mp4

The only way to open the keyboard is to long press on the field, then tap it again (takes a lot of time to understand and find out how to manage this).

> Original issue https://github.com/gnosis/cowswap/issues/2516 by @elena-zh

**Comment by elena-zh** [comment]
Closed as the Fortmatic wallet is going to be removed from the app
