### ISSUE TITLE
Permit: Update swap button

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3150]
# Summary

Update swap button to match design when the order will include the permit CoW Hook

![image](https://github.com/cowprotocol/cowswap/assets/43217/14ff0600-cf6c-49d6-b98b-2be872692da0)

When it doesn't, the button should be merged

![image](https://github.com/cowprotocol/cowswap/assets/43217/a3dd4288-c107-45f8-85d7-1b9aa5cb3a40)

# Background

[Figma](https://www.figma.com/file/NdiLgmx8lhtlCB41n73IDJ/2023-Permitable-tokens?type=design&node-id=59-2&mode=design)

**Comment by elena-zh** [comment]
@alfetopito , is this task still relevant?..
