### ISSUE TITLE
Permit: Flag permittable tokens on token selector

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3151]
# Summary

Add flag for known permittable tokens to token selector
![image](https://github.com/cowprotocol/cowswap/assets/43217/fff8257b-6c74-4152-a667-ce64509a9b65)

# Background

[Figma](https://www.figma.com/file/NdiLgmx8lhtlCB41n73IDJ/2023-Permitable-tokens?type=design&node-id=59-2&mode=design)

**Comment by elena-zh** [comment]
Hey @alfetopito , this is should be implemented, correct?

**Comment by alfetopito** [comment]
Yep, it has!
