### ISSUE TITLE
Can't connect to 1Inch wallet in Gnosis chain

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#316]
1. Open 1Inch wallet
2. Switch to Gnosis Chain there
3. Open Cowswap--> Wallet connect
4. Scan the code

**AR**: pop-up in the wallet appears saying that it is not the currently selected network in the dApp
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/14656d92-e73d-4a33-9a05-980bb54ee46a)

**ER**: user should be able to connect to GC 

> Original issue https://github.com/gnosis/cowswap/issues/2524 by @elena-zh

**Comment by elena-zh** [comment]
Closed in favor of #129 , #233
