### ISSUE TITLE
No request to add GC to MM  in integrated browser

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#318]
1. Make sure that GC is not added to the MM wallet
2. Open the app in MM integrated browser
3. Open the network switcher and press on the GC there

**AR**: nothing happens

https://images.zenhubusercontent.com/192335743/0b93f813-fd74-4415-a50e-6b0b08abc779/rpreplay_final1646921793.mp4

**ER**: the app should send a request to add GC to the MM 

> Original issue https://github.com/gnosis/cowswap/issues/2534 by @elena-zh

**Comment by elena-zh** [comment]
Still reproducible in MM integrated browser: user sees this message when tried to connect to GC network when it is no added to MM
![image](https://user-images.githubusercontent.com/70885163/169295445-d4c700d3-dcd9-4b62-9595-3b7154a8dcf6.png)

**Comment by elena-zh** [comment]
Duplicated by #1002
