### ISSUE TITLE
The page is crashing when selecting the token MPS as sell token

### ISSUE THREAD

**Issue by theChim9** [cowprotocol/cowswap#3186]
**Description**
Selecting MPS (Mt Pelerin Shares) as sell token then entering a sell amount makes the page crash, happens both on Gnosis Chain and Ethereum.

**How to Reproduce**
1. Select MPS as sell token
2. Enter an amount 

**Screenshots**

![Capture d'écran 2023-10-09 134511](https://github.com/cowprotocol/cowswap/assets/96598599/7d03200d-caf4-4f60-806e-c9db598cc894)

**Additional context**
The user who initially reported the bug on Discord is telling us that the token in question is indivisible and say it could potentially be the source of the bug ( https://discord.com/channels/869166959739170836/869170873033166868/1160890264756420649 )

**Comment by Sigri44** [comment]
Thank for issue, ping me if needed.

**Comment by elena-zh** [comment]
Fixed
