### ISSUE TITLE
After ETH wrap I see "Insufficient ETH balance"

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#32]
**Describe the bug**
After ETH wrap I see "Insufficient ETH balance".

I would expect to be able to click `Swtich to ETH` after wrapping ETH to continue the Swap

**How to Reproduce**
1. With ETH in your wallet, select ETH as sell and any other token  besides WETH as buy
1. Enter half of your ETH balance in the sell input
1. The wrap section should be displayed. Click on `wrap my ETH`
2. Send the tx and wait for it to be confirmed
3. Once it's confirmed, you will have less than half of your ETH in your balance, and it and `Insufficient ETH balance` is shown

**Screenshots**
- I originally had 0.3 ETH
- I chose to sell 0.15 ETH
- I wrapped ETH using the modal
- After the wrap tx is mined:
![screenshot_2021-05-07_10-33-07](https://user-images.githubusercontent.com/43217/117487201-9c88f380-af1f-11eb-8096-4bc862c4b30f.png)

**Additional context**
I believe somewhere in the state it's too eager to show you there's not enough balance for the order, without taking into account the wrap that was just performed to use WETH instead of ETH.

This happened in Mainnet. I expect this is harder to notice on Rinkeby given tx costs way less ETH

> Original issue https://github.com/gnosis/cowswap/issues/609 by @alfetopito

**Comment by elena-zh** [comment]
Might be fixed after #418 is implemented
