### ISSUE TITLE
New FAQ Layout

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#320]
**Description**
This is NOT related to a problem, but rather in my opinion an enhancement of the UI/UX of the FAQ page. 

Currently we have a long page with a lot of questions, divided by section. Now that we have a token, I just submitted a PR to create a new section, with 4 questions the page gets even longer, and I recall remembering we almost reached the maximum length at some point. 

**Proposal**
I would like to create a simple menu panel that can lead the user to navigate to the section they want answers from. This panel ideally would also allow to search among the 5 different sections so that I can quickly find what im looking for. The panel should not be very elaborate, but rather a more "clean & simple" version to digest all the current FAQ sections. 

In my opinion, ideally we treat each section differently and not just simply point the panel to the section in which those questions are in the long page (like we currently do). 

This would be the panel:
![image](https://user-images.githubusercontent.com/80408352/158165161-ed0962c3-c424-41a6-8f60-0bd0f5fa0664.png)

If the user is to click on general, then its redirect to the page that only shows the general questions: 
![image](https://user-images.githubusercontent.com/80408352/158165305-a0f46d77-4a89-440c-9ef4-385535af4c79.png)

> Original issue https://github.com/gnosis/cowswap/issues/2541 by @avsavsavs

**Comment by elena-zh** [comment]
@anxolin , @fairlighteth , @avsavsavs can we close this? 
We have already implemented a new FAQ format

**Comment by fairlighteth** [comment]
I would say so, yes.

**Comment by avsavsavs** [comment]
yes from my side!

**Comment by elena-zh** [comment]
I'm closing it then. Thanks!
