### ISSUE TITLE
[1.48.0] Bad error handling posting orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#3217]
**Description**
We have two important issues when we place an order:
- Error handling: in some situations, we show an empty dialog
- Bad handling of some known errors in the API. Like `QuoteNotFound`

![image](https://github.com/cowprotocol/cowswap/assets/2352112/e03b2950-b14c-4a00-b1dd-9d908558f4ae)

**How to Reproduce**
1. Sen an order to SWAP in your wallet
2. Wait for 2.5 min
3. Sign it

**Expected behavior**
1) Never have a broken screen. At least inform about the error.

2) Handle the expiration of the quote, and ask the user to accept the new one. Ideally, we would auto-accept if the price is equal or better

**Additional context**
This is the error I got and would be nice to handle better
```json
{
    "errorType": "QuoteNotFound",
    "description": "could not find quote with the specified ID"
}
```

## Additional info
@shoom3301 says this is not from this release, and @alfetopito reported some feedback we think is related to this.

I consider this should be fixed ASAP as its breaking the normal flow of the user: https://cowservices.slack.com/archives/C03S445V822/p1696898447500789

**Comment by alfetopito** [comment]
I got the nice screen both with MM in the browser and another EOA via WCv2

![image](https://github.com/cowprotocol/cowswap/assets/43217/b7db5679-4c54-4976-bc62-e87fbdc0a729)
