### ISSUE TITLE
1Inch: 'Add token to MM' button is displayed on the Confirm order modal in the integrated browser

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#322]
1. Open 1Inch wallet in the mobile app
2. Open the integrated browser there
3. Connect to the Cowswap
4. Place an order
5. Verify the order confirmation modal

**AR**: 'Add token to MM' button is displayed on the Confirm order modal
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7d0ab45d-3781-49e7-b513-1c1f5071d2a8)
**ER**: no such button in the 1Inch integrated browser

> Original issue https://github.com/gnosis/cowswap/issues/2548 by @elena-zh

**Comment by fairlighteth** [comment]
To add to this issue: Might be an opportunity to create a client/wallet agnostic 'Add Token' component. In this case it's the 'Add to MetaMask' component. But perhaps there are more that have different methods exposed to add a token (1INCH, Tally?).

**Comment by elena-zh** [comment]
> To add to this issue: Might be an opportunity to create a client/wallet agnostic 'Add Token' component. In this case it's the 'Add to MetaMask' component. But perhaps there are more that have different methods exposed to add a token (1INCH, Tally?).

More details are here https://github.com/cowprotocol/cowswap/pull/378#issuecomment-1090123830
