### ISSUE TITLE
vCow and xDAI balances appear/disappear when app is opened in Gnosis Chain

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#323]
I noticed, that vCow and xDAI balances appear/disappear when app is opened more than 1 minute without any action. Network - Gnosis Chain. 
Balance is not displayed up to 20 seconds, then appears again.
This happens each 3-5 minutes.
See the video: https://watch.screencastify.com/v/R2kBAClc94DLSgffiYAn

**To reproduce:** 
1. Open the Cowswap app
2. Connect to a wallet in GC
3. Leave the app opened for 3-5 min and trace balances

**Expected**: balances are always displayed. 

> Original issue https://github.com/gnosis/cowswap/issues/2550 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
