### ISSUE TITLE
Permit: Missing modals in expert mode

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3242]
**Description**

Swapping/Placing order modals are no longer displayed in the Expert mode for permittable tokens.

The new modal 'Confirm' appears only when 'Approve' has been signed before, f.e. for the cancelled order.

**Additional context**

Reported [here](https://cowservices.slack.com/archives/C06002PRF37/p1697630078994519)

**Comment by elena-zh** [comment]
Closing this as Expert mode is going to be removed
