### ISSUE TITLE
Permit: show final buy amount in the modal

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3243]
**Description**

Show an amount in the modal that a user signs ('Minimum received (incl. fee)') instead of the 'Receive (incl. fee)' in the modal

![amount on modal](https://github.com/cowprotocol/cowswap/assets/43217/39e2a4ac-651d-476c-9f21-cf3deb44a7e5)

**Context**

From [this thread](https://cowservices.slack.com/archives/C06002PRF37/p1697630881200489)

**Comment by alfetopito** [comment]
Duplicates https://github.com/cowprotocol/cowswap/issues/97

**Comment by elena-zh** [comment]
Closing this as this modal is no longer  used in the app
