### ISSUE TITLE
Make (v)COW balances formatting locale dependable + show full amounts on hover

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#325]
Originally reported in https://github.com/gnosis/cowswap/pull/2564#issuecomment-1075049983

It would be nice to make formatting of these amounts locale dependable
![image](https://user-images.githubusercontent.com/70885163/159469554-e3522749-8974-45b2-b045-16ea897a5621.png)
Also, it would be nice to show full amounts on hover as we do for all amounts across the app
![image](https://user-images.githubusercontent.com/70885163/159469826-11ec8967-13ea-43fc-b222-c147f79ce07e.png)

> Original issue https://github.com/gnosis/cowswap/issues/2571 by @elena-zh

**Comment by elena-zh** [comment]
Already implemented
