### ISSUE TITLE
Cookie policy page not loading on Brave Browser

### ISSUE THREAD

**Issue by fairlighteth** [cowprotocol/cowswap#3256]
**Description**

- Link https://swap.cow.fi/#/cookie-policy doesn't work on Brave browser

<img width="961" alt="Screenshot 2023-10-20 at 12 29 42" src="https://github.com/cowprotocol/cowswap/assets/31534717/e50e19ba-0161-4ada-8f8f-4c5c3dd5a6f8">

<img width="557" alt="Screenshot 2023-10-20 at 12 30 20" src="https://github.com/cowprotocol/cowswap/assets/31534717/74cedae5-c5f9-4f01-a036-86e5a24ae023">

**Comment by elena-zh** [comment]
I can't reproduce the issue :(
