### ISSUE TITLE
Add a COW token info/address to the profile page 

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#326]
It would be nice to add whether a  'Add COW to MM' button, or add token's address into this card in order to add the token  to the wallet quickly after conversion
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/03090d7b-0a1f-4885-985f-3a9447427e64)

> Original issue https://github.com/gnosis/cowswap/issues/2578 by @elena-zh

**Comment by fairlighteth** [comment]
Will be addressed in https://github.com/cowprotocol/cowswap/pull/369 - suggesting to close this issue.
