### ISSUE TITLE
Tooltip's circle is almost invisible in the Convert vCOW section in the light mode

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#329]
Tooltip's circle is almost invisible in the Convert vCOW section in the light mode
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7e964a3f-fbd5-4995-8b8a-3c79f63a53ff)

**Expected**: make it more visible: it looks much better in the dark mode
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6d5a77ae-139e-43b2-8093-0a25d7a0c549)

> Original issue https://github.com/gnosis/cowswap/issues/2610 by @elena-zh

**Comment by elena-zh** [comment]
No longer relevant
