### ISSUE TITLE
[wallet] Crypto.com Defi wallet cant sign eth_signTypedData_v4

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#33]
Using Wallet Connect, not able to sign the swap message.
To be more precise, there's no prompt at all in the wallet app when a signature is requested from the web interface.

I couldn't yet found any reference regarding their app.
There are a few repos available on github, but none that I could link to the mobile wallet, so I assume it's all closed source.

I've reached out to their support through the website (help.crypto.com)
![screenshot_2021-05-07_12-31-38](https://user-images.githubusercontent.com/43217/117499459-1f19af00-af30-11eb-8dcc-46ed16c9beed.png)

It says it takes a day to reply. Let's wait for it :crossed_fingers: 

> Original issue https://github.com/gnosis/cowswap/issues/610 by @alfetopito

**Comment by ericatallah** [comment]
Any progress on this? I'm having the same issue.

**Comment by alfetopito** [comment]
> Any progress on this? I'm having the same issue.

Unfortunately not. 
I never got a reply and we didn't get back to testing this wallet

**Comment by anxolin** [comment]
Maybe we can contact them again @alfetopito , also @ericatallah u could help by reaching to them too. We are happy to integrate as many wallets as possible, but they must implement offchain signing so we can provide the gass-less experience
