### ISSUE TITLE
Include the slippage tolerance in the settings of the user when we submit the order

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#332]
We want to pass the slippage tolerance value as an order parameter to the API's and/or also to the Sentry.

![Screenshot from 2022-03-31 10-43-00.png](https://images.zenhubusercontent.com/61093afdffd52dc74263a8d2/08cf4b60-2eb7-431e-a7aa-bf037749c54e)

> Original issue https://github.com/gnosis/cowswap/issues/2617 by @nenadV91

**Comment by anxolin** [comment]
Bringing back the comment from our sprint session:

Coordinate with backend, the initial Idea:

* [ ] When we get the quote, backend will send an ID that identififies the quote. This id helps them to debug and we should include it in the posting of the order
* [ ]  Include slippage in the post i.e in bips? or '0.5' (to agree with backend)
* [ ]  [good to have] Ideally include this information in the metadata (IPFS)


Depend on https://github.com/cowprotocol/services/issues/131

**Comment by anxolin** [comment]
Adding some document to help with the definition and coordination https://docs.google.com/document/d/1N8K-ueKxxuuFfKjnegbPUYx30Qk1H8zjeiLo3jg-X14/edit#

**Comment by anxolin** [comment]
Nick created a task for the quoteId https://github.com/cowprotocol/services/issues/170

**Comment by alfetopito** [comment]
Implementation details (based on the [gdoc shared above](https://docs.google.com/document/d/1N8K-ueKxxuuFfKjnegbPUYx30Qk1H8zjeiLo3jg-X14/edit#))

CowSwap:
1. New field `quoteId` received as part of the `/quote` api response
2. Propate/store in the internal state 3 new fields (2 might be there already, need to check)
  - sellAmount
  - buyAmount
  - quoteId
3. Before placing an order, create the appData doc
4.
