### ISSUE TITLE
Ledger integration

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#334]
We want to add Ledger as a wallet option to connect with.
https://developers.ledger.com/docs/transport/overview/

This is from 1Inch
![Screenshot from 2022-03-31 11-46-14.png](https://images.zenhubusercontent.com/61093afdffd52dc74263a8d2/08eaa1f4-3f8e-465e-993d-1b0546e11b71)

This is from Paraswap
![Screenshot from 2022-03-31 11-49-44.png](https://images.zenhubusercontent.com/61093afdffd52dc74263a8d2/29412abc-3bd8-4c9c-b787-d2fc8dd1ef47)

> Original issue https://github.com/gnosis/cowswap/issues/2619 by @nenadV91

**Comment by alfetopito** [comment]
I looked at this awhile ago.
The initial integration is pretty straight forward, but that defaults to the first address only in your ledger, and doesn't allow for custom derivation paths.

To fully integrate we need to build/load some UI where users can pick which wallet they want to connect and so on.
