### ISSUE TITLE
Add a 'scroll to top' click event on click a FAQ menu

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#335]
1. Open the FAQ page
2. scroll down to a section
3. press on the FAQ menu

**AR**: page's content is not auto-scrolled to the top
https://watch.screencastify.com/v/eKrqzGrzIaxV0Ti7xxhv

**ER**: scroll page content to the top

> Original issue https://github.com/gnosis/cowswap/issues/2620 by @elena-zh

**Comment by elena-zh** [comment]
Fixed
