### ISSUE TITLE
Wallet Connect: Analytics app used

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#34]
**Description**
Add some dimension to analytics, that shows the wallet name if connected with WalletConnect

* See notes in: https://gnosisinc.slack.com/archives/CSGLUC1BN/p1627378660040800

> Original issue https://github.com/gnosis/cowswap/issues/618 by @anxolin

**Comment by elena-zh** [comment]
Discussed with Nenad: implemented
