### ISSUE TITLE
[v1.50.0] App requires a gasless approval when a token is approved

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3423]
Reported in https://cowservices.slack.com/archives/C06002PRF37/p1700669625624939?thread_ts=1700661106.495829&cid=C06002PRF37

and in https://github.com/cowprotocol/cowswap/pull/3417#issuecomment-1822969627 (case 2)

**Steps**: 
1. Open the app
2. Make sure that you have at least 1 token approved using onchain method, and that is on the gasless approval token list. 
3. Specify a trade with this token
4. Press on the Swap/Limit

**AR**: the app requires to sign a gasless approval for the token
![image](https://github.com/cowprotocol/cowswap/assets/70885163/669b0055-0f3b-4268-a426-361e57c81616)

**ER**: no approval is needed

**Comment by shoom3301** [comment]
Thank you! Fixed in https://github.com/cowprotocol/cowswap/pull/3417

**Comment by elena-zh** [comment]
LGTM!
