### ISSUE TITLE
[v1.50.0] Balances are not updated in 10 sec on Tokens overview page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3424]
Related to #3417 

 It takes a bit more than 10 sec to update balances on the Tokens overview page (up to 35 in my case).
![not updated (10 sec)](https://github.com/cowprotocol/cowswap/assets/70885163/f3ee1aa4-229d-4c8d-b8b7-cb6830eaf6a0)
The same with 'Approve' info: it shows a loader when a token has been approved, then it is changed to 'Approve' instead of the loader, and in about 30 sec it is changed to 'Approve'
![image](https://github.com/cowprotocol/cowswap/assets/70885163/ae1c6e93-e667-4d31-82d7-1bf73563b89f)

**Expected**: balances and a token approval info is updated in up to 10 sec on the Tokens overview page.

**Comment by shoom3301** [comment]
This is not a bug.
We do frequent polling (every 10 sec) only for priority tokens:
1. Trade assets pair (what you have selected in a trade widget (swap/limit/advanced))
2. Assets from pending orders
3. Native tokens
