### ISSUE TITLE
[v1.50.0] 'Approve' button does not disappear in 10 sec on Swap page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3426]
Related to #3417

1. Select a token (not in the list of gasless approval tokens) to trade on **Swap** page
2. Specify a trade
3. Press on the Approve button and execute the TX

**AR**: Approve button is displayed up to 1 minute after the TX is executed

**ER**: Approve button is displayed up to 1o sec 

**Note**: not reproducible on Limit orders page

**Comment by shoom3301** [comment]
Thanks @elena-zh !
Fixed in https://github.com/cowprotocol/cowswap/pull/3417

**Comment by elena-zh** [comment]
LGTM!
