### ISSUE TITLE
[v1.50.0] Safe: Approve and Review Limit/TWAP button is not changed to Review when an order is executed

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3428]
Related to #3417

1. Open the app inside the Safe
2. Open Limit orders/TWAP page
3. Select a not approved token to trade
4. Place an order with a bundled approval transaction
5. Wait till the TX is signed and executed

**AR**: 'Approve and limit order' (or 'Approve and TWAP') button remains to be displayed
![image](https://github.com/cowprotocol/cowswap/assets/70885163/6920eafc-5507-4517-8b42-9677540e5267)

**ER**: buttons should be changed to 'Review Limit order' ('Review TWAP') when a token is approved

**Comment by shoom3301** [comment]
Thank you!
Fixed in https://github.com/cowprotocol/cowswap/pull/3417

**Comment by elena-zh** [comment]
Changes LGTM!
