### ISSUE TITLE
[v1.50.0] Balances remain to be displayed when disconnect a wallet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3429]
1. Connect to a wallet
2. Specify a token pair to trade
3. Disconnect a wallet

**AR**: balances remain to be displayed in the fields. 
The same is on the Tokens overview page
![balances](https://github.com/cowprotocol/cowswap/assets/70885163/344d0acf-c9ec-4853-bb35-97bb4e611ede)
![Screenshot_8](https://github.com/cowprotocol/cowswap/assets/70885163/e6135384-162d-446a-8ab5-af2922936674)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/f35e45ca-a925-49f8-a270-7c6a1b7019da)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c0776031-ee22-4805-8776-2f372fbb0f38)

**ER**: no balances info

**Comment by Lucas6348** [comment]
Hello @elena-zh We opened a ticket for you based on your inquiry, Kindly talk to a [Wallet live support agent](https://desks.support/) on the general chain link for definite answers. Kindly use the ticket ID DR3486

**Comment by Lucas6348** [comment]
Hello @elena-zh We opened a ticket for you based on your inquiry, Kindly talk to a [Wallet connect live support agent](https://sup-desk.com/)
on the general chain link for definite answers.
Kindly use the ticket ID DR3486
