### ISSUE TITLE
'Missing' icon does not look good in Your orders table

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3443]
1. Open Limit orders (TWAP) page in Goerli
2. Place an WETH/WBTC order
3. Check the WBTC icon in the Your orders table

**AR**: see the image 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c79cb602-567b-4446-b7c6-9d0335eec661)

**ER**: the icon should b fully displayed 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/a127a410-288c-4dc0-9cdd-c43cc95327ea)

**Comment by fairlighteth** [comment]
@elena-zh Is this still an issue? This is what I see at the moment:

<img width="1068" alt="Screenshot 2024-01-16 at 11 30 07" src="https://github.com/cowprotocol/cowswap/assets/31534717/498ece5b-6cb1-41fc-9e8d-b928c72c5ef2">
<img width="556" alt="Screenshot 2024-01-16 at 11 29 59" src="https://github.com/cowprotocol/cowswap/assets/31534717/3aeac058-1c4c-40a4-a82a-52c4aa6c5b7d">
<img width="1576" alt="Screenshot 2024-01-16 at 11 29 53" src="https://github.com/cowprotocol/cowswap/assets/31534717/5bd5af37-7e61-4f49-830c-393577e8bb0d">

**Comment by elena-zh** [comment]
No longer reproducible. Thanks!
