### ISSUE TITLE
Swap: Icon on the Caution warning does not look nice

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3444]
1. Open Swap page
2. Specify an order
3. Enter a recipient
4. AND/OR wait till the Confirm swap modal is opened, a price is updated
5. Check the warning icon on the modal

**AR**: see the image
![icon](https://github.com/cowprotocol/cowswap/assets/70885163/1661c70f-e765-4c13-9f8c-01d377fba7b1)

**ER**: the icon should not be too dark and truncated

**Comment by fairlighteth** [comment]
@elena-zh Is this issue still present? This is what I see:

<img width="531" alt="Screenshot 2024-01-16 at 11 32 10" src="https://github.com/cowprotocol/cowswap/assets/31534717/36017f51-ea32-4b08-9ba7-7d107348bece">

**Comment by elena-zh** [comment]
Not an issue anymore! Thanks!

**Comment by elena-zh** [comment]
@fairlighteth , maybe one nitpick that is still left is this square corner
![image](https://github.com/cowprotocol/cowswap/assets/70885163/4915c4b9-4c2d-46a9-b21d-c6fea49b039f)
