### ISSUE TITLE
Terrible price estimation for a 0-decimals token

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3483]
1. Open the Swap page in GC
2. Select WXDAI-MPS token pair, WXDAI amount
3. Check the price impact

**AR**: see the image
<img width="895" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHM2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e045935b921c55160bfd156edfa384953c0ec217/image.png" alt="image.png" />

**ER**: the impact should look nicer (or be absent if it is impossible to calculate it)

**Note**: impact looks good on Limit orders page

**Comment by anxolin** [comment]
I believe is a bad estimation from the API. They handle badly tokens with 0 decimals, at least for small amounts. 

They are looking into this

**Comment by anxolin** [comment]
Confirmed, is Balancer solver estimation issue
