### ISSUE TITLE
Hide claiming page

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#349]
- [x] Make the claiming route to redirect to profile. We might need to remoe some redux state, updaters, and so on.
- [x] Make the COW balance in the top link to point to profile.
- [x] Adapt label, now '(v)COW', also aggregate vCOW+COW (we should have already the hooks ready)

> Original issue https://github.com/gnosis/cowswap/issues/2639 by @anxolin

**Comment by elena-zh** [comment]
I have a proposal: based on the https://github.com/gnosis/cowswap/pull/2599 PR, we are going to show vCOW balance from locked GNO. So it would be nice to include this amount as well into the (v)COW balance at the top of the page.
![image](https://user-images.githubusercontent.com/70885163/161534637-c1ee8c56-1864-40f6-ad4f-365ec02856fa.png)

**Comment by elena-zh** [comment]
It would be nice to remove 'shining/shimmering' effect from the Claim/menu button. So it will fix the issue with button's boarders in  iOS
![image](https://user-images.githubusercontent.com/70885163/161728387-8d305eca-f0be-4943-b379-e1bed1906320.png)
