### ISSUE TITLE
Token list: values does not look good in mobile with gasless approval label

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3498]
1. Open the app in a mobile view
2. Connect to a wallet
3. Make sure you have a permittable token with a balance
4. Open token list

**AR**: see the image
![image](https://github.com/cowprotocol/cowswap/assets/70885163/7b0c949a-608f-41cd-8d1a-2d35dbe05037)

**ER**: shorten the label area?

**Comment by fairlighteth** [comment]
@elena-zh Please review if we can close now with PR #3686

**Comment by elena-zh** [comment]
@fairlighteth , yes, the issue is fixed there. Thank you!
