### ISSUE TITLE
2440/uni merge: remove 'in the dropdown menu' from the Wrong Network message

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#352]
Related to #2536

1. Open the app,
2. Connect to an unsupported network
3. Press on the 'Wrong Network' button

**AR**: Message says: 'Please connect to a supported network **in the dropdown menu** or in your wallet.'
But when  select a network in the dropdown, nothing is changed: no request to change a network is sent to the connected wallet.
![remove.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/15c8ca3d-eee3-4a24-b6b2-cf22988c29d3)

**ER**: it would be nice to remove 'in the dropdown menu' from the Wrong Network message
OR change its text to the currently used: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c4c7e4cd-a00d-4f98-9109-8aca27cfb62a)

> Original issue https://github.com/gnosis/cowswap/issues/2645 by @elena-zh

**Comment by elena-zh** [comment]
Actually, not fixed in #406 : notes are here https://github.com/cowprotocol/cowswap/pull/406#issuecomment-1098807170 (p.1)

**Comment by anxolin** [comment]
@elena-zh, For me this  this issue is mostly an issue with not working when you click in the dropdown, right? 
We should be able to change networks using that, even if the connected wallet is in the wrong network.

**Comment by W3stside** [comment]
> @elena-zh, For me this this issue is mostly an issue with not working when you click in the dropdown, right? We should be able to change networks using that, even if the connected wallet is in the wrong network.

@anxolin 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/21335563/165275472-8de02945-e3fd-45dc-829b-b35caa1024e0.png">

**Comment by anxolin** [comment]
@W3stside fine with me. I just checked and now it works exactly like Uniswap, so it lets you be in the wrong network and then you can select any other network, and the app changes. I think we can leave it like this
