### ISSUE TITLE
Move the 'Wrong network' modal to the top

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#353]
Currently, the 'Wrong network' modal is displayed in the center of the screen, and it looks a bit weird. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/4ece8b09-7eae-4c43-85cf-47eedd0aedd0)

It would be great to lift it up

> Original issue https://github.com/gnosis/cowswap/issues/2646 by @elena-zh

**Comment by elena-zh** [comment]
No longer relevant in 1.21.0
