### ISSUE TITLE
Cancelled TWAP order is displayed on Open orders

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3530]
1. Place TWAP order
2. Cancel the 1st part
3. Then cancel the parent order

**AR**: the TWAP order remains to be displayed on Open orders
![Screenshot_1](https://github.com/cowprotocol/cowswap/assets/70885163/218dcb66-43e5-4e22-b5ed-dcc39dd03bab)

**ER**: the order with 'cancelled' status should be moved to the History tab

**Comment by alfetopito** [comment]
I can still reproduce it

**Comment by elena-zh** [comment]
Yes, not fixed.
