### ISSUE TITLE
TWAP orders are displayed in Limit orders history

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3549]
1. Open https://app.safe.global/apps/open?safe=gno:0x42cEDde51198D1773590311E2A340DC06B24cB37&appUrl=https%3A%2F%2Fswap.cow.fi
2. Check TWAP and Limit orders history tabs in the Your orders page

**AR**: no TWAP orders history --> orders are displayed in the Limit orders history
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c6e49210-a47d-416f-a375-be8ddcd541c3)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/8c235353-619e-44f8-8f76-1fbb154e5249)

**ER**: separate Limit orders and TWAP orders

**Comment by alfetopito** [comment]
FYI, I cannot reproduce it locally or on dev.
But on prod I can.

That's because TWAP orders are always on backend's prod.

My initial guess:
1. We fail to find TWAP parent orders based on the (limited) Safe history
2. Orders are loaded as usual, since there's no parent order to group them with
