### ISSUE TITLE
Recipient field is misaligned in the Account modal

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3560]
Place a Swap order with a different recipient
Open Account modal and see the order details

**AR**: Recipient field is misaligned
![image](https://github.com/cowprotocol/cowswap/assets/70885163/ff1cfb76-f57b-477b-920b-3e7f0d6dbc6e)

**ER**: the field is properly aligned (the same intends, same alignment, same font)

**Comment by fairlighteth** [comment]
@elena-zh Is this still actual? Because I've been testing with a different recipient address on Goerli and Gnosis Chain, but don't see the warning banner:
<img width="916" alt="Screenshot 2024-01-15 at 17 49 27" src="https://github.com/cowprotocol/cowswap/assets/31534717/24c08283-e2c5-4154-8e65-f9ea6365d616">

**Comment by elena-zh** [comment]
Hey @fairlighteth , I don't see that you are sending sell order to another recipient on your screenshot.
Please, add a recipient here 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/1a10874f-4bc6-4e05-8f9f-fb728a6386df)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/55606515-a36d-4cb2-b1d0-7ddda36f47af)

**Comment by fairlighteth** [comment]
Seems like I had sent the wrong screenshot. Correct one:
<img width="911" alt="Screenshot 2024-01-15 at 17 49 09" src="https://github.com/cowprotocol/cowswap/assets/31534717/65872127-400e-4c9e-ba94-28f237483c04">

**Comment by fairlighteth** [comment]
<img width="914" alt="Screenshot 2024-01-16 at 10 36 35" src="https://github.com/cowprotocol/cowswap/assets/31534717/71826d86-4fd4-4d64-bb7e-735ac0ee5af5">

Now on Goerli was able to re-produce

**Comment by elena-zh** [comment]
When filled, it looks nice. When is open/creating/etc. - I see this issue. 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/7478d521-92c2-4bb2-9e3d-940acda5651b)
