### ISSUE TITLE
No 'Price out of market' message

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3561]
1. Place to the same market orders with high price impact (>5%). I placed witg WETH/Poly or GNO/POLY token pairs on Gorly
2. Wait till the 1st order is filled
3. Check the progress bar message on the 2nd order

**AR**: it says that 'it takes longer than usual to execute' 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/fc060e10-5e39-451c-9340-c86b9f85bdd5)

**ER**:  this is due to Price OOM issue, and the message should be displayed on the bar
![image](https://github.com/cowprotocol/cowswap/assets/70885163/5e571079-4df6-45a6-b16d-d28cc7ba5ff4)

**Comment by alfetopito** [comment]
Looks like this came from https://github.com/cowprotocol/cowswap/commit/69e03514042a890c1656b4d4de3a5e3d6a172fcc#diff-9482db61e36308191813df797a23be4c81768bc9f68f97a4523bd2241cadd22dR93

In the context of refactoring for TWAP.

Seems like by a mistake:

![image](https://github.com/cowprotocol/cowswap/assets/43217/fffd8b02-0df8-4443-9e4e-748410fad8ff)

Unfillable orders updater should remain for SWAP.
