### ISSUE TITLE
Twitter icon is too big on Surlus modal/share fortune screen

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3667]
Related to #3663 
See images: 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/4abe0a81-0050-4f9c-928a-65f9e180d8a4)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/26e5c981-2122-4f37-b38a-3234638e259f)

**Expected**; a smaller icon

**Comment by fairlighteth** [comment]
This should be fixed now?

**Comment by elena-zh** [comment]
@fairlighteth , yes, looks great now, thank you!
