### ISSUE TITLE
Inquiry Regarding the Removal of Ledger Connector in CowSwap Wallet Connection Module

### ISSUE THREAD

**Issue by danielstone25** [cowprotocol/cowswap#3682]
Hello team,

I hope this message finds you well. As a web3 developer with a keen interest in the CowSwap project, I recently came across the wallet connection module and was particularly impressed with its functionality. However, I noticed that the Ledger connector, which was previously available, had been removed.

I would like to kindly inquire about the rationale behind this decision. Understanding the thought process behind the removal of the Ledger connector would greatly assist me in comprehending the project's development direction and inform my own work.

I appreciate the hard work and dedication put into the CowSwap project and would be grateful for any insights you can provide on this matter.

Thank you for your time and consideration.

Best regards,
Daniel.

**Comment by alfetopito** [comment]
Hello Daniel, thank you for your interest.

It has been removed in light of this https://www.ledger.com/blog/security-incident-report.

Let us know if there is any extra info you'd like.

**Comment by danielstone25** [comment]
Thanks for your reply.
So what do you think  if you revert the removal and replace ledger/connect-kit-loader with ledger/connect-kit (according to https://github.com/LedgerHQ/connect-kit/tree/main/packages/connect-kit-loader#-important-notice-) then it might work again?

**Comment by alfetopito** [comment]
We are not interested in adding the direct ledger connection back at this point.
We might reconsider if there's user demand, but that's not the case so far.
