### ISSUE TITLE
TWAP page is too wide when place an order with >30 parts

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3683]
Reported in https://cowservises.slack.com/archives/C0361CDG8GP/p1705598065623679

Such order can be found in https://app.safe.global/apps/open?safe=gor:0xe9B79591E270B3bCd0CC7e84f7B7De74BA3D0E2F&appUrl=https%3A%2F%2Fswap.cow.fi
See the image: 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/4e872f5e-db96-4a3a-82be-a6113411f757)

Internal pagination is not collapsed and causes this issue. 

**Expected**: TWAP area is not changed.

**Comment by anxolin** [comment]
Thanks! it looks terrible.

We will limit the pages we show at a given time. Thanks @elena-zh
