### ISSUE TITLE
Fills tab pagination on mobile

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3703]
**Description**

There's no fills tab pagination in the responsive mode

Example: https://explorer.cow.fi/orders/0xc0688a39e9ce5ee01c49786867357811c3fcf86e27eefb072e80c9417d731bf3a53a13a80d72a855481de5211e7654fabdfe352664fd9408/?tab=fills

Pagination does show up on desktop:
![image](https://github.com/cowprotocol/explorer/assets/43217/7cd00bbe-36ae-47be-a7fe-a595f3a67bdf)

On smaller screens, only the first page of results is displayed:
![image](https://github.com/cowprotocol/explorer/assets/43217/fa87f39b-8427-4f29-8bcc-feb8db3f6ced)

**Comment by elena-zh** [comment]
Fixed
