### ISSUE TITLE
Load images not in CoW Swap's token list

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3708]
**Description**

Part of [Improve token lists](https://www.notion.so/cownation/FE-Improve-Token-Lists-88cca26bf32f477eb79eaec34a201d87)

Strategy for finding images for tokens not in the CoW Swap’s token list

**Proposal**

See the definition on [Notion](https://www.notion.so/cownation/10-Strategy-for-finding-images-for-tokens-not-the-in-CoW-Swap-s-token-list-0dafb2fbd1ba4893a76dea4e9b5ce711)

**Comment by elena-zh** [comment]
Partially addressed: https://cowservices.slack.com/archives/C04DV3TL1MH/p1727782174373479?thread_ts=1727332936.250749&cid=C04DV3TL1MH
