### ISSUE TITLE
Show Execution price on a TX details

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3718]
It would be great to show Execution price instead of a Limit price on a TX details page: as an order is already executed:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/8ce7b929-9996-42e0-b897-5f3241c121ff)

**Comment by alfetopito** [comment]
We have that already. [Example](https://explorer.cow.fi/orders/0xce1a4852571dd6e28e9b0f6ce2d9e461cefee7b0a619388b3384bd3d6f2dd1ff40a50cf069e992aa4536211b23f286ef88752187ffffffff?tab=overview)

<img width="604" alt="image" src="https://github.com/cowprotocol/cowswap/assets/43217/dd30ba6f-acd6-4d96-8b2c-c44ebeba8a00">

**Comment by elena-zh** [comment]
Indeed!
