### ISSUE TITLE
[solver-competition] Explorer: Show solver competition page

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#3720]
As a user of the explorer, 
I want to see the current state on the solving competition,
So I:
- Can understand better how the solvers compete to find the best solutions
- Can I can see if the solution has been already proposed, and if the transaction is being mined
- Can see the latest batches

I might be interested in showing some general stats on surplus

TBD: 
- Mockups
- How can we explain the objective function, so is, well... objective? 
- Can we link this to the rules of the game? 
- Should we have a banner advertising on how to become a solver?

## Additional details
Related to backend API proposal https://github.com/cowprotocol/services/issues/187

**Comment by elena-zh** [comment]
Closing for now: can be reopened when re-prioritized.
