### ISSUE TITLE
Load recipient address from url when not connected

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3757]
**Description**

When loading the url with the parameter `?recipient=0x...`, the recipient address is not set when there's no connected wallet.
Additionally, the network from the wallet takes precedence if you are already connected to a wallet different from that of the URL.

**How to Reproduce**

1. Without being connect/private browser window, open https://swap.cow.fi/#/100/swap/_/EURe?recipient=0x01
2. The recipient address will not be populated/set in the form

**Expected behavior**

The form with a custom recipient should be set, and the network should be changed.
The behaviour should be the same being connected or not.

**Additional context**

Reported in [this internal thread](https://cowservices.slack.com/archives/C036MD8ADMG/p1706783043710229)

**Comment by anxolin** [comment]
The part of the network we discussed a bit. I think we need to not automatically change the network of the Dapp to the one of the wallet when the user connects. We should handle the situation where they don't match, and make it easier to:
- Change the Dapp to have the one of the wallet
- Change the Wallet to have the one of the Dapp
