### ISSUE TITLE
[solver-competition] Explorer: Show solver competition status in order details

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#3778]
As a user,
I want to see the solver competition status in the order details page,
So I can:
- Understand if the solution was already proposed or nor
- If the tx has been sent but is not mined yet
- Know if there weren't any proposed solutions, and this is why my order expired

## Additional details
Related to backend API proposal https://github.com/cowprotocol/services/issues/187

**Comment by elena-zh** [comment]
Closing for now: can be reopened when re-prioritized.
