### ISSUE TITLE
[Widget] Documentation

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#3794]
Tasks:
- [x] Document theme, it is outdated: https://docs.cow.fi/cow-protocol/tutorials/widget
- [x] Document `partnerFee` in the widget
- [x] Document `partnerFee` in https://docs.cow.fi/governance/fees
- [x] Good to have, but not a must. Would be nice to provide in https://docs.cow.fi/governance/fees  or somewhere else some additional information on how to add the `partnerFee` without the widget

Also add the documentation for the new features:
- [x]  ~#3791~ Will be done when adding sounds
- [x]  #3789
- [x]  #3790

Also:
- [x] Adapt the link npmjs [link](https://www.npmjs.com/package/@cowprotocol/widget-lib) previously shared where it says live example, the [link](https://github.com/cowprotocol/cowswap/apps/widget-configurator/src/main.tsx) is now

**Comment by shoom3301** [comment]
https://github.com/cowprotocol/docs/pull/337
https://github.com/cowprotocol/docs/pull/338
https://github.com/cowprotocol/docs/pull/339
