### ISSUE TITLE
[1.60] Add Recipient field into the Confirm Swap modal

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3833]
Related to #3756

1. Open Swap page
2. Enable toggle with Custom recipient
3. Specify an order to a custom recipient that differs from an owner address
4. Open an order confirmation modal

**AR**: there is no Recipient field

**ER**: the Recipient field should be present (like on Limit/TWAP modals)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/ace2a467-c078-40d4-8fc0-257ede545a18)

----------------
Also, it would be great to remove this message from the modals (@fairlighteth , WDYT? )
![image](https://github.com/cowprotocol/cowswap/assets/70885163/2468f408-e64c-455d-b215-316cf508aad7)

**Comment by fairlighteth** [comment]
@elena-zh Agree with point 2.
