### ISSUE TITLE
[1.60] The app becomes irresponsible after disconnecting a WC wallet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3859]
1. Open the app https://swap-dev-git-release-20240214-cowswap.vercel.app/
2. Connect to a wallet using WC (I connected to Seploia)
3. Disconnect the wallet

**AR**: the app becomes irresponsible: connect button does not appear at the top (up to 2-3 mins). Connect to a wallet button on the form is not working
![irr](https://github.com/cowprotocol/cowswap/assets/70885163/48486bb8-81bd-479f-b64c-55fc11e3dd1b)
![irr1](https://github.com/cowprotocol/cowswap/assets/70885163/43a852e7-9d92-4fd3-9d4d-6e9ae12472c4)

**ER**: the app works as intended

**Comment by shoom3301** [comment]
The issue was with wrong RPC node endpoint, I've set nodereal endpoints, should be good now
