### ISSUE TITLE
Informing User about Transaction Speed

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#39]
Many users complain about long time period it takes for a transaction to be executed. 

This issue asks to create a proposal how the UX around this topic can be improved for the user. 

For example:

Once a transaction has not been executed for 60 seconds, a notification appears "The network currently experiences high congestion, don't worry, we are speeding up the transaction for you"

Or:
A button "Speed up the transaction", when clicked, it says "Don't worry, we already take care of it"

> Original issue https://github.com/gnosis/cowswap/issues/677 by @annamsgeorge

**Comment by elena-zh** [comment]
Seems that it was implemented in Progress bar changes. 
@anxolin , can we close this task?
