### ISSUE TITLE
[CoW Swap] Cancelling status not shown

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3917]
# Summary

Cancelling status/notification is not shown unless the order was placed on that device.

# To reproduce

1. Place a LIMIT order (might apply to SWAP, didn't check)
2. In a different browser/device, cancel the order

Actual:
- Order is cancelled right away
- No pop up is shown

And when I go back to original device, I see the cancellation notifications when re-opening the app

![Image](https://github.com/cowprotocol/cowswap/assets/43217/fb6afc30-136d-4d80-95b6-1b994c988228)

Expected:
- The order goes into `cancelling` status and remains in the open orders table
- After one minute, it move to history table
- Pop up notification is displayed

# Version

Present on prod and latest develop

**Comment by elena-zh** [comment]
hey @alfetopito , I can see 'Cancelling' status for a swap and limit order (when I initiate cancelling in another device) 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/cafea7e7-9d50-4394-87d8-666402adea6d)

The only one issue I see is there are several moo sounds (2 or 3) when an order is cancelled

**Comment by elena-zh** [comment]
Hey @alfetopito , is this still reproducible to you? :)
