### ISSUE TITLE
[1.62] Enhance Fees displaying in a mobile view

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3953]
1. Reported in https://github.com/cowprotocol/cowswap/pull/3964#issuecomment-1976252466
It would be great to enhance values displaying in a mobile view (not to move the price to another line)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/0f71d5bd-acee-4800-9441-21d0d5fe7b6b)

2. Reported in https://github.com/cowprotocol/cowswap/pull/4005#pullrequestreview-1918104143(case 8): values seem to be misaligned
![image](https://github.com/cowprotocol/cowswap/assets/70885163/5c1546b9-2e45-4ea3-a2b1-781622310b2c)

**Comment by anxolin** [comment]
@alfetopito if this still happens. Could you have a look to this one?

**Comment by elena-zh** [comment]
This is still hapenning :(
