### ISSUE TITLE
Scroll to top when press on the Recreate button in a mobile view

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3955]
Reported in https://github.com/cowprotocol/cowswap/pull/3930#issuecomment-1970793960

1. Open Limit orders in a mobile view
2. Connect to a wallet
3. Navigate to the History tab
4. Open an order receipt
5. Press on the Recreate button from there

**AR**: recreate orders modal is opened, but a user stays at the bottom of the screen

**ER**: scroll to top

**Comment by anxolin** [comment]
This issue is marked as "current sprint" is this right? @fairlighteth
