### ISSUE TITLE
Permit: approve message on the modal is not center-aligned

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3970]
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1709561736250119

Permit: approve message on the modal is not center-aligned. See the image: 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/a03a0299-1166-4a51-8ea7-d2e57735c1e4)

**Expected**: the message should be center-aligned

**Comment by anxolin** [comment]
@fairlighteth not urgent at all. Just assigning to you so you decide what to do with it
