### ISSUE TITLE
Icon on 'Price OOM' message is pale in dark mode

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#3981]
**To reproduce:** 
1. In sepolia, place 2 the same swap orders (one after another) with proce impact >5%
2. Wait till the 1st order is filled
3. Open the account modal and check the 2nd order status (in the dark mode)

**AR**: Icon on the 'Price OOM' message is almost invisible in the dark mode
![too dark](https://github.com/cowprotocol/cowswap/assets/70885163/e82b7b6a-a853-42d2-afe2-7a4302636b96)

**ER**: it is a bit brighter

**Comment by anxolin** [comment]
Not worth it since we are revamping the whole progress bar
