### ISSUE TITLE
[1.62] Update labels/tooltips on Explorer

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4011]
As labels naming has been changed in #4005 in CoW Swap, it would be great to update labels and tooltips on Explorer as well
![image](https://github.com/cowprotocol/cowswap/assets/70885163/00909bdc-39fa-41d2-a561-e423dd7cf350)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/aac76f70-4c95-4daf-87cd-1ee19e8f6f75)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/df62174c-7f36-451f-85a2-c89c0fe3b4e5)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/97d5152e-8861-417b-9c92-473af2b68cfd)

**Comment by MindyCoW** [comment]
Orders placed through the widget will also show up in the Explorer, no? And some will have partner fees applied. So these tooltips will change depending on which ones include the partner fee in the calculation and which ones do not. For example, will the Fees line include partner fee in the calculation? @anxolin

**Comment by anxolin** [comment]
@MindyCoW the explorer don't make any differences from the source of the orders, at least for now. 

I would think this issues is suggesting to rebrand in explorer the fee to network costs, which I'm not sure is a good idea. 

> So these tooltips will change depending on which ones include the partner fee in the calculation and which ones do not

Solvers take a fee and they don't give you a breakdown, at least for now, on the different concepts. What would be exactly your proposal @MindyCoW . I'm not sure we should change the explorer

**Comment by elena-zh** [comment]
Closed as new changes are introduced in #4680
