### ISSUE TITLE
Error loading price issue when time is incorrect on a device

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4030]
Reported in https://cowservices.slack.com/archives/C03NXGFJA2U/p1710175871205829
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1710232016500759

**To reproduce:** 
1. change time on your device (I set +3 hours)
2. Open CoW Swap and try placing a trade

**AR**: impossible: error loading price error is displayed

**ER**: the quote should not rely on the local PC time.

**Comment by anxolin** [comment]
Moving it to current sprint as it can affects the normal flow and prevent someone from placing orders

**Comment by shoom3301** [comment]
This happens because we get an error from the API:

```
description: "validTo is too far into the future",
errorType: "ExcessiveValidTo"
```

Which is reasonable, because the user local time doesn't match the real time
