### ISSUE TITLE
Remove link to Etherscan from native token

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4035]
1. Open Account page
2. Search for a native token there
3. Press on the Etherscan link for this token

**AR**: it navigates to a not existing page
![remove](https://github.com/cowprotocol/cowswap/assets/70885163/e77370b5-d71f-4b12-a6be-922e3784db1e)

**ER**: remove the link

**Comment by anxolin** [comment]
I guess is super easy to fix, so @alfetopito should we do it?
