### ISSUE TITLE
Show ENS name by default in a referral link

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#404]
Originally reported in https://github.com/cowprotocol/cowswap/pull/367#issuecomment-1095119729 (case 2)

Once connected to an account with ENS name, it would be nice to show the an affiliate link with ENS name by default instead of the address, as the account info shows ENS name
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1b886e4b-d3b7-40c1-8265-1ae63290efc6)

**Comment by alfetopito** [comment]
I think this is nice, unless there are multiple ENS names for the same address. Can't decide which to pick.
Still, agree would be great to have

**Comment by elena-zh** [comment]
No longer relevant as the affiliate section is removed
