### ISSUE TITLE
[1.62] Recreate: price impact is wrong when sell amount is low

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4040]
1. Connect to a wallet
2. Open limit orders page, go to History tab
3. Select an order with low amount to sell (e.g. 25 USDC or so)
4. Open the order menu and press on the Recreate button
5. Wait till the data is loaded, change a Sell amount to a greater one (to 50 USDC)

**AR**: there will be a huge price impact, and a price will be incorrect
![image](https://github.com/cowprotocol/cowswap/assets/70885163/0aa6d3b3-9053-4071-a029-2d052556e5ac)

**ER**: price impact+price should be correctly displayed
![image](https://github.com/cowprotocol/cowswap/assets/70885163/e6affa07-b836-4a53-9795-0a1a9c8ecae1)

**Comment by alfetopito** [comment]
Managed to reproduce.

The issue is not (just) with the price impact, but the receive amount

https://github.com/cowprotocol/cowswap/assets/43217/b1791b0e-99b2-4eae-b80d-5ca74af4bef8

**Comment by alfetopito** [comment]
Still not able to fix it, but I know it's happening due to different in token decimals.
