### ISSUE TITLE
Approval is stuck pending

### ISSUE THREAD

**Issue by cmagan** [cowprotocol/cowswap#4044]
**Description**
Initiating approval didn't result with a wallet popup for signing.
Now the interface is stuck indicating pending status and won't allow to initiate a new approval

Clearing local storage didn't help 

![image](https://github.com/cowprotocol/cowswap/assets/6940448/bb7f5397-fba8-48c0-aebb-ddef8c7d86de)
![image](https://github.com/cowprotocol/cowswap/assets/6940448/34f33c1a-b995-4580-adb3-c17635b214c2)

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by elena-zh** [comment]
Hey @cmagan , thanks for reporting this. 
Could you please clarify whether you did the 2nd try? Sometimes the 1st one does not help.
Also, could you please try opening in incognito mode the app and see whether this button is also displayed there?

**Comment by jierlich** [comment]
Our users are experiencing this as well connecting via WalletConnect on Den (https://www.onchainden.com/). If you have a Gnosis Safe, you should be able to sign in and test it yourself.

Our logs are showing that the WalletConnect message is not being received on our end.

Let me know if any questions we can answer to provide more context.

**Comment by elena-zh** [comment]
Hey @shoom3301 , one more case to fix (also should be related to the issue): when ETH order fails on creating (signing TX duting the order creation took too long, the order got expired), it also hangs in the Creating state and can't be easily removed from the UI 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/774cf7f6-d177-414c-83a7-179b12860812)
