### ISSUE TITLE
No error when try placing Limit order with 0 price in Safe

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4046]
1. Open the app inside the Safe app
2. Go to Limit orders
3. Select a token without allowance to sell
4. Select To token, an amount to sell
5. Change the price to 0

**AR**: there is 'Approve and place limit order' button, enabled
![error](https://github.com/cowprotocol/cowswap/assets/70885163/ea3f49de-3fbc-4cc1-b527-56d2d7332f43)
this also still recalculates amounts when change a value in the sell field 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c2c80f90-13fd-42fb-95ec-e2c16bc440b8)

**ER:** 'Enter a price' error should be displayed
![enter a price](https://github.com/cowprotocol/cowswap/assets/70885163/5422d037-547f-4b73-94d1-9c656f93fa1a)

**Comment by shoom3301** [comment]
@elena-zh I don't think this is a bug.
Token approving has no relations with a price.

**Comment by elena-zh** [comment]
@shoom3301 , screenshot provided in the expected result is done when connected to EOA, so it is actually well-processed when connected to EOAs, but is not when connected to a SC wallets. 
My point here is that **everywhere** in the app it should be properly working in the same manner.
