### ISSUE TITLE
Add USD estimations into the token list

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4047]
Reported in https://cowservices.slack.com/archives/C04F92LS4UC/p1710415793023679

Would be great to see $ equivalents for all tokens when you select which tokens to swap.
![Screenshot 2024-03-14 at 11 34 07 (1)](https://github.com/cowprotocol/cowswap/assets/70885163/58db23ae-1893-4302-8658-8ce5d509ebaa)

**Comment by anxolin** [comment]
I think we can close this one for now
