### ISSUE TITLE
Add more context into onchain TXs snackbars

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4049]
Reported in https://github.com/cowprotocol/cowswap/pull/4045#pullrequestreview-1937273008
It would be great to add 'Fail' word into the notificaiton when wrap/unwrap/approve or other onchain TX fails
![fail](https://github.com/cowprotocol/cowswap/assets/70885163/db4c62c9-abbb-4778-81c4-76d734d781e4)

**Comment by shoom3301** [comment]
The enhancement looks a bit excessive.
Developers should implement their own listeners and decide how to react on events.
Docs: https://github.com/cowprotocol/docs/blob/7657ccb50af17f00e89389042379889298111f41/docs/cow-protocol/tutorials/widget.md

@anxolin do you think so?
