### ISSUE TITLE
[Notifications] Double 'Cancelled' notifications when cancel onchain

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4053]
Reproducible with EOA (when cancel onchain) and SC wallets

1. Place any order
2. While the order is Open, run cancel TX (onchain)
3. Wait till the TX is executed

**AR**: user receives 2 cancelled pop-ups and 2 sounds

**ER**: user should get only 1 pop-up and sound

**Comment by anxolin** [comment]
@alfetopito @shoom3301 is this something recently introduced or it was happening before?

**Comment by alfetopito** [comment]
I think this is new, maybe related to the move away from redux for notifications?

**Comment by anxolin** [comment]
I only get one message and one sound....
tested in https://dev.swap.cow.fi/#/100/swap/WXDAI/EURe

<img width="1723" alt="image" src="https://github.com/cowprotocol/cowswap/assets/2352112/f3882607-0475-48d6-87a9-3672e88309e1">

**Comment by elena-zh** [comment]
Indeed. I've played around with different types of orders, and can't reproduce the issue. Thanks for checking!
