### ISSUE TITLE
[safe] Review safe decoding

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#4066]
Safe team is working on decoding the pre-sign orders in order to show the relevant information.

This is great step forward, as it eliminates the bling-signing of trades for DAO members or multisig owners.

This issue is about reviewing the swagger docs and giving feedback to Safe team:
https://cowservices.slack.com/archives/C03DVQREAH0/p1710777008893389

**Test check list**
- [ ] Swap/Limit orders: Sell orders vs Buy orders (type, and "at least" vs "at most")
- [ ] Swap/Limit orders: Cancelation flow is decoded
- [ ] Swap/Limit orders: Has explorer link
- [ ] Swap/Limit orders: Shows Limit Price (Open/Cancelled/Expired/Cancelling/Signing statuses)
- [ ] Swap/Limit orders: Shows Execution Price (Filled orders)
- [ ] Limit orders: Shows Avg. execution price for Partially fillable orders (Open+PF/Filled/Partially filled statuses)
- [ ] Swap/Limit orders: Shows Filled amount (handle partial fillable / Fill or Kill)
- [ ] Swap/Limit orders: Shows order type (Partially filled or Fill or Kill)
- [ ] Swap/Limit orders: Statuses: 
 - Signing,
 - Filled, 
 - Open, 
 - Cancelling,
 - Cancelled, 
 - Expired, 
 - Partially filled+Expired = Partially filled,
 - Partially filled+Opened= Open,
 - Partially filled+Cancelled= Partially filled.
- [ ] Swap/Limit orders:  Warning: change of receiver --> `IMPORTANT as it will lead to hacks not doing it`
- [ ] Swap/Limit orders: Sell/Buy token and links to Etherscan/Gnosisscan (to make sure the token is good)
- [ ] ?TWAP flow: parent and a part indication, fields for parent and parts...
- [ ] Good to have?
    - [ ] Surplus?
    - [ ] Order placement time?
    - [ ] Hooks, and other appData
    - [ ] Bad price (out of market order)?
    - [ ] Limit vs Swap
    - [ ] not enough allowance/not enough balance warnings?

**Comment by elena-zh** [comment]
Test round 29-30/04:

**Test check list**
- [ ] Swap/Limit orders: Sell orders vs Buy orders (type, and "at least" vs "at most")
- [ ] Swap/Limit orders: Cancelation flow is decoded
- [ ] Swap/Limit orders: Has explorer link
- [ ] Swap/Limit orders: Shows Limit Price (Open/Cancelled/Expired/Cancelling/Signing statuses)
- [ ] Swap/Limit orders: Shows Execution Price (Filled orders)
- [ ] Limit orders: Shows Avg. execution price for Partially fillable orders (Open+PF/Filled/Partially filled statuses)
- [ ] Swap/Limit orders: Shows Filled amount (handle partial fillable / Fill or Kill)
- [ ] Swap/Limit orders: Shows order type (Partially filled or Fill or Kill)
- [ ] Swap/Limit orders: Statuses: 
 - Signing,
 - Filled, 
 - Open, 
 - Cancelling,
 - Cancelled, 
 - Expired, 
 - Partially filled+Expired = Partially filled,
 - Partially filled+Opened= Open,
 - Partially filled+Cancelled= Partially filled.
- [ ] Swap/Limit orders:  Warning: change of receiver --> `IMPORTANT as it will lead to hacks not doing it`
- [ ] Swap/Limit orders: Sell/Buy token and links to Etherscan/Gnosisscan (to make sure the token is good)

**Comment by anxolin** [comment]
Thanks for testing all this @elena-zh . Do you see any important blocker from our side, or are all this issues on their side they plan to fix?

**Comment by elena-zh** [comment]
@anxolin , no blocking issues from our side, IMO. Just nice to haves like: 
 - #4285 
 - #4229 - is still reproducible on my end
 - #4289 - low prio issue

All the rest issues I reported are related to changes on Safe side.

**Comment by elena-zh** [comment]
Test round 16/05 (on Prod):

**Test check list**
- [x] Swap/Limit orders: Sell orders vs Buy orders (type, and "at least" vs "at most"): _**all orders and notifications are named as 'Swap', even Limit orders. Reported to them**_
- [x] Swap/Limit orders: User can cancel an order
- [x] Swap/Limit orders: Has explorer link
- [x] Swap/Limit orders: Shows Limit Price (Open/Cancelled/Expired/Cancelling/Signing statuses): _**in the order preview (before signing) they include slippage/fees into the price. Added a proposal to them to explain about this to users?**_
- [x] Swap/Limit orders: price: **_can't be inverted. Reported to them. They will not fix._** 
- [x] Swap/Limit orders: Shows Execution Price (Filled orders)
- [x] Limit orders: Shows Avg. execution price for Partially fillable orders (Open+PF/Filled/Partially filled statuses): **_They do not show. Reported to them_**
- [x] Swap/Limit orders: Shows Filled amount (handle partial fillable / Fill or Kill)
- [x] Swap/Limit orders: Shows order type (Partially filled or Fill or Kill) **_They do not show. Reported to them_**
- [x] Swap/Limit orders: Statuses: 
 - Signing,
 - Filled, 
 - Open, 
 - Cancelling, _**They don't have cancelling state. Reported to them.**_ 
 - Cancelled, 
 - Expired, 
 - Partially filled+Expired = Partially filled, **_in Safe they show 'Expired'. Reported to them_**
 - Partially filled+Opened= Open,
 - Partially filled+Cancelled= Partially filled. **_in Safe they show 'Cancelled'. Reported to them_**
- [x] Swap/Limit orders:  Warning: change of receiver -->**_The receiver is displayed in the preview, but is not displayed in the TX log. Reported to them. They will fix this_**
- [ ] Swap/Limit orders: Sell/Buy token and links to Etherscan/Gnosisscan (to make sure the token is good) **_They don't have links to tokens, but have links to Explorer/TX details/etc._**

**Additionally reported:** 
 - Surplus is not correct for Buy orders
 - Surplus is not displayed for Open+Partially filled, Cancelled+Partially filled, Expired+Partially filled orders
 - Slippage field is displayed for Limit orders
 - Some UI and UX issues
 - 'Order expired' notifications appear for orders that were not signed
