### ISSUE TITLE
No 'Insufficient allowance' warning for permittable tokens in Safe

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4076]
Currently, permittable tokens are not supported in SC wallets. So every time when allowance becomes 0, and a limit order is created with this token as a Sell token, we need to show 'Insuffisient allowance' warning for these orders.

**To reproduce:** 
1. Open the app inside the Safe wallet
2. Select a sell token with no allowance to sell
3. Specify allowance amount < than the order amount
4. Place a partially fillable order.
5. Wait till the order is partially filled (all approved amount is executed)
6. Check the order

**AR**: status says 'Open'
![image](https://github.com/cowprotocol/cowswap/assets/70885163/a28195c8-22d4-45de-8d70-1413c2824459)

**ER**: it should say 'Unfillable' and show the  'Insufficient allowance' warning (when approved amount is <0.05%)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/1f0bfc23-6ddc-4814-9f44-513408cc6043)

**Comment by anxolin** [comment]
@elena-zh  @shoom3301 any clue why this is related to the Safe? Why do you say this is related to permitable tokens? I mean, we always do the allowance check, the only difference for permit orders is that if there's a permit as a pre-hook then we can count the order as OPEN, but here is not the case.

I think this one we should fix cause makes people think the protocol is not working
