### ISSUE TITLE
[CoW Swap] IPFS deployment

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#4078]
# Summary

Last IPFS deployment was version 1.54.2 https://github.com/cowprotocol/cowswap/actions/runs/7448985265/job/20264551920 on January https://github.com/cowprotocol/cowswap/releases/tag/v1.54.2

https://bafybeicccgo3vjq7m6n24gjqq6dimoe5bp5tzmidemesq3cpzrv2fo7th4.ipfs.dweb.link/cowswap/#/1/swap/WETH

We should make sure every new version gets deployed to IPFS

**Comment by anxolin** [comment]
Done
