### ISSUE TITLE
Remove Shimmering effect from menu button (uni merge)

### ISSUE THREAD

**Issue by W3stside** [cowprotocol/cowswap#408]
> but it doesnt for me, only does in emulated chrome
@elena-zh u see this on ur mobile device or on web eumlated?

It at least happens on iOS simulator as well:
<img width="425" alt="Screen Shot 2022-04-14 at 16 29 15" src="https://user-images.githubusercontent.com/31534717/163423254-4d46daa5-f2ec-4fc3-a9e6-e6d6302a5a75.png">

But this effect has been removed in our latest release (glowing effect). If it's still present here then we should be careful about not accidentally introducing it again.

_Originally posted by @fairlighteth in https://github.com/cowprotocol/cowswap/issues/380#issuecomment-1099305774_

**Comment by elena-zh** [comment]
No longer reproducible
