### ISSUE TITLE
The app is crashed when switch network during classic ETH-flow

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4092]
1. Connect to the wallet in Sepolia chain
2. Select ETH as a sell token
3. ETH amount should be > WETH balance in the wallet, WETH should not be approved
4. Expand the 'Switch to the classic mode' dropdown and press on the Wrap ETH and Swap button
5. Run the Wrap transaction
6. When it is mined, switch to the GC in the connected wallet

**AR**: the app is crashed
![image](https://github.com/cowprotocol/cowswap/assets/70885163/0fb3f325-2304-426f-b563-1626ad6b68ea)

**ER**: the app is not crashed

**Comment by anxolin** [comment]
This looks bad. @shoom3301 @alfetopito can any of you look at this?
