### ISSUE TITLE
[CoW Swap] Accept appData as url param

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#4107]
# Summary

Add `appData` as optional url parameter

Suggested by Felix on [this issue](https://github.com/cowprotocol/docs/issues/341#issuecomment-2018493435)

**Comment by anxolin** [comment]
If we do this one, could we also add the limit price in the URL params? (currently missing)

**Comment by anxolin** [comment]
@alfetopito, I will close this one in favour of these two:
- https://github.com/cowprotocol/docs/issues/358
- https://github.com/cowprotocol/cowswap/issues/4237
