### ISSUE TITLE
Uni merge: Network selector is enabled when connected to SC wallets 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#414]
Originally reported in https://github.com/cowprotocol/cowswap/pull/406#issuecomment-1098807170 (case 2)

Network selector is enabled when connected to WC wallets (as an example, to Safe). So when I try to change a network, I see this warning message, that seems to me illogical as Safe wallet does not support networks changing. So can we disable this dropdown when connected to SC wallets at least?
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/625e3479-3d44-44c2-9ea6-7e09b944611c)

**Comment by W3stside** [comment]
@alfetopito @anxolin @nenadV91 @fairlighteth  thoughts?

**Comment by W3stside** [comment]
i agree we should hide on sc wallet detection

**Comment by anxolin** [comment]
Mmm, but doesn't other wallet that use wallet support to change the network using wallet connect? 

What about Metamask mobile for example? If i'm not mistaken there.
Also, how does it behave with Minerva? see https://github.com/cowprotocol/cowswap/issues/233

**Comment by elena-zh** [comment]
- With WC MM, Coinbase it network switcher works perfectly fine (in Mobile and in Desktop).
 - With TrustWallet, imToken, TokenPocket, Minerva**mobile**: network selector navigates to the wallet, ant that it. In **desktop** simply nothing happens when press on a network in the selector
 -  1Inch: user sees this message when tries to change a network (both desktop and Mobile) 
![image](https://user-images.githubusercontent.com/70885163/165704659-e9ccad76-c998-4a1a-80be-678078ea6ea7.png)
 - Fortmatic: the app hangs when I try to change a network using selector. 

So I'd disable the network selector like we currently do in the Production at all for those wallets that do not support network switching via WC, as the current implementation in the Uni merge works fine with  MM and Coinbase wallets only.

**Comment by fairlighteth** [comment]
I think there are different ways to read and understand `..you must change the network in your wallet..`:

1. You have to switch using a feature in your wallet. This is not always present and mentioned by others here.
2. You have to connect with your wallet using a different network.

Both mean the same, but on the second point above you have to switch manually. E.g. with a Mainnet (smart contract) Safe wallet, you have to manually switch (use) another network and re-connect with WalletConnect. Much more (manual) steps involved but in the end it achieves the same.

Back to the network switcher: We intend that to trigger the 'switching' function on the client wallet's end. But this obviously doesn't work for each wallet.

In the end, we do want to signal and make it clear to the user **what other networks we do support.** This gives the users enough cues as to what they could do and allows them to identify and address the problem:
- (manually) switch networks on their (smart contract) wallet
- Consider using another wallet they might have, on the right network

So perhaps the message should try to address that in detail. For example:
> Failed to automatically switch to the Ethereum network. In order to use CowSwap on Ethereum please manually change/use the network in your wallet.

Our messaging could also be made more specific in case we can detect the connected wallet client. E.g. we can detect it's a Safe and provide detailed steps there:
> Failed to automatically switch to Ethereum. In order to use CowSwap on Ethereum please switch the network in your Safe and re-connect with WalletConnect.

**Comment by anxolin** [comment]
We can know the connected wallet because WC report their name, so i think Michel proposal should be feasible. 

Can we open a issue for all the wallets that this doesn't work on their side? They should address the problem, or if it's WalletConnect, they should try to sort it out with them. 

I see hiding as a pragmatic solution, but i would avoid doing, its sad having to do so when this some wallets support it.
