### ISSUE TITLE
The app gets crashed when place Limit orders with USDC token, specific combinations

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4178]
See details in https://cowservices.slack.com/archives/C0361CDG8GP/p1711014216646249

Try placing a limit order with USDC-FLIP token pair, change amounts in the Sell field

**AR**: the app may be crashed on an order placement

**ER**: no crash

**Comment by anxolin** [comment]
@alfetopito @shoom3301 is this something we want to fix?

**Comment by alfetopito** [comment]
Checked with the user, they said they will try whenever the prices are better.
They don't want to place the order with the same exact amounts right now as it would be below market and execute right away.

**Comment by elena-zh** [comment]
Closing this for now.
