### ISSUE TITLE
Widget: arrow in the classic flow modal is not clickable

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4183]
1. Open widget.cow.fi
2. Connect to a SC wallet using WC
3. Try placing an ETH order when ETH amount<WETH balance
4. Press on the Swap button
5. Try pressing on the back button when 'Wrap my eth' modal is displayed

**AR**: impossible: the arrow is not clickable
![image](https://github.com/cowprotocol/cowswap/assets/70885163/9f9939e8-d4f4-4c15-a609-e27c8b8dc601)

**ER**: the arrow should be clickable.

**Comment by alfetopito** [comment]
@elena-zh which SC wallet you used?
With Safe it shows the bundling option instead of the classic ethflow

![Image](https://github.com/cowprotocol/cowswap/assets/43217/a6a8cba3-5871-4bac-8d8c-b4f20a9f58a6)

**Comment by elena-zh** [comment]
@alfetopito , connection to Safe also works in order to reproduce this issue. 
When you click on the Swap with WETH button, it will call the next modal 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/8a54843e-6a75-44dc-a17f-6add6536aa0f)

But! The most important thing is that the issue is no longer reproducible (in the new version). So I'm closing this :)
