### ISSUE TITLE
Ambire: impossible to place a TWAP using this wallet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4199]
1. Open The CoW Swap app inside the Ambire wallet (dApps tab)
2. Navigate to the TWAP page there

**AR**: the app says that the wallet is not supported
![image](https://github.com/cowprotocol/cowswap/assets/70885163/6a18bcd7-f1d6-45eb-8f1d-ad18dfbc2913)

**ER**: it should be possible to place a TWAP (in a Safe-based wallet)

**Comment by anxolin** [comment]
Indeed it doesn't work.

We don't detect the SDK as we do with the Safe. I think we should talk to Ambire team, and seek help, I didn't see a lot of info in https://help.ambire.com/hc/en-us/articles/4415496135698-Which-dApps-are-not-supported-by-Ambire-Wallet
