### ISSUE TITLE
[1.65] Widget is not connected when open it inside Safe

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4207]
1. Load the widget configurator app (https://widget-configurator-git-release-20240409-cowswap.vercel.app/) into the Safe as a custom app
2. In the Safe, switch between Safes in different networks several times (429 error should appear in the console)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/5c282590-513b-4a16-90bc-de05a27d2e5e)

3. Reload the Safe app with the opened widget

**AR**: when something goes wrong (errors in console), OR app is loaded too long, the widget confiogurator is opened in a not connected state inside
![image](https://github.com/cowprotocol/cowswap/assets/70885163/f017cc83-0cb0-4b8f-9e91-d85954a977de)

**ER**: the widget should be connected

Note: going back to apps and loading the widget configurator again helps to resolve this issue. 
Also, waiting a bit, then refreshing the page also helps.

**Comment by anxolin** [comment]
@elena-zh  I tested this, and I see that the issue just giving an error saying "Error Loading Balances", but if you navigate a few seconds later to another page and come back, it recovers from that

What happens is that we are rate-limited if we stress the RPC provider as you described, and is possible we struggle to load the balances, but letting it cool down a bit will solve the issue on its own

**Comment by anxolin** [comment]
I can see that, at least in my case is super hard to break it even though I'm loading fast a lot of safes and making hundred of requests.

Should we close it?

**Comment by elena-zh** [comment]
@anxolin , lets close this. We always can re-open the issue once receive user complaints :)
