### ISSUE TITLE
[1.65] Stop requesting cancelled/replaced orderID

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4209]
Related to #4143

**Steps**: 
1. Place a ETH order (any network)
2. When signing a TX, specify tooo low gas price
3. Sign a TX
4. Cancel the  onchain TX in the wallet
5. Check the app/console

**AR**: the app keeps requesting for the ETH order ID that can't be created. It reduces the app's performance.
![image](https://github.com/cowprotocol/cowswap/assets/70885163/314febc0-ab75-4363-aca8-daef7999f07a)

**ER**: stop requesting an orderID once order creation fails. 

-----

Additionally: when an order is cancelled/replaced in GC or Sepolia, it would be great to remove 'Cancel ' order button from an order details log in the Account modal
![image](https://github.com/cowprotocol/cowswap/assets/70885163/b3233ab7-a8f3-468c-bf12-d6eff1552324)

**Comment by anxolin** [comment]
@shoom3301 , could this be that we treat on-chain cancelation same as off-chain cancelation?
The difference is that off-chain cancelation is not final (until is expired), off-chain cancelation is final once mined
