### ISSUE TITLE
[1.65] TX replacement: incorrect order status when execute conflicting TX in Safe

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4210]
**Please follow exact steps to reproduce:** 
1. Connect to the Safe using WC
2. Specify a SWAP order
3. Sigh the order request in Safe, but don't execute
4. Create a WRAP transaction
5. When signing, re-use the order creation nonce from the step 3, sign the request
6. Open Queued transactions list in Safe
7. Execute the 1st (order creation) transaction
8. Wait thill the TX is executed, check the Account modal

**AR**: the order creation log shows 'Cancelled' status
![Screenshot_3](https://github.com/cowprotocol/cowswap/assets/70885163/6c1c18af-b8d3-4ad6-b465-99795876e5ed)

**ER**: the order creation log should show 'Open' status (TX is executed, order is created)

**Comment by anxolin** [comment]
@shoom3301 could you assess this one? I guess is detecting the nonce bump, but not the order becoming open. Not sure if we get the state of the safe transactions periodically, but I think this info is available (it should show that it was executed)
