### ISSUE TITLE
Widget: ETH balance is not auto-updated

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4228]
1. Open https://widget.cow.fi/
2. Connect to a wallet in dapp mode
3. Run Wrap transaction
4. Once TX is mined, check the ETH balance in the connector

**AR**: the balance is not changed. It is changed only when I refresh the lage
![auto-update](https://github.com/cowprotocol/cowswap/assets/70885163/b2770e23-7c49-4015-a817-434835ab069c)

**ER**: the balance is updated.

**Comment by anxolin** [comment]
CoW Swap balance is right, I think it doesn't need any fix
