### ISSUE TITLE
safe.widget.cow.fi is connected to MM inside the Safe

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4229]
When I open the app inside the Safe in Sepolia, it appears connected to MM, not to Safe 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/1d6cbd6a-f813-4c56-9c2f-6aaf1d2558ac)

Each change in the top fields triggers MM switching to Ethereum
![image](https://github.com/cowprotocol/cowswap/assets/70885163/5c204fd5-5efc-4e09-87b0-3b10dc0d1c81)

The issue happens when I open the link in incognito mode as well. 

----
Some additional details: 

[Safe address ](https://app.safe.global/apps/open?safe=sep:0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531&appUrl=https%3A%2F%2Fsafe.widget.cow.fi) where I reproduce this issue.

Local storage: safe.widget.cow.fi:
[2 (2).txt](https://github.com/cowprotocol/cowswap/files/14948228/2.2.txt)
Local storage: WC: 
[2 (1).txt](https://github.com/cowprotocol/cowswap/files/14948222/2.1.txt)
Local storage (top): 
[2 (3).txt](https://github.com/cowprotocol/cowswap/files/14948237/2.3.txt)

**Comment by elena-zh** [comment]
Not fixed in #4271 :(

**Comment by shoom3301** [comment]
It should be already fixed in #4416

**Comment by elena-zh** [comment]
@shoom3301 , now I can see that I'm not connected at all
![image](https://github.com/cowprotocol/cowswap/assets/70885163/821dfbf9-aae4-4006-b6ab-ae108c095d0d)

**Comment by elena-zh** [comment]
No longer reproducible
