### ISSUE TITLE
Limit orders: Warn users about Expiry date in the past

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4248]
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1713256624644769

1. Open Limit orders page
2. Connect to a wallet
3. Specify a trade
4. Select a custom date: min allowed (+30 min from the current time)
5. Wait for 31 minutes
6. Try placing an order

**AR**: user gets 'already expired' message 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/06639aef-00db-4812-ab3c-6494c73216b9)

**ER**: warn a user about a date in the past in the Expiry field

**Comment by anxolin** [comment]
I think what happens is that the UI persists the date as an absolute date. 

I think what users would expect here is that CoW Swap remembers the relative dates for subsequent trades.

**Comment by anxolin** [comment]
I agree is improvable but the user already get a message informing, and is not common to leave it there for 30min

Closing for now
