### ISSUE TITLE
[Limit orders] Modify order (cancel+create)

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#425]
**Description**

Allow users to replace existing orders

**Additional resources**

This feature involves allowing users to, in a single operation, cancel existing orders and replace it with a new one.

It also allows users to "replay" existing orders by pre-filing the UI with data for a previous order.

**Feature breakdown**
It includes:
- [ ] Adding to recent activity [1]
- [ ] Recreate order (Canceled / Filled) UI [5]
- [ ] Replace order (Pending) [10]
- [ ] Sign the order: Add meta-info to the order so backend ensures that only one of the orders are executed [2]
- [ ] Replacing/Replace logic for old pending: only for new [5]

Good to have:
- [ ] ???

> Original issue https://github.com/gnosis/cowswap/issues/2467 by @alfetopito

**Comment by alfetopito** [comment]
FYI, backend support for cancel+place is available for almost 2y https://github.com/cowprotocol/services/pull/239

Given that it has been sitting for so long without integration, I believe it's outdated, specially in regards to appData field usage.

By the time it was implemented, there was no [appData schema definition](https://github.com/cowprotocol/app-data/).
This field however stores important information for Fronted, Backend and Analytics. Replacing the original order's appData with cancellation specific format can cause all sorts of issues making it unfortunately not worth it in the current state.

**Comment by alfetopito** [comment]
Backend work to update the endpoint while keeping up with current appData expectations tracked on https://github.com/cowprotocol/services/issues/2365

**Comment by alfetopito** [comment]
As part of this:

- New app-data version https://github.com/cowprotocol/app-data/releases/tag/v2.1.0, updated by Mateo
- Update sdk with latest backend version https://github.com/cowprotocol/cow-sdk/pull/201 - including the new recreate order feature
