### ISSUE TITLE
[widget] Impossible to see orders

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#4268]
**Description**
We only show the orders button in responsive mode for SWAP.

We should always be able to see the orders. I believe is not shown in: "non responsive "dapp mode" (not standalone)"

So if we don't show the account, at least we should show the "Orders" button so users can cancel or check the state

Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1712908269756109

https://github.com/cowprotocol/cowswap/assets/2352112/3d534e99-c0e9-46dc-9c70-049627a12fdc

**Comment by elena-zh** [comment]
Fixed in #4297
