### ISSUE TITLE
Arrows are different on the Swap form

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4278]
Reported in https://cowservices.slack.com/archives/C03DVQREAH0/p1713525427689839

See the image: arrows are not alighned, and are different ones 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/c45fda59-a095-4cb1-a02c-c8d7a43c5f65)

**Expected**: arrows should have the same design and position.

**Comment by shoom3301** [comment]
@elena-zh I think they are looking good.
What do you compare the UI with? I mean, is there  Figma or smth else?

**Comment by elena-zh** [comment]
@shoom3301 , this issue came from the Safe team, the link is in the description. 
Based on the [discussion](https://cowservices.slack.com/archives/C0361CDG8GP/p1713527162698989), @fairlighteth confirm a possibility of making arrows to look the same.
