### ISSUE TITLE
Add signers block to the Order Submitted modal

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4285]
Discussed in https://cowservices.slack.com/archives/C03DVQREAH0/p1713514473784299
An initial attempt of implementing this was made in #1081 

Add signers block to the Order Submitted modal:
![image](https://github.com/cowprotocol/cowswap/assets/70885163/6635196d-8e40-48aa-a715-5bbe82083928)
+
![image](https://github.com/cowprotocol/cowswap/assets/70885163/392206a3-7d7a-4e6a-a958-49ef5067facf)

**Comment by anxolin** [comment]
@shoom3301 not to critical, but if this is just reusing our component, I think it really makes sense to add it

**Comment by elena-zh** [comment]
Done
