### ISSUE TITLE
Add new Network

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#4310]
https://www.notion.so/cownation/Add-new-nework-5b96447bee7d4b9997136e1d6c359a9c?pvs=4

**Comment by alfetopito** [comment]
- [x] SDK https://github.com/cowprotocol/cow-sdk/pull/206
- [x] Quote config https://github.com/cowprotocol/cowswap/commit/9efb564b76e329b7460bb61baa5fb546edc9c43a
- [x] Announcements https://github.com/cowprotocol/cowswap-banner/pull/10

**Comment by alfetopito** [comment]
- [ ] Token lists pt1 (PermitInfo and Token form) https://github.com/cowprotocol/token-lists/pull/389
- [ ] Token lists pt2 (Coingecko mapped via bridge): TODO
- [ ] CoW Swap https://github.com/cowprotocol/cowswap/pull/4407

**Comment by alfetopito** [comment]
- [ ] Watch tower pt1: update SDK https://github.com/cowprotocol/watch-tower/pull/152
- [ ] Watch tower pt2: infrastructure https://github.com/cowprotocol/infrastructure/pull/1501

**Comment by alfetopito** [comment]
- [ ] Update docs https://github.com/cowprotocol/docs/pull/390

**Comment by alfetopito** [comment]
- [ ] Update services repo docs https://github.com/cowprotocol/services/pull/2757
