### ISSUE TITLE
Refactor tooltips logic

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4343]
Task related to this [discussion ](https://github.com/cowprotocol/cowswap/pull/4339#issuecomment-2086145697)

> Hey @anxolin , I'd like to clarify whether this behavior should be applicable for explanation tooltips in the token list?:

Good question. In principle yes, should be the same. The issue is tooltips are a mess for what I can see. There are multiple implementations and there's some replicated logic that lead to these differences

It was not part of my scope, but I'm trying now to see if I can improve this in a follow up PR. If you could, limit the review for this one for the `fee` tooltip, as this is what blocks the release for the Safe. I will give it a try to refactor some of the tooltips in another PR (but not promises, as I will need to untangle some things and this component is used a lot)

So let's leave for the scope of this PR only these 2 fields, unless I'm breaking something that works on production. I believe this behaviour was already like this in the app.

<img width="586" alt="image" src="https://github.com/cowprotocol/cowswap/assets/2352112/f7fc3fe4-b757-4442-9201-a04c0e0cadbe">

Having said this, I did a mini-refactor for this tooltips, so this now should behave in the same way for this PR already:
<img width="1069" alt="image" src="https://github.com/cowprotocol/cowswap/assets/2352112/debc27ed-dea2-4778-abb4-49fb18c19b5f">

Eventually all tooltips will behave well, just let limit the scope of this PR.

> Also, to let you know that issues I reported in https://github.com/cowprotocol/cowswap/pull/4337#pullrequestreview-2031340031 and in https://github.com/cowprotocol/cowswap/pull/4336#issue-2271198701 are reproducible in the PR as well

I'm afraid this is also because these tooltips are not the same tooltip component as the one used for the fee. So It should be fixed after we do a refactor. So, not this PR

**Comment by anxolin** [comment]
@elena-zh could you try here? https://github.com/cowprotocol/cowswap/issues/4343
