### ISSUE TITLE
Limit order creation fails when place several orders one after another

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4346]
Reported in https://cowservices.slack.com/archives/C0375NV72SC/p1714557340855299

1. Connect to the wallet, go to the Limit orders page
2. Place 5 (or more) limit orders one after another with default duration (7 days)

**AR**: the 5th order creation will fail due to validTo=0 in the request
![image](https://github.com/cowprotocol/cowswap/assets/70885163/12b1fc07-d22e-4fae-ad15-6e5db56a77ec)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/8f1391c7-01c0-4dc6-a9a5-80f31fa9fa90)

**ER**: the order creation should not fail.

**Comment by anxolin** [comment]
This is strange, why 5. I would love we review this, because seems like we might have some race conditions and this might be covering up something bigger.

**Comment by elena-zh** [comment]
5 on average. Sometimes 4. Just need to place them one after another. 
After failure, need to wait for 10-20 seconds, and the next order will be successfully placed.

**Comment by shoom3301** [comment]
It's not a question of orders count, I've created 7 in a row and didn't catch the error:

<img width="1051" alt="image" src="https://github.com/cowprotocol/cowswap/assets/7122625/80def5c6-3af2-4b82-9aa2-503a2fa613ff">
