### ISSUE TITLE
Toolltips may point to a wrong place in a mobile device

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4348]
Related to #4342 

Tested in iPhone 13 mini+Safari, iOS 17.4.1

Sometimes, tooltips may point to a wrong place on the form. 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/ca45be55-5bbc-4f32-b802-fd5c8bd552e9)

**Comment by anxolin** [comment]
> (1) Tooltips may not be opened when press on the question icon for the 1st time

Thanks @elena-zh, I did a small change to improve on https://github.com/cowprotocol/cowswap/pull/4342 to improve on (1)

> (2) Tooltips are moving on scroll and are not closed

I removed this code to make it simpler...  I can always bring it back, but I thought the scroll is not that bad. Will leave this issue open, if we want to have this behaviour is just to bring this code back: https://github.com/cowprotocol/cowswap/pull/4337/files#diff-400d713bb6c96f6ad6185b8e36f1f749634f94a5d00c830c62bfa79d472ce83eR134

**Comment by elena-zh** [comment]
> > (3) Sometimes, tooltips may point to a wrong place on the form.
> 
> I didn't get what you mean with this one

@anxolin , see: the arrow is displayed at the bottom, not points to the tooltip icon I pressed. 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/1e648c58-114b-4fb2-9d95-1084caec5ee6)

**Comment by elena-zh** [comment]
Cases 1-2 LGTM in #4342 !

**Comment by elena-zh** [comment]
Closing for now
