### ISSUE TITLE
Meta descriptions: Abbreviate numbers

### ISSUE THREAD

**Issue by fairlighteth** [cowprotocol/cowswap#4393]
For a Meta description such as:
> Graze on this: Dai (DAI) at $0.999828, with decrease ▼ of -0.05% in 24h. Trading volume: $191496741. They boast a market cap of $4331495723. Learn about DAI.

It would be great to abbreviate the trading volume and market cap numbers. 
E.g. 191,496,741 = 191.5M

**Comment by elena-zh** [comment]
Closing for now. Will reopen once decided to proceed with Tokens page implementation
