### ISSUE TITLE
Recipient field clears out when switching tokens

### ISSUE THREAD

**Issue by compojoom** [cowprotocol/cowswap#4411]
**Description**
If you enable custom recipient and enter an address, switching the tokens would clear the recipient address

**How to Reproduce**
1. Go to [CoWswap](https://swap.cow.fi)
2. Enable custom recipient form the settings
3. Enter an address for recipient
4. Change any token
Recipient will be lsot

**Expected behavior**
The entered recipient address should not be cleared out.

**Comment by elena-zh** [comment]
**Some notes to the Dev team:** It would be great to fix this issue along with: 
 - https://github.com/cowprotocol/cowswap/issues/4018
 - https://github.com/cowprotocol/cowswap/issues/3439

**Comment by elena-zh** [comment]
Fixed in #4519
