### ISSUE TITLE
Replace 'Read only' with 'Connect signer' message for TWAP/Limit pages

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4432]
1. Do not connect Safe to a wallet
2. Open the CoW Swap app inside the Safe (or open Swap form there)
3. Navigate to the Limit orders/TWAP page

**AR**: Read-only is displayed there
![signer](https://github.com/cowprotocol/cowswap/assets/70885163/6bbe430a-9098-406d-b320-f40252bfe268)

**ER**: it should show 'Connect signer' message like it is on the Swap page

**Comment by elena-zh** [comment]
> Anxo fixed it before

Hey @shoom3301 , please open Limit or TWAP page in order to reproduce this issue.

**Comment by shoom3301** [comment]
Aaah, sorry, it's not about swap
