### ISSUE TITLE
Add support for tokens with a tax

### ISSUE THREAD

**Issue by Mookow4eva** [cowprotocol/cowswap#4448]
I understand why taxes weren't supported in the initial version, just to keep things simple. But it seems like a solvable problem in general, just need to do a little more math.

**Comment by MartinquaXD** [comment]
We are aware that supporting these tokens would be a great new "feature" and this indeed seems to be a solvable problem in our current system. We already have a good general idea to work towards that but but not all the details are exactly clear, yet.
The key ingredient for a **general** solution would be to analyse every quote given by solvers and basically check their math to see if they truly understand that a given token has fee on transfer semantics. Theoretically whenever we can "prove" that there is at least a single solver that handles the fee on transfer properties correctly a token could be considered supported.

**Comment by Mookow4eva** [comment]
I get what you mean, but I don't think it should be the protocol's responsibility to "check the solvers' math". However to gracefully fail, orders containing tax shouldn't be shown to solvers that haven't yet opted into it. This could be done in various ways: protocol version bumping, rpc endpoint change, a config flag the solvers have to opt into, etc...
