### ISSUE TITLE
[1.70][notifications] Disable 'Due date' in notification's template when date in the past

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4450]
Reported in https://github.com/cowprotocol/cowswap/pull/4409#issuecomment-2117517510 (case 4)
Notification's template can be re-used. And when update the past date for a notification's template, an outdated notification  will appear again to users. 

So it would be great not to allow users modify due date in already published AND outdated notification template. Look: I've updated the date, and received 2 the same notifications 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/4d3f961e-4f97-4236-8ec4-ce5188d5361f)

**Comment by alfetopito** [comment]
Not able to do it right now
