### ISSUE TITLE
[1.70][notifications] Add staging env to notifications system

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4456]
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1716285681566159?thread_ts=1716281060.591949&cid=C0361CDG8GP

It would be great to separate notifications displaying per environment.

**Comment by alfetopito** [comment]
That's what Anxo did with the barn cms, right?

https://cowservices.slack.com/archives/C0361CDG8GP/p1718920035681709

cms.barn.cow.fi
