### ISSUE TITLE
[1.70] Add 'Beta' label to the notifications bar

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4486]
Add 'Beta' label to the notifications bar until the main functionality is implemented (Trade notifications/etc.)
Like a NEW label. but beta :) 
![image](https://github.com/cowprotocol/cowswap/assets/70885163/f374947c-e80e-455f-9926-1cecdb02f181)

**Comment by anxolin** [comment]
We discussed and we won't include
