### ISSUE TITLE
Button to approve token appears when no token balance in the wallet

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#451]
Connect to a wallet in the Ethereum Mainnet
Select a token pair, sell token with 0 balance in the wallet
Specify a token's amount to sell

**AR**: 'Allow CowSwap to use your 'token'' button appears
**There are no token balances in the fields**
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9c2a667c-f3ff-4114-9052-a3b5e69ea28a)

**ER**: tokens' balances show 0; 'Insufficient balance' message is displayed, there is no button to approve a token's spend.

**Comment by elena-zh** [comment]
Might be related to network/MM errors

**Comment by anxolin** [comment]
MM, I think this one is important to review, its likely that is the consecuence of some other error. 

@alfetopito do you think you can take a look to this one?

**Comment by alfetopito** [comment]
> Besides, there are a lot of errors might appear in the console ![image](https://user-images.githubusercontent.com/70885163/165094993-1fdedbad-2369-47c6-a5ae-e6cd0bba8ead.png)

Those errors are unrelated to the tokens/balances in the swap UI.
They are only regarding the tokens loaded from the API in the activity list and won't break anything in the UI.

Will now try to reproduce the issue in the description
