### ISSUE TITLE
[1.73][widget] Can't copy WC code in standalone mode

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4541]
Originally reported in https://github.com/cowprotocol/cowswap/issues/4155#issuecomment-2042754803
Discussed in https://github.com/cowprotocol/cowswap/pull/4522#issuecomment-2160131742

1. Open [the widget configurator](https://widget.cow.fi/)
2. Select Standalone mode
3. Select WC option
4. Press on the 'Copy code'

**AR**: impossible to copy
![image](https://github.com/cowprotocol/cowswap/assets/70885163/cbcf563c-a400-486b-adbe-18be316f32ea)

**ER**: it should be possible to copy

**Comment by alfetopito** [comment]
Works on Firefox, still doesn't work on Chrome

**Comment by alfetopito** [comment]
Reach out to WC team to improve/fix the issue
