### ISSUE TITLE
Limit: Order does not show '99.99%' of fill 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4548]
Related to #4482 and #4477 

Link to such order: https://dev.explorer.cow.fi/sepolia/orders/0x7717e411cb91aac3fd4bc787194b9a4e02048e9a361127cb5ef38496dde3c7229fa3c00a92ec5f96b1ad2527ab41b3932efeda5866743a1c?tab=overview

The order is 99.99999999999% filled, but it shows 100% **instead of '>99.99%'** both on CoW Swap and on Explorer. 
The order hangs in "partially filled' state on Exploer, in 'Open' state on CoW Swap' until expires
![image](https://github.com/cowprotocol/cowswap/assets/70885163/5303a11a-2e40-4fee-981c-f86919841a3f)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/cad4bc7e-c934-41c2-a4ef-3df8e4d8100f)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/fd412612-1303-4acd-a593-4aa5e0733281)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/da81df48-84c3-4546-b2c2-bd299cedb62a)

**Comment by elena-zh** [comment]
I've noticed that some orders are displayed with >99.99, some with 100%
![image](https://github.com/cowprotocol/cowswap/assets/70885163/a9e7da0c-ff29-4899-b7bf-fe70d89a3e4f)
Also, order lines are shifted a bit when '>99.99' filled order is displayed
![image](https://github.com/cowprotocol/cowswap/assets/70885163/5c594d88-70b4-4841-8ccc-af0f1a6d431e)

**Comment by alfetopito** [comment]
Regarding becoming expired, that's expected, since we do not want to mark them as fully matched when there's something left.
The rest should be fixed, I agree.
