### ISSUE TITLE
Unsupported Counterfactual Safe via WC

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4569]
Reported in https://github.com/cowprotocol/cowswap/pull/4553#issuecomment-2174240158 (case 1)

When connect to a counterfactual Safe using WC, the app still behaves like connected to EOA: 
 - max button for ETH token does not fill in 100% amount
 - no budling
 - ETH-flow shows 2% of slippage
 - permit flow works like with EOAs
![permit](https://github.com/cowprotocol/cowswap/assets/70885163/a3acf9ab-6da8-401c-98ae-fd911bc0f8aa)
![safe WC](https://github.com/cowprotocol/cowswap/assets/70885163/009877f8-bca1-4c97-8868-ca840ff57fde)

**Expected**: the app behaves like connected to SC wallet: 
 - max button for ETH token fills in 100% amount
 - message related to Bundling feature is displayed on forms when needed
 - ETH-order uses classic flow
 - no permittable tokens should be present

**Comment by compojoom** [comment]
Ah, now that I think of this - it's expected. You cannot detect whether this is a safe over protocol-kit. Protocol kit would make a request on-chain and there is no deployment for the safe. 
The counterfactual safe can only be detected through safe-apps-sdk, but it is only available if the app is running inside of safe. If you have a WC connection, there is no safe-apps-sdk and cow falls back to protocol-kit.

**Comment by alfetopito** [comment]
Dang it. Then we don't support CF Safes via WC and cannot tell when that's the case to prevent those weird edge cases :/

**Comment by compojoom** [comment]
We have an idea to expose a getSafe method over WC. Once could call it and it would return data for the safe. This way you could know that it is a CF safe. What do you think?

**Comment by alfetopito** [comment]
> We have an idea to expose a getSafe method over WC. One could call it and it would return data for the safe. This way you could know that it is a CF safe. What do you think?

That would be amazing.
What's the API that you have in mind?

**Comment by compojoom** [comment]
there is currently a setSettings method: https://github.com/safe-global/safe-wallet-web/blob/b51729389568c6b3e914bd8a6c88e021766f6dbf/src/services/safe-wallet-provider/index.ts#L167

Maybe something of the sort of safe_getInfo that would then return the same data as one would currently get over the iframe.

**Comment by alfetopito** [comment]
> there is currently a setSettings method: https://github.com/safe-global/safe-wallet-web/blob/b51729389568c6b3e914bd8a6c88e021766f6dbf/src/services/safe-wallet-provider/index.ts#L167
> 
> Maybe something of the sort of safe_getInfo that would then return the same data as one would currently get over the iframe.

Sounds good.

What's the context for it being called `setSettings`?
For some reason I thought this would be read only.

**Comment by compojoom** [comment]
setSetting is a method that is already available. 
the getInfo method will be read only.

**Comment by alfetopito** [comment]
> setSetting is a method that is already available. the getInfo method will be read only.

Ahhh I had misunderstood.
I though you meant to add that as part of the `safe_setSettings` method.

But now it's clear, we'd have something like `safe_getInfo` or similar.

**Comment by elena-zh** [comment]
Currently, it is impossible to run TXs with counterfactual safes (see https://github.com/cowprotocol/cowswap/issues/4569)
Closing this issue.
