### ISSUE TITLE
Allow to approve tokens with no balance

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#46]
## Separate token Approval from Swap function
Currently token allowance approval happens only once all fields are set and the swap is ready to go, in order to separate the token approval from trading, the system could check for allowance as soon as the user fills the "from" field. This way the user can start approving tokens at any time without any commitment to trading them now.

Testing and if needed asking for approval at this stage
![image](https://user-images.githubusercontent.com/66846441/121682891-f059a000-cabc-11eb-89f4-7bb70db9b1dc.png)

instead of this stage
![image](https://user-images.githubusercontent.com/66846441/121682990-11ba8c00-cabd-11eb-9084-7ce60574d1e5.png)

> Original issue https://github.com/gnosis/cowswap/issues/763 by @NanoOrca

**Comment by elena-zh** [comment]
Now users can approve tokens with 0 balances on Account --> Tokens page (1.21.0 version)
