### ISSUE TITLE
No warning about an unsupported network in  a mobile app

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#462]
1. Open a mobile wallet and select an unsupported network there
2. Open the wallet integrated browser OR **open the app in a mobile browser**
3. Connect to the Cowswap app there

**AR**: user sees that a wallet is not connected, no warning about wallet/app mismatch

**ER**: warning about wallet/app mismatch should appear

**Comment by W3stside** [comment]
@elena-zh I see this on MM mobile browser connected to ropsten using Android 
![Screenshot_20220504-113514](https://user-images.githubusercontent.com/21335563/166665947-77a00172-fec1-4390-801c-77ebc477fea8.jpg)
![Screenshot_20220504-113509](https://user-images.githubusercontent.com/21335563/166665952-f3f34959-65f1-43a1-9015-53eea6fb2150.jpg)

**Comment by elena-zh** [comment]
Hey @W3stside , please follow these exact steps: 
1. Change a wallet network to Ropsten
2. Then open an integrated browser
3. Paste Cowswap app url and try to connect to a wallet
So you will not see 'Wrong network' warning

'Wrong network' message appears when you connect to a supported network, then change it to an unsupported one. So that is why you are not able to reproduce the issue.

**Comment by elena-zh** [comment]
No longer reproducible
