### ISSUE TITLE
Recipient is not clickable on order confirm modal

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#4624]
We've lost this feature in one of the recent releases. 

To reproduce:
1. enable custom recipient option in the settings
2. Specify any order to a custome recipient
3. Press on the Swap/Limit/TWAP button to open confirm modal
4. Check the recipient field there

**AR**: it is a read-only field
![image](https://github.com/cowprotocol/cowswap/assets/70885163/d5a0cae3-6b13-4a22-a38f-3072c9892a6e)

**ER**: it has a link to a user's address on a blockexplorer.

**Comment by anxolin** [comment]
We should do, and should be trivial to impemnt

**Comment by elena-zh** [comment]
fixed in #4637
