### ISSUE TITLE
Freeze amount on Claim/Convert cards when transaction is running

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#463]
Related to #460 and #405

Could we 'freeze' somehow an amount we are claiming/converting when the transaction is signed and is pending? 
See the video: https://watch.screencastify.com/v/x2uVzq0E8FHkg4xzhi2j
 I started the transaction when the amount was 0.0019, and when transaction was finished, the amount was 0.0028. 
Claimed = 0.00256742294520548 . Moreover, I can't see what exact amount I'm claiming in the activity log, as well as the result of the transaction. 
https://rinkeby.etherscan.io/tx/0x069f505535f18dead4b2cd0847cd627df9808b55035bdc16ed246169bbca89a3

So 'freezing' will help a user to understand what the amount of COW he/she will receive in the end of the transaction.

**Comment by nenadV91** [comment]
At this point we cant freeze this since the contract method claims all that is vested at the time the transaction reaches it.

**Comment by elena-zh** [comment]
@nenadV91 , thanks for the explanation. 
Anyways, let the issue exist. Maybe one day we will enhance it.
