### ISSUE TITLE
Unsupported token FAQ anchor link not working

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#48]
# How to re-produce:
- Add an unsupported token `0x27dce1ec4d3f72c3e457cc50354f1f975ddef488`
- Click on the FAQ link:
<img width="693" alt="Screen Shot 2021-06-21 at 09 09 02" src="https://user-images.githubusercontent.com/31534717/122721058-7d94b580-d270-11eb-9256-7c498f865448.png">
- Should open a new page with this URL [](https://cowswap.exchange/#/faq#what-token-pairs-does-cowswap-allow-to-trade)
- On open of the page, it doesn't scroll you automatically to the right section. The same anchor link on the FAQ page does work on click.

# Suggestions how to fix:
- Need to investigate first how to support incoming anchor URL's. 

**Responsible code:**
`<HashLink to={UNSUPPORTED_TOKENS_FAQ_URL} target="_blank" onClick={e => e.stopPropagation()}>`

**File:**
`src/custom/components/SearchModal/CurrencyList/index.tsx` L91

> Original issue https://github.com/gnosis/cowswap/issues/787 by @fairlighteth

**Comment by elena-zh** [comment]
Duplicates #104
