### ISSUE TITLE
[Rebranding] Update logos on batch viewer

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#4831]
# Summary

Batch viewer still has old logos

![image](https://github.com/user-attachments/assets/9b3aa0f0-b046-4ae9-8605-6c896f1101a5)

Example order: https://explorer.cow.fi/tx/0xbbd95459d2da998f3fb0fa0f4bc2bff7ddabe1525ba47c10654fc7c981759d10/?tab=graph&vis=transfers

# Context

Raised internally [on slack](https://cowservices.slack.com/archives/C036G0J90BU/p1724438993433789)

**Comment by elena-zh** [comment]
Done
