### ISSUE TITLE
MM integrated browser: 'add token' button is not displayed in 1 line

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#490]
1. Open MM wallet in a mobile device
2. Open an integrated browser in the MM wallet
3. Connect Cowswap app
4. Open Profile page and check the COW card

**AR**: 'add token' button is not displayed in 1 line
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d268ef6b-d8fd-4354-ac5e-8b26fdb4d3cc)

**ER**: 'add token' button is not displayed in 1 line

**Comment by anxolin** [comment]
Super low effort, I think we should fix
