### ISSUE TITLE
Add a loader/card loading effect when open Profile page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#492]
1. Connect to a wallet account with available vCOW to convert, and COW from locked GNO (list of accounts can be found here https://dune.com/bh2smith/Locked-GNO-Snapshot)
2. Open Profile page
3. See how the cards are loaded

**AR**: cards are loaded one by one and 'jumping' on the page
Video: https://watch.screencastify.com/v/Nk5p38CfOwx6gNDZ758u

**ER**: add some kind of a loader/cards loading effect in order to avoid this jumping?

**Comment by anxolin** [comment]
@elena-zh , whats the difference between QA done and closed?

**Comment by elena-zh** [comment]
@anxolin , `QA Done` means that I have verified the task and finished testing. 
`Closed` - PR is merged to Dev/Release brunch/etc. 
I tried to describe the workflow [here ](https://docs.google.com/document/d/1MuRCRSF1OCtSFAZiyV0RIZsJ1i9oDPprBbNA9u0OQ8M/edit)

**Comment by anxolin** [comment]
I see, makes sense. I guess here i was wondering because the issue had a linked PR which was merged. But I think it was Github that didn't auto-close although Nenad wrote Fixes #492 in the description (they usually do it afait)

**Comment by elena-zh** [comment]
@anxolin , yes, GitHub does not auto-moves tasks to the `Closed `column from `QA Done.` 
Usually, I do it manually.
