### ISSUE TITLE
Uni merge: incorrect message appears when 'select token' is  displayed in the from field 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#504]
Related to #502 
**Steps**: 
1. Connect to a wallet
2. Open profile page
3. Press on the 'Buy COW' button

**AR**: Incorrect message appears when 'select token' is  displayed in the from field 
![image](https://user-images.githubusercontent.com/70885163/166442501-983d53ab-0f2b-4f2b-a006-2e56e1d55589.png)

**ER**: Here we should show 'Enter an amount' 
![image](https://user-images.githubusercontent.com/70885163/166442613-fcb06ddb-a3c9-4cea-97da-f274473d8321.png)

OR 'Select a token' messages
![image](https://user-images.githubusercontent.com/70885163/166442659-af7afa47-1cc6-4cff-814d-f8582e07da93.png)

**Comment by anxolin** [comment]
Good catch! it needs to be fixed
