### ISSUE TITLE
CSS broken on Limit Order

### ISSUE THREAD

**Issue by greenlucid** [cowprotocol/cowswap#5084]
**To reproduce:** 
1. Open Limit orders page
2. Connect to a wallet
3. Fill in a Sell token 
4. Pick a LP token that is currently not supported on the UI ( I picked 0xfcd125f4c5030137634863A2d3E5d6D89158f19C on Gnosis chain)
5. Start typing a price ---> you will get this screen

Cannot even click the X on the green popup
![image](https://github.com/user-attachments/assets/6ad44e66-078b-4bab-80ef-c08e737e83ed)

<img width="624" alt="image" src="https://github.com/user-attachments/assets/25466243-0bce-4ce0-929e-4803b59685b1">

**Comment by greenlucid** [comment]
Swapping the tokens out of order fixes the style. I'd guess the issue is that the symbol length of the token you're buying, was too long. The error only occurs when the long-symbol token is intended to be bought

**Comment by greenlucid** [comment]
Good catch, slightly different since that one is about typing in the field. I cannot reproduce it that way. Might be two different issues at the same time (unbounded size on the token picker, and unbounded size on the amount input form)

**Comment by elena-zh** [comment]
There are different ways to reproduce this issue, but in terms of the CSS the issue is the same: the UI expands on invalid price/quote. I've added steps to reproduce to the issue  description and will let the team know about it.
