### ISSUE TITLE
[1.89] Show a link to simulation result in the confirm modal 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#5095]
1. Open Hooks tab, connect to a wallet
2. Add any hook, specify a swap
3. Navigate to the Confirm modal

**AR**: simulation re-runs, but there is no link to a simulation report there
![image](https://github.com/user-attachments/assets/287e5ece-3022-44ee-acbb-c2ea31b09885)

**ER**: the link should be present

**Comment by yvesfracari** [comment]
This was already done on dev and was just not included on prod

<img width="598" alt="image" src="https://github.com/user-attachments/assets/c4969039-0d22-4565-9420-bfe72772b242">

**Comment by elena-zh** [comment]
@yvesfracari , yes, I can see it when I expand a hook details. Not so easy to quickly find it :(
Could you please add the link to a result label itself? 
![image](https://github.com/user-attachments/assets/09d102c8-c0c3-4059-9a5a-fb6445da2e07)
More or less similar as we do here: 
![image](https://github.com/user-attachments/assets/edb552ee-6c1e-4b9a-af5a-b4c8d59beb20)
