### ISSUE TITLE
[1.89] Improve loader for iFrame hook

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#5098]
Reported in https://cowservices.slack.com/archives/C07FQTUKLJC/p1731562193435739

While the iFrame is not loaded, we should put a spinner or something, cause the app remains blank for a while
![image](https://github.com/user-attachments/assets/41629723-62f7-4a69-998a-94779fcc6e4e)

Plus it would be great to hide the tooltip when a hook is opened (see it on the image above): reproducible when press on the question mark icon when adding a hook 
![image](https://github.com/user-attachments/assets/e1aa8e0c-05b4-4127-9513-216363718fb0)

**Comment by fairlighteth** [comment]
@elena-zh couldn't reproduce the second tooltip issue. Got a screen recording?

**Comment by elena-zh** [comment]
Hey @fairlighteth , here is the video for the second issue: https://www.loom.com/share/6a42a30a03c6482681d57a9cae653d57

**Comment by elena-zh** [comment]
Fixed
