### ISSUE TITLE
Signing onchain transactions in mobile MM/1Inch goes through opening the app in AppStore

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#510]
Related to #502

Originally reported in https://github.com/cowprotocol/cowswap/pull/444#issuecomment-1117143344

Some more context: https://github.com/cowprotocol/cowswap/pull/444#pullrequestreview-961025752

I see a request to open App store when I send a request to Approve a token using **MM**
![image](https://user-images.githubusercontent.com/70885163/166660742-969d6481-b98e-42ef-a476-d2110602ddc4.png)

However, I proceeded and opened the AppStore, then opened MM from there, and was able to sign the approve transactions. Afterwards I was redirected back to the app store. 
The same is for the warp/unwrap/convert transactions. 
Here is the video: https://drive.google.com/file/d/1jR5AuVWL0O-PMRuIPdQod5uc7AGR-Hm4/view?usp=sharing

The same is for the **1Inch wallet.** However, the CowSwap app page is changed to that one https://wallet.1inch.io/wc/, and transaction does not appear in the activity modal when go back to the Cowswap app.

**Comment by fairlighteth** [comment]
Hehe, nice music selection 🎶 ! 

So following the screen recording, it looks like:
- It brings you to the AppStore even though you already had MetaMask installed?
- When you click on OPEN in the AppStore, it opens your already installed MetaMask and you see the transaction signing request. When you sign, nothing seems to be signed/transmitted to the UI?

**Comment by elena-zh** [comment]
@fairlighteth , thanks=)

1. Yes, it opens AppStore even the app is already installed
2. When I sigh: 
 -  for **MM**: the Tx is signed, but I'm navigated back to the AppStore, and need 'manually' go back to the browser to open the  Cowswap app
 - for **1Inch**: the TX is signed, but nothing is transmitted to the UI

**Comment by elena-zh** [comment]
I have retested the issue in #502 PR and  I faced this intermediate message only once after connection a wallet in MM when testing in **iOS**. Then transactions started to run nicely with MM. 
As for the **1Inch** wallet, I always face an intermediate step when try to sign onchain transactions in **iOS**. However, transactions started to be visible in the Cowswap. 

in Android all types of transactions work fine for both 1Inch and MM wallets

**Comment by anxolin** [comment]
Apparently is a well know bug https://community.metamask.io/t/deeplink-opens-appstore-when-app-installed/18199/20 a bit sad

**Comment by anxolin** [comment]
Also a related issue, https://github.com/MetaMask/metamask-mobile/issues/3965 

They show there a workaround (https://github.com/MetaMask/metamask-mobile/issues/3965#issuecomment-1110690454), but we are not the ones generating the deep link (is Wallet connect), and second, there's someone that says that it doesn't work

**Comment by anxolin** [comment]
Also related issue, here they mentioned that is solved in MM 5.0.1, but for me it still reproduces.
https://github.com/MetaMask/metamask-mobile/issues/3914

Very annoying also that Uniswap uses web-react and they don't have this issue afait.

**Comment by anxolin** [comment]
Theres a few solutions suggested here https://github.com/MetaMask/metamask-mobile/issues/3965 @nenadV91 can you take a look?

**Comment by elena-zh** [comment]
No longer reproducible

**Comment by elena-zh** [comment]
Fixed in https://github.com/MetaMask/metamask-mobile/issues/3914#issuecomment-1497433197
