### ISSUE TITLE
[1.89] Post hook (vesting) does not include balance incrementation from a pre-hook

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#5100]
1. Open Hooks tab
2. Connect to a wallet
3. Add a pre-hook that will increment a token's balance
4. Specify a trade with a buy token with incremented balance
5. Add post-hook: create LLamapay vesting
6. Pick the last option (manually) and check the balance there

**AR**: it does not include balance incrementation from a pre-hook
![image](https://github.com/user-attachments/assets/601e21d3-42c5-484d-adbe-51f34c7ca413)
![image](https://github.com/user-attachments/assets/8021c10f-ddae-4dbd-bf54-4ccf9d6fbefb)

**ER**: it should include it.

**Comment by yvesfracari** [comment]
Hey Elena! Thanks for reporting this. I think this is solved now, can you test it again? Since this was related only to the hook dapp the changes are on [another repo](https://github.com/bleu/cow-hooks-dapps/commit/591c36131f0e05abc50123dbfe0609f6d091d5ff)

**Comment by yvesfracari** [comment]
cc @elena-zh
