### ISSUE TITLE
LlamaPay vesting hook: wrong token is picked in the hook's details

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#5122]
Reported in https://cowservices.slack.com/archives/C07FQTUKLJC/p1732192693171659?thread_ts=1732008214.772899&cid=C07FQTUKLJC

1. on Arbitrum, connect to a wallet
2. Go to the Hooks page
3. Specify a trade with USDC.e in the Buy field
4. OPen post-hooks and pick 'Create LlamaPay vesting hook'
5. Check a token there

**AR**: it is USDC
![token](https://github.com/user-attachments/assets/12e38f67-cbfe-431d-a4e7-deb5fe2e0dbb)
![wrong token](https://github.com/user-attachments/assets/149558e6-b027-4824-b68d-1215cee504e1)

**ER**: USDC.e should be displayed.

**Comment by yvesfracari** [comment]
It seems to me that this is an error on the CoW Token List since the token symbol is `USDC` on the contract https://arbiscan.io/token/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8#readProxyContract#F14

**Comment by elena-zh** [comment]
Thanks for clarification :)
