### ISSUE TITLE
'Hang in here..' message when switching back from an unsupported network to a supported one.

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#514]
Related to #502
Originally reported in https://github.com/cowprotocol/cowswap/pull/505#issuecomment-1117174921

 I have noticed that only in this PR I have started to see 'Hang in here..' message when switching back from an unsupported network to a supported one. 
![hang](https://user-images.githubusercontent.com/70885163/166667974-fc0eed61-45dd-459f-958a-f36a9dc77484.jpg)

Please, follow these steps to reproduce the issue: 
1. Connect a wallet to GC
2. Change to an aunsupported network
3. Change the networj to Ethereum --> you will see a hanging 'Hang in here' message

**Expected**: the price should be loaded

**Comment by alfetopito** [comment]
Short investigation I did so far:

1. Could not observe this locally, only when trying it out via the PR link
2. In my case, the error was thrown by Metamask, kinda breaking the blockchain connection in the app, thus causing the balances to not load rather than failing to load the prices
