### ISSUE TITLE
Uni merge: no toast notifications for onchain/offchain transactions

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#516]
Related to #502

Place an order
OR run a wrap/unwrap/approve/convert transaction

**AR**: there is no toast notifications when: 
 - order is placed
- order is executed
 - order is cancelled
 - order is expired
 - token is concerted
 - token is wrapped
 - token is unwrapped
 - token is approved

**ER**: toast notifications should be displayed.

**Comment by alfetopito** [comment]
After bisecting it, found where it started to break `c811fc5776c6deb2e66565fcc717ac4a3d51bdd0`

![Screen Shot 2022-05-05 at 11 21 19](https://user-images.githubusercontent.com/43217/166904894-a7227a50-e4c9-4c11-933f-fa42381b0c76.png)

**Comment by alfetopito** [comment]
To be more precise, there was a bad merge that removed the pop up component https://github.com/cowprotocol/cowswap/pull/484/commits/7c016a67ea69bb5fb390ab8b6ec6eaff69019b6d
