### ISSUE TITLE
limit buy order shows funky incorrect numbers + add example with USDC limit buy to the Docs

### ISSUE THREAD

**Issue by BillionShields** [cowprotocol/cowswap#5163]
Go to limit orders
Select Sell USDC $100
select buy coin i.e JASMY
set limit order amount
hit the round button to switch from USDC to Jasmy
See error - only receives 1.59 jasmy for $100
this is incorrect I should get like 2K jasmy 
Screenshot: 
![GeCZolLWkAA5fD8](https://github.com/user-attachments/assets/7fc2949f-f1ab-4787-92d7-34edb500a43e)

also add clear buy limit order example to the documentation section Limit Orders. Current does not have example of buy limit. only sell limit

**Comment by elena-zh** [comment]
Replied on [Discord ](https://discord.com/channels/869166959739170836/869170356383002625/1314526364858056747)

**Comment by Athensmo** [comment]
Hello @BillionShields 
have you resolve this issue yet?
