### ISSUE TITLE
[1.93]Weird APR for CoW AMM pools

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#5183]
Reported in https://cowservices.slack.com/archives/C07FQTUKLJC/p1733916000785899

1. Connect to a wallet
2. Open Hooks store
3. Specify a trade 
4. Add 'CoW AMM Deposit' hook --> check the APR data in the list of hooks

**AR**: it shows a wring value
![image](https://github.com/user-attachments/assets/bbe9646f-8a7a-4bcb-9f26-fd6914c541cb)
![image](https://github.com/user-attachments/assets/794c56d8-1ff8-4dd8-9282-c6cc8ce2e3b1)

**ER**: value should match the one is displayed on Balancer UI

Additionally, could you please remove this message from the 'No results found' screen? 
![image](https://github.com/user-attachments/assets/df1963ac-ebf6-4cce-8b17-f0ec07152837)

**Comment by yvesfracari** [comment]
Thanks for reporting @elena-zh ! Now it should be fixed.

<img width="445" alt="image" src="https://github.com/user-attachments/assets/880c4129-005f-4394-921c-ca40e5710664" />
<img width="598" alt="image" src="https://github.com/user-attachments/assets/097252bf-1ec7-434e-b935-e7dfb2550200" />
<img width="520" alt="image" src="https://github.com/user-attachments/assets/c6cc8b39-e3e7-4ce3-a54e-1fef704316fd" />

**Comment by elena-zh** [comment]
Looks good now, thank you!
