### ISSUE TITLE
Make seasonal background picture configurable

### ISSUE THREAD

**Issue by tjwelde** [cowprotocol/cowswap#5247]
**Description**
The currently added seasonal background picture is visible as a blue background and can't be removed:
![image](https://github.com/user-attachments/assets/9369b8b8-5b7e-40a2-8728-cb66cc259c9c)

**Proposal**
Either don't add a background image to embedded cowswap widgets, or make it configurable

**Alternatives**
Since the widget renders an iframe, that runs on a different domain, than our site, there is not much we can do on our side.

**Comment by elena-zh** [comment]
Hey @tjwelde , thank you for bringing up this issue. It has been fixed. Please check it from your side.

**Comment by tjwelde** [comment]
Looks good, thanks
