### ISSUE TITLE
Cowgame: Alternating dark and light mode

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#53]
**Description**
The dark and light mode alternate when jumping. 
Happens if you change the mode after opening the game. 
Stops once you clicked anywhere on the screen with the mouse

https://user-images.githubusercontent.com/34510341/124590120-145d9680-de5b-11eb-8289-c945d18e7b2a.mov

> Original issue https://github.com/gnosis/cowswap/issues/868 by @MareenG

**Comment by elena-zh** [comment]
No longer reproducible
