### ISSUE TITLE
[1.14]'Injected' wallet appears when disable MM extension

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#537]
1. Disable MM extension in the browser
2. Disable Coinbase extension in the browser
3. Open Cowswap app, press on the Connect to a wallet

**AR**: 'Injected' wallet appears. Nothing happens when press on it (A request to connect a wallet is sent, but I can't know what wallet it is connecting). 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3fdd45be-9a4d-44c5-8b08-3217a8e3887e)

**ER**: 'Install Metamask' button should be displayed. Should navigate to metamask.io

**Comment by nenadV91** [comment]
I wasn't able to reproduce this issue, this is what I see when I disable the MM
![Screenshot from 2022-05-23 15-05-31](https://user-images.githubusercontent.com/34926005/169826005-8ae2945c-edf2-4de5-afdd-38b1021bc165.png)

**Comment by nenadV91** [comment]
@elena-zh When you see this please check again if you can reproduce this.

**Comment by elena-zh** [comment]
@nenadV91 , I can reproduce this issue. Please, see the video: https://watch.screencastify.com/v/muIAYXnC683J9ct3MfUH

**Comment by elena-zh** [comment]
The issue is still reproducible to me in 1.16v in Chrome (Version 103.0.5060.53 (Official Build) (64-bit))
![image](https://user-images.githubusercontent.com/70885163/175938917-de606410-c8e1-457a-aac6-141e9d145ba4.png)

**Comment by elena-zh** [comment]
The issue is also reproducible ('Injected' does not connect to any wallet) when install any injected wallet extension to the Chrome (Coinbase/Frame). 
![image](https://user-images.githubusercontent.com/70885163/175940483-7e5f2ef9-efa0-44f5-ae3f-b3c337ef2884.png)

**Comment by elena-zh** [comment]
So, exact steps to reproduce the issue: 
1. Install Coinbase extension to the browser, disable it
2. Install MM extension to the browser, disable it
3. Open Cowswap app, reload the page
4. Press on the 'Connect to a wallet' button
