### ISSUE TITLE
[1.14] Not connected user is navigated to the Mainnet when refreshes the page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#540]
1. Open the app as a not connected user
2. Select Gnosis Chain
3. Go to the Profile page and press on the Buy Cow button
4. Refresh the page

**AR**: network is changed to Mainnet, To field is empty
![disconnected.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3f28d2f8-6346-45f0-82a7-051dbb1a903c)
Video: https://watch.screencastify.com/v/tjoxsRNhIWsWfysz0EM7

**ER**: user is connected to GC, To field = COW

**Comment by alfetopito** [comment]
But eventually it goes back to gchain, doesn't it?
That's what I understood from your video

**Comment by anxolin** [comment]
Yes, probably can be improved because if we refresh, the gnosis_chain was a param that is present in the URL, so we shouldn't default to main-net in this case

**Comment by elena-zh** [comment]
@alfetopito , more than often it is does not comes back. 
I'd say, it is a rare case when the chain goes back to the GC
