### ISSUE TITLE
[Token list] add a notification to connect a wallet when adding a custom token

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#55]
Currently, nothing happens when a not connected user tries to add a custom token. User does not see any warning/token is not added, etc. 
It would be nice to add a notification to connect a wallet when adding a custom token to make it a bit understandable to a user what is going wrong there
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e61f1421-5ac4-494b-a253-4b1e8bb44356)

> Original issue https://github.com/gnosis/cowswap/issues/889 by @elena-zh

**Comment by elena-zh** [comment]
Fixed
