### ISSUE TITLE
Referral address is not removed from local storage after successful trade

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#554]
1. Share a referral link
2. Connect to a wallet (in my case I connected to ledger live) with an account with no trades on Mainnet
3. Place a successful order

**AR**: referral address is not removed from the local storage. It remains flashing there. See the video: https://watch.screencastify.com/v/x8ZEpRYNIpNYIj6ZG3AL

**ER**: referral address is removed from the local storage after a successful trade

**Comment by anxolin** [comment]
Not only should be removed but also a user who already has trades imo shouldn't see the message. They are not eligible if they traded before

**Comment by elena-zh** [comment]
Hey @anxolin , 
> Not only should be removed but also a user who already has trades imo shouldn't see the message. They are not eligible if they traded before

It is true. And the message is not displayed for users who have traded before (works fine now). 
This issue affects cases (banner appears again): 
 - when switch to an unsupported network
 - when disconnect a wallet
 - when switch to an account that has not traded before
 - when switch to an account that is a referral link owner.

**Comment by elena-zh** [comment]
No longer relevant as the affiliate section is removed
