### ISSUE TITLE
Integrate SDK with CowSwap

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#563]
Now there's an official SDK, we start to have some duplicated logics.

This task is for moving all our basic logics into the SDK. We already have some nice methods to query and sign orders. We would need to review what is missing, and progressible make our logics in CowSwap thinner, so other apps can use them too from the SDK.

For now we decided to not move any hook to the SDK. We might do some other project in the future for this, or we might reconsider. For now we are starting with moving our main logics

**Comment by W3stside** [comment]
1 PR to add:
- Paraswap in isolation
- 0x in isolation
1 PR to add:
- utils for best price race
- utils for fastest price

**Comment by elena-zh** [comment]
Closed in favour of #2043
