### ISSUE TITLE
Analytics: Add slippage tolerance settings to analytics

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#565]
Since we are implementing some changes to the slippage tolerance, this will be a good opportunity to take more metrics.

We could track how often users change the slippage tolerance, and what are the most common values. This could also be relevant for the funnel if we filter by the selected slippage tolerance.

- [ ] Send event to analytics when user changes the default slippage settings

**Comment by W3stside** [comment]
done in PR #590
