### ISSUE TITLE
CowSwap keeps Metamask connection even when opening as Safe App

### ISSUE THREAD

**Issue by dasanra** [cowprotocol/cowswap#580]
**Description**
Currently we added CowSwap as a Safe App in the default list. It happen that many users already used CowSwap directly with Metamask or other accounts. When they want to use it with a Safe they find that the Safe App still connects to their Metamask instead to the Safe, which makes it unusable as Safe App without reseting the local storage.

**How to Reproduce**
1. Go to CowSwap and connect a Metamask account
2. Then go to the Safe and connect the same Metamask account to the Safe
3. Open CowSwap as a Safe App
4. Your Metamask will be picked. There is no way of easy disconnecting, which makes the Safe App unusable.

**Expected behavior**
If it's run as a Safe App it should discard previous wallet session and allow the Safe to connect

**Comment by elena-zh** [comment]
I'm reopening the issue as it appears to be reproducible again 
![safe-mm](https://user-images.githubusercontent.com/70885163/182591842-3a5f866a-1449-48c4-9045-8a72b33c5309.jpg)

**Comment by elena-zh** [comment]
Some additional context: 
1. When I load the safe, Safe balances are displayed
2. Then I go to the Desktop Cowswap, place an order there and sign it by Safe ownver's MM account
3. I go back to the Safe, reload it and see MM account balances+pending TX there
4. When TX is executed, I reoad Safe app, and Safe shows its balances correctly
