### ISSUE TITLE
Setup new swap.cow.fi

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#582]
https://docs.google.com/document/d/1XMMWeMhxFUsSmCOD8W7TrtxhZaL3U2CRGlAmmpMo_BI/edit#

**Comment by Yikes667** [comment]
> - [ ] Create all domains under cow.fi
> 
> - [ ] Setup analytics
> 
> - [ ] Google console
> 
>    - [ ] Setup
> 
>    - [ ] Migrate/Redirect old site to new one
> 
> - [ ] Fix links in:
> 
>    - [ ] Dev Docs
> 
>    - [ ] cow.fi
> 
>    - [ ] CowSwap
> 
> - [ ] Good to have: Create site for the static content of cowswap, or move to the landing
> 
> 
> 
> i.e. How to Migrate/Redirect old site to new one
> 
> 
> 
> <img width="1329" alt="image" src="https://user-images.githubusercontent.com/2352112/170855537-87f8ac90-62c6-4bfa-8c82-6e42593e2ce0.png">
> 
>
