### ISSUE TITLE
'Switch to WETH' appears for a couple of secs before 'Insufficient ETH balance' message

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#61]
1. Open the app and select ETH token to swap
2. Select 'To' token
3. Enter an amount of ETH token > than in the balance

**Actual Result**: 'Switch to WETH' appears for a couple of secs before 'Insufficient ETH balance' message
https://drive.google.com/file/d/1V_Zx1lPskc3oL-PQsrndRVWuWgJ5AQ14/view

**Expected result:**  'Insufficient ETH balance' should be displayed

> Original issue https://github.com/gnosis/cowswap/issues/926 by @elena-zh

**Comment by anxolin** [comment]
Probably irrelevant after implementing #418

**Comment by elena-zh** [comment]
No longer reproducible
