### ISSUE TITLE
Progress bar iteration 2

### ISSUE THREAD

**Issue by alongoni** [cowprotocol/cowswap#615]
## Context:
After some UX sessions, we conclude that the progress bar it's hard to find in the activity modal. Anxo made a proposal to move the progress bar to the "Transaction Submitted" modal.

## Background
https://github.com/cowprotocol/cowswap/pull/609
https://www.figma.com/file/VCL4fDZiaKkCV5lPU65Kvp/Progress-Bar-reiteration?node-id=0%3A1
https://github.com/gnosis/cowswap/issues/1946

**Comment by alongoni** [comment]
I've added a design (still a draft) for the modal "Transaction submitted" in order to include the progress bar component. Still I've some doubts about showing the cow game access, the quiz, etc. Let's discuss it later.
https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=4988%3A1446
![image](https://user-images.githubusercontent.com/622217/171532443-c1ac8d8d-c8fb-44e8-97eb-f251ee07d5ac.png)

@anxolin @MindyCoW @ramirotw

**Comment by alongoni** [comment]
v3.1
https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=5044%3A90
![v3 1](https://user-images.githubusercontent.com/622217/171960943-88452623-0cb3-42e4-b199-91352416c500.png)

**Comment by elena-zh** [comment]
Hey @alongoni , new iteration of a progress bar looks awesome!

But I'd like to  propose another enhancement for this flow: it might happen, that a user can close 'Transaction in Progress' modal (by clicking outside its area/navigating to the CowGame page/etc.)

So I have an idea to show an info pop-up something like 'You can still track the order progress in the Activity modal'  or so with OK button when closing the pop-up. In this case, user will be able to open the Activity modal and see the progress bar there. 

We could also add 'Do not show this message again' box at the bottom of the modal in order not to annoy users with lots of modals in the future. 

@anxolin , @MindyCoW , @alfetopito , WDYT?

Thanks

**Comment by alongoni** [comment]
> Hey @alongoni , new iteration of a progress bar looks awesome!
🤙
> 
> But I'd like to propose another enhancement for this flow: it might happen, that a user can close 'Transaction in Progress' modal (by clicking outside its area/navigating to the CowGame page/etc.)
> 
> So I have an idea to show an info pop-up something like 'You can still track the order progress in the Activity modal' or so with OK button when closing the pop-up. In this case, user will be able to open the Activity modal and see the progress bar there.

Hey @elena-z. You are right! Thanks!
There is an idea to show a tooltip beside the Pending button (Activity Modal) when a user close the 'Transaction in progress' modal or open the CowGame. 
![image](https://user-images.githubusercontent.com/622217/173577242-87f41c48-7d21-410d-8e67-5c85895c32d6.png)

I think the tooltip it's more precise in order to point specifically what part of the UI will opened the Activity modal.

Another deprecated idea was showing a box with a message referring to the pending button in the header.
![image](https://user-images.githubusercontent.com/622217/173578578-e8687c0f-5568-4aa7-bf73-45990f711315.png)

> We could also add 'Do not show this message again' box at the bottom of the modal in order not to annoy users with lots of modals in the future.

I like this! We can add it at the botton of the tooltip.

Thanks!!
> 
> @anxolin , @MindyCoW , @alfetopito , WDYT?
> 
> Thanks

**Comment by elena-zh** [comment]
Hey, I have another question: will we show the progress bar on the order confirmation modal after signing an order in SC wallet? 
Maybe we should add an additional step there ('signing') with an appropriate explanation for it? @alfetopito , @anxolin , @alongoni  WDYT?
