### ISSUE TITLE
'Insufficient WETH balance' when WETH amount = balance in the wallet

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#62]
It might be an exceptional case.
Reproducible on Prod/Staging in xDAI, Mainnet and Rinkeby.

**Steps:** 

1. select ETH token on the From field
2. select WETH token in the To field
3. specify ETH amount = WETH token balance
4. swap tokens in the From/To fields

**Actual Result:** Insufficient WETH balance is displayed
https://drive.google.com/file/d/18a4_0JB6MNKve___HWTs7OOzlo5JHGCM/view
![xdai](https://user-images.githubusercontent.com/70885163/125611696-feedc9fc-e715-40b9-96b0-6ffc11a0e5e6.jpg)

**Expected Result:** User is able to place an order

> Original issue https://github.com/gnosis/cowswap/issues/928 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
