### ISSUE TITLE
Show COW discount in the cofirmation modal

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#625]
**Description**

We show the fee discount of the trade:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/2352112/171840853-8dab2ab9-000c-455f-86fd-88b02cbf4333.png">

However, we don't show it in the confirmation modal

<img width="832" alt="image" src="https://user-images.githubusercontent.com/2352112/171840810-3d97a806-6a6e-45c3-94e9-28e2dede7a55.png">

One small difficulty we will face, is that if we click it we will show another modal. So we might need to review how we deal with this.
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/2352112/171841022-0dc3ba76-d171-437b-9da7-a30e589f5045.png">

**Comment by elena-zh** [comment]
Fee discounts were removed
