### ISSUE TITLE
The app is not adjusted to the whole screen width in iOS in the landscape mode

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#63]
The app is not adjusted to the whole screen width in iOS in the landscape mode: white boarders are displayed from the right and left corners
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ddcc7fd6-2515-4c93-82bc-bbd3bd3748f6)

**Expected**: adjust the app  to the whole screen width 
Or make boarders black at least in a dark mode (I'm not sure if it is possible)

> Original issue https://github.com/gnosis/cowswap/issues/932 by @elena-zh

**Comment by elena-zh** [comment]
The issue is relevant for the light mode only.
