### ISSUE TITLE
[1.15] Change TX rejection messages for Claim/Convert tokens transactions

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#646]
As mentioned in the #630 PR, a rejection message for orders signing is changed. It would be great to change the message when cancelling signing Claim/Convert transactions
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ea6daff8-2158-4b5b-86d3-ee1c0bc54958)

To: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a4045c3b-7f9e-40b1-9d0a-ac0bccd2ed8b)

**Comment by W3stside** [comment]
how can you even claim anymore isnt that over? 😓

**Comment by elena-zh** [comment]
Partially fixed in #655 
The 2nd part will be fixed in #665
