### ISSUE TITLE
Max button is not displayed when XDAI/ETH  balance is too low

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#65]
1. Select ETH/XDAI  token in the 'From' field when its amount in a connected wallet is <0.0001

**Actual Result:** No Max button
![image](https://user-images.githubusercontent.com/70885163/127839323-017f0ce2-924d-4644-9a69-9aa59238fa92.png)

**Expected Result:** Max button should present

> Original issue https://github.com/gnosis/cowswap/issues/934 by @elena-zh

**Comment by elena-zh** [comment]
No longer reproducible
