### ISSUE TITLE
On revoke of a token allowance, this isn't properly picked up.

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#66]
Browser: Brave
Web version: v0.16.0

- Revoke allowance for a token https://etherscan.io/tokenapprovalchecker (e.g. GNO)
- Go to CowSwap where I select GNO ( I've got balance).
- It doesn't ask me to approve the token again.
- If I continue, it shows me:
<img width="501" alt="Screen Shot 2021-07-16 at 16 42 31" src="https://user-images.githubusercontent.com/31534717/125972469-15c8c6fe-7224-47f0-85fd-b6d71d2d1820.png">

## Notes
- Refreshing/cleaning local storage doesn't help.
- If you play with the TO input amounts, switch tokens around, etc. Sometimes it does come up briefly. Then disappears again.

> Original issue https://github.com/gnosis/cowswap/issues/954 by @fairlighteth

**Comment by elena-zh** [comment]
I can't reproduce this issue
