### ISSUE TITLE
Analytics follow ups - PRIOS

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#665]
**Description**

Improve some issues with the new analytics, and add some additional events:

ASAP:
- [X] Refactor 1: https://github.com/cowprotocol/cowswap/pull/696
- [X] Refactor 2: https://github.com/cowprotocol/cowswap/pull/714
- [x] Emit event when we show the warning of: Order out of Market. Also emit when the order comes back to market price
- [x] Funnel
   - [x] Load first price estimation
   - [x] Change input token, output token, amount

Next
- [x] Add new dimension: Wallet

Next
   - [ ] **Approve Workflow**: Hanging approving (Wallet Connect) https://github.com/cowprotocol/cowswap/pull/660#issuecomment-1150025142 

Next:
- [ ] Post-conversion (or post-submittal) actions
      -[x] Play the game
      -[ ] Click(s) on explanations of status messages (needs clarification)
      -[x] Add token to Metamask from the Submitted modal
      -[x] View on Explorer (via Submitted modal or toast notif) / Batch Viewer

Next:
- [ ] **Reject Claim COW for locked GNO**: Incorrect event for Rejecting TX (Wallet Connect) https://github.com/cowprotocol/cowswap/pull/658#issuecomment-1150010118
- [ ] **Reject for unwrap/wrap/claim transactions using WC wallet, I still see 'Error signing' GA event instead of 'Reject' https://github.com/cowprotocol/cowswap/pull/655#issuecomment-1149771629

- [ ] https://github.com/cowprotocol/cowswap/issues/661
- [ ] https://github.com/cowprotocol/cowswap/issues/638
- [ ] https://github.com/cowprotocol/cowswap/issues/639 ?
- [ ] When reject signing order with SC wallet (Safe), it shows an incorrect GA event (Error signing instead of Reject)

Follow up
- [ ] Both the approve token and the wrap have hooks which don't handle displaying error in case of an error (or rejection)
- [ ] Split Cancelation events: https://github.com/cowprotocol/cowswap/pull/631#issuecomment-1148460745
- [ ] Review TODO events and add them to this list https://docs.google.com/spreadsheets/d/1AwcuvmPaAyIRuKayOEp1cKcVGD3MLOpfS8UWA04fBtY/edit#gid=0
- [ ] Abstract the use of analytics behind a utils. Refactor all `reportAnalytics` methods
- [ ] Add alternative analytics (depend on the abstracting)
- [ ] Reitetate after trying to do the funnel, I'm sure we will have other requirements based on our first experiences

**Comment by elena-zh** [comment]
@anxolin , could you please take a look and include these issues into the scope of the task: 
 - #638 
 - #639 ?

**Comment by anxolin** [comment]
Incredible! for the Wallet Connect issues, i saw that if I reject the transaction in Metamask IOS app for the approval, the Wallet never notifies my back!

This is specially weird because they do for Wrapping/Unwraping ETH and EIP712 signings!

**Comment by elena-zh** [comment]
Yes, too odd issue

**Comment by anxolin** [comment]
Just adding this for context, Metamask team is reviewing it https://github.com/MetaMask/metamask-mobile/issues/4482

**Comment by nenadV91** [comment]
@anxolin I'm not sure what this refers to `Click(s) on explanations of status messages`, could you clarify?
