### ISSUE TITLE
'Insufficient liquidity' error when select ENS name in the recipient field

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#667]
1. Open Swap form and connect to  a wallet
2. Switch Toggle recipient ON in the settings
3. Specify a token pair, and amount to trade
4. Expand Recipient field and fill it in with a valid ENS name
5. Wait till the next quote/price update

**AR**: 'Insufficient liquidity' error appears, impossible to trade

**ER**: no error after a quote/price update

**Comment by anxolin** [comment]
Adding more context. @nenadV91  https://cowservices.slack.com/archives/C0361CDG8GP/p1653897648653779
