### ISSUE TITLE
[1.15] Price out of range message appears right after placing the order

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#674]
1. Open the app
2. Place a sell/but order in the Mainnet
3. Open activity modal 

**AR**: Price out of range message appears right after placing the order. The the message disappears in 30 sec, the order is traded
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6fe2c158-2815-4671-8089-60713c74689c)

**ER**: the message does not appear if the price is OK

Note: orders in GC work fine.

**Comment by elena-zh** [comment]
Today I'm able to reproduce the issue 
![image](https://user-images.githubusercontent.com/70885163/173816546-5c6d0eb0-249d-423b-8532-459363fb8465.png)

**Comment by elena-zh** [comment]
I have placed 3 orders, and have faced this message for every order
https://explorer.cow.fi/address/0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d
![image](https://user-images.githubusercontent.com/70885163/173817598-ee3452e3-e0d5-4ba2-8fc2-1137734f2a5b.png)

**Comment by elena-zh** [comment]
Since we implemented an order execution progress bar in #609 , this issue has become more visible now: users can see 'out of market' state right after placing an order on the order confirmation modal
![from beg](https://user-images.githubusercontent.com/70885163/178673451-58cef330-8629-4377-a8ee-1ac7d9608c86.jpg)

I have to notice, that the order has been traded in 1 minute.

**Comment by alfetopito** [comment]
I debugged this for awhile on rinkeby and my assumption so far is this:

1. The fee impacts the prices
2. Smaller amounts are more impacted by the fee
3. Prices can move from one moment to the next due to gas price changes rather than real price movements

This would be more easily observed in environments where the fee is high and more volatile ==> mainnet
Smaller orders with tighter slippage also are more prone to being out of market.

Will try to test my assumptions on mainnet

**Comment by elena-zh** [comment]
Hey @alfetopito , I can share with you an account where each order I place gets 'Price out of market' message right after submission. I believe, it might help you to debug the issue on Mainnet
![image](https://user-images.githubusercontent.com/70885163/184333900-12ecfee9-9517-454f-a479-e9595e12a900.png)

**Comment by alfetopito** [comment]
Thanks Elena!
I'll reach out to you when I get back to this issue.
