### ISSUE TITLE
CowGame: endgame sound is playing in a minute when the game runs in the background

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#68]
Reproducible in Prod/Staging/Dev

1. Run the game
2. Switch to the Swap form
3. Wait for a 1 minute
4. select any token in the From list 

**Actual Result:**  endgame sound is playing

**Expected Result:** no endgame sound

> Original issue https://github.com/gnosis/cowswap/issues/986 by @elena-zh

**Comment by elena-zh** [comment]
The issue is still reproducible, but I will close the issue since no one has complaint on it for more than 2 years.
