### ISSUE TITLE
Pinpoint where in 1.15.0 ETH USD price and impact broke

### ISSUE THREAD

**Issue by W3stside** [cowprotocol/cowswap#736]
related to [the postmortem doc](https://docs.google.com/document/d/1SfKDvGBRQFLScEoiQ3V2aGXG9ktIIaJ3WkIm_oghG9g/edit#) - we need to find where exactly the USD/impact logic failed in 1.15.0 vs 1.14.2

**Comment by W3stside** [comment]
Before version `v1.15.0`, the fallback CoW API price response for ETH was always `null` due to a bug outlined below. 
The fix, introduced in `v1.15.0`, fixed the bug in the fallback CoW API, albeit now with the `feeAmount + sellAmount` bug (which was subsequently fixed in `v1.15.5`)

### Breakdown:
`v1.14.2` was NOT showing this because the fallback cow source was always failing, thus:
1. Coingecko -- FAILS 
2. fallback to CoW API
3. CoW API -- FAILS
4. fallback to ABA

`v1.15.0`- fix the fallback CoW API
1. Coingecko -- FAILS 
2. fallback to CoW API
3. CoW API -- returns bad price with `feeAmount + sellAmount` bug
4. Show bad impact

[This commit](https://github.com/cowprotocol/cowswap/commit/4f57bf4b6e91bd80abbe83e1231e3d3c436831fc) is the PR that changed a key bug in the `useUSDCPrice` logic - it was first seen in prod in `v1.15.0` as seen from this screenshot (and in the link)
<img width="946" alt="image" src="https://user-images.githubusercontent.com/21335563/175085463-940b743f-15d7-43c6-8b72-28258f7048d0.png">

the relevant code change [is here](https://github.com/cowprotocol/cowswap/blob/4f57bf4b6e91bd80abbe83e1231e3d3c436831fc/src/custom/hooks/useUSDCPrice/index.ts#L136) which was improperly creating a `Currency` object, which, when passed to the `Price` api, was [failing silently](https://github.com/cowprotocol/cowswap/blob/4f57bf4b6e91bd80abbe83e1231e3d3c436831fc/src/custom/hooks/useUSDCPrice/index.ts#L175) (`TOKEN_INVARIANT` error from Uniswap's sdk)

**Comment by anxolin** [comment]
Good detective work!

This sounds like it, thanks for researching this aspect. I believe when these things happen is not only important to fix it, but also understand all the chain errors. I'm happy with the outcome because out of the investigation you already found 4 contributors to the chain of events:
- ETH param in coinbase
- cache issue in SWR
- Fee applied for USD estimations
- Now this SDK error

Of these 4, I understand the first 3 you already fixed and don't need further actions. Now my follow up question is, for this last SDK error, did it show in Sentry?

**Comment by W3stside** [comment]
> Of these 4, I understand the first 3 you already fixed and don't need further actions. Now my follow up question is, for this last SDK error, did it show in Sentry?

No :( because it was being dropped in the catch block

**Comment by anxolin** [comment]
@W3stside can we close?

**Comment by elena-zh** [comment]
@W3stside , is the task still relevant? 
If not, can we close it?

**Comment by elena-zh** [comment]
Hey @W3stside , can we close this?

**Comment by W3stside** [comment]
sorry, yes!!
