### ISSUE TITLE
Error in console when switch networks

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#74]
Trivial priority. 
Error appears on the network change action and does not affect anything

Anyways, I'd better report this issue.

1. Connect a wallet
2. Change a network to any supported one

**AR**:  Error in console is displayed
![switch networks.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/eb0b2cf7-9a91-457d-bfd9-28cec6855ecd)

**ER**: no error

> Original issue https://github.com/gnosis/cowswap/issues/1030 by @elena-zh

**Comment by anxolin** [comment]
Does it fail also in Uni?

**Comment by elena-zh** [comment]
@anxolin , I do not see this exact error in Uni merge. 
However, I see a lot of different errors (console is fully in red)
![image](https://user-images.githubusercontent.com/70885163/166421635-416fbf66-5264-4fe0-877a-8cffe8e23381.png)
![image](https://user-images.githubusercontent.com/70885163/166421744-abe60187-b40b-46b6-b1d4-ff3217834699.png)
![image](https://user-images.githubusercontent.com/70885163/166421774-d9c5ebed-e78b-4b7b-b02a-a8b9d615f05e.png)
![image](https://user-images.githubusercontent.com/70885163/166421818-79a2a9b9-5d6b-4ce3-9f5a-ca006eeb364b.png)
![image](https://user-images.githubusercontent.com/70885163/166421982-9ea217da-e6c7-49be-87ed-285553b12bda.png)

**Comment by elena-zh** [comment]
no longer reproducible
