### ISSUE TITLE
Quote requests for WETH/USDC token pair are sent when WETH/ETH token pair is selected

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#743]
1. Open the app
2. Select WETH/ETH token pair
3. Open Console-Ntwork tab
4. Filter by 'quote'
5. Check requests

**AR**: Quote requests for WETH/USDC token pair are sent in the bg when WETH/ETH token pair is selected
![bg quotes.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a25a00d5-596e-4ccb-972c-e513788c5cd9)
**ER**: no requests

**Comment by W3stside** [comment]
Why do you expect no results? The usdc WETH request is the fall back USD price request

**Comment by elena-zh** [comment]
No longer relevant in v.1.21
