### ISSUE TITLE
Disable 'Change' button in a wallet integrated browser

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#75]
The issue is related to next wallets: 
1. MetaMask
2. imToken
3. TrustWallet 
4. TokenPocket

When I open the app in an integrated browser, the app requires an immediate connection. 
Other connection options are not available there. Hence, when i press on the 'Change' button, I see  only 'Terms and conditions' disclaimer in the connection modal. 

It would be nice to disable 'Change' button for these cases.
https://images.zenhubusercontent.com/192335743/f1b532d6-c1f8-42dd-b8c1-628add11590b/skype_video.mp4

![image](https://user-images.githubusercontent.com/70885163/134157944-d5c63810-8f98-4fa7-bde6-35a1f9949344.png)
![image](https://user-images.githubusercontent.com/70885163/134157980-0d26ef0f-917d-4047-8b42-f485156fbfb5.png)

> Original issue https://github.com/gnosis/cowswap/issues/1034 by @elena-zh

**Comment by elena-zh** [comment]
Fixed in 1.21.0
