### ISSUE TITLE
Feedback NPS

### ISSUE THREAD

**Issue by alongoni** [cowprotocol/cowswap#760]
Add a form to collect feedback based on NPS (Net Promoter Score)

**Appzi | Typeform comparison**
https://docs.google.com/document/d/1_lnztKGrRNoVNNZ4lGXmYIX-Bm-wArzJDlHS1WHXkUs/edit
Advantages of Appzi: Better NPS results visualization, more options for targeting users
Advantage of Typeform: Ability to embed NPS in the UI, which Appzi doesn’t offer

**Questions to show:**
https://docs.google.com/document/d/1lQwuISnSNHADiYhuL5JNolX-mJg9OSQeU4pAGLvxXYY/edit

**Display policy (WIP):**
- once per week/month/any other period to an account
- to a new user after the 1st successful order
- users who had not placed orders for a long time (f.e. for 1 month), then placed

**Other information/resources:**
https://github.com/Typeform/embed

**Comment by alongoni** [comment]
Here are some design options / ideas:
1. Feedback box on the Transaction modal after a successful trade:
![feeedback-1-1](https://user-images.githubusercontent.com/622217/176552916-55033cf4-c835-43c5-8c36-4cfbc1e713f7.png)
![feeedback-1](https://user-images.githubusercontent.com/622217/176552919-ecddd9dc-1508-4cfd-82ef-e83dd6afcc94.png)

2. Feedback box on popover after a successful trade:
![nps-2](https://user-images.githubusercontent.com/622217/176552933-fe5bec7e-b150-49c9-b856-9f278445816a.png)

**Comment by elena-zh** [comment]
I'd vote for the 2nd option.
Moreover, an order confirmation modal does not appear when a user is in Expert mode, so there is no way to show the feedback form in this case.

**Comment by alongoni** [comment]
Hey @elena-zh. Also I'm a bit in favor with 2nd option.
Another option here:
![image](https://user-images.githubusercontent.com/622217/176676860-ecbef3e1-8d97-43db-84ca-aff144201566.png)

**Comment by alfetopito** [comment]
Loved the last one with the cow in the slider.

As I mentioned during our last sync, I believe the pop-up is a better fit for a number of reasons:

1. Expert users don't see the modal
2. The user might close the modal and won't get to see the feedback request
