### ISSUE TITLE
Sentry shows 'Insufficient liquidity' error instead of 'Unsupported token' 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#763]
I noticed that sometimes Sentry shows 'Insufficient liquidity' error instead of 'Unsupported token' 

**To reproduce:** 
1. Connect to GC
2. Select wxDAI-ADAI token pair
3. Check sentry logs

**AR**: Sentry shows 'Insufficient liquidity' error
https://sentry.io/organizations/cowprotocol/issues/3141100910/?environment=staging&project=5905822&query=is%3Aunresolved&statsPeriod=1h

![insuff liq.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/694b0b23-641b-4471-81f1-fa6b5098e6b2)![insuff liqq.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a90d5f42-995d-49c7-96e2-93a01bd3b0e6)

**ER**: Sentry shows 'Unsupported token' error

**Comment by W3stside** [comment]
@elena-zh i don't have ADAI showing as unsupported in CS - is this really an unsupported token? can anyone else confirm? @cowprotocol/frontend

**Comment by alfetopito** [comment]
Testing staging (https://cowswap.staging.gnosisdev.com/#/swap?chain=gnosis_chain) I get insufficient liquidity, not unsupported token

![Screen Shot 2022-07-01 at 10 46 38](https://user-images.githubusercontent.com/43217/176870831-ede21a45-dfa7-4486-ae50-6f31dd859c87.png)

**Comment by elena-zh** [comment]
Yes, I can see 'Insufficient liquidity' error now as well. 
So, it might be  cache issue then, as until Thursday ADAI was always an unsupported token for GC (to prove it, see the #644 issue description).
Closing the current task then.
