### ISSUE TITLE
[Explorer] Add Cards to details page

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#77]
# Summary

Using the component created on #cardIssue, add it to the `address` page (#pageIssue)
Connect the data with the backend API (create task for that)

If total volume is not available, implement the cards that we have data for at this point

## Cards:
Number of orders placed
Number of Trades
[Blocked] Trade volume in USD(C)
[Calculate from trades] Number of unique tokens traded

# Requirements

- 

# Out of scope

- 

# Additional context

- Design doc: https://docs.google.com/document/d/1KRS_vjjJUy2s1SyLJ9eSdMhGMw324JBPXH8mAUoLCRo/edit#
- Wireframes: https://www.figma.com/file/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=0%3A1

> Original issue https://github.com/gnosis/cowswap/issues/1048 by @alfetopito

**Comment by elena-zh** [comment]
Will reopen once the task becomes relevant
