### ISSUE TITLE
Total trades amount is incorrect in Dev/Barn environments

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#771]
Compare trades for account `0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d ` in 
 - https://cowswap.exchange/#/account?chain=mainnet
 - https://cowswap.dev.gnosisdev.com/#/account?chain=mainnet

**AR**: trades amount is different (correct amount is in Prod)
![trades.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1eaf7ca2-d518-4cdf-97e7-4ecb50d9ea69)

**ER**: trades amount should match and show total of trades in Barn and Prod APIs

Note: referrals data does not match also (check `0x1f5B740436Fc5935622e92aa3b46818906F416E9 `account)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ba47624c-f9c9-4b60-812f-06ac84a26a77)

**Comment by W3stside** [comment]
is barn affected? afaik barn and dev are on different backend endpoints, `staging`/`develop`, respectively

**Comment by elena-zh** [comment]
Yes, affected
![image](https://user-images.githubusercontent.com/70885163/177129737-edb21014-ad0e-4f83-81e5-b053aec8779f.png)

As far as I remember, BARN and DEV are on Barn endpoints, Staging and Prod are on Prod endpoints..
But I might be mistaken.

**Comment by alfetopito** [comment]
Cowswap's `barn` and `dev` are running against the same Backend environment, `staging`
On the other hand, Cowswap's `staging` is pointing to Backend's `prod`

**Comment by anxolin** [comment]
> Cowswap's barn and dev are running against the same Backend environment, staging
On the other hand, Cowswap's staging is pointing to Backend's prod

But the affiliate uses Dune data, right @alfetopito the amounts should match. We don't differentiate for this between the two envs (it wouldn't make sense imo)

**Comment by anxolin** [comment]
To reproduce:

```
curl 'https://api.cow.fi/affiliate/api/v1/profile/0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d'

curl 'https://barn.api.cow.fi/affiliate/api/v1/profile/0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d'
```

![image](https://user-images.githubusercontent.com/2352112/177130780-7ccf4f85-01dd-4e62-a44e-bbcb9fa9b4cb.png)

**Comment by alfetopito** [comment]
> > Cowswap's barn and dev are running against the same Backend environment, staging
> > On the other hand, Cowswap's staging is pointing to Backend's prod
> 
> But the affiliate uses Dune data, right @alfetopito the amounts should match. We don't differentiate for this between the two envs (it wouldn't make sense imo)

While that is true, the data fetching is still isolated per environment.
Changes are first deployed to `staging` then moved onto `prod`.
It could be that relevant changes haven't reached `prod` or the infra running the service might have a problem in one of the environments

**Comment by anxolin** [comment]
Okay, then we have the same understanding. Just flagging that to my knowledge the amounts should match. Yep I know they are independent, but just flagging that then a new change in barn might be making us to under calculate the trades/volume

**Comment by josojo** [comment]
```

curl 'https://api.cow.fi/affiliate/api/v1/profile/0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d'

curl 'https://barn.api.cow.fi/affiliate/api/v1/profile/0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d'
```
Now, the data will match again. Sorry for the inconvenience.

**Comment by elena-zh** [comment]
Now the data match. Thank you!
