### ISSUE TITLE
Referral data is not updated after a successful order placement by a link follower

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#772]
1. I shared a referral link https://cowswap.dev.gnosisdev.com/#/?referral=0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d
2. I connected to this account  `0xE5a0Af01B2038cecE03baE41035567bd34B36A9c`
3. I have placed a successful trade
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c6a697fa-7f04-4fc5-960e-bd86f9813e0b)
4. Trades data was updated in the follower's Account page
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9168c60a-201b-4535-b328-d2c39ff3c639)
5. However, referral data was not updated for the referee neither in Dev, nor in Prod
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c5b8bb42-9508-4049-87dc-0531536e0903)

**Expected**: the data updated

Order details: https://barn.api.cow.fi/mainnet/api/v1/orders/0xd5c64bff3be25bb14b38213b7971cc30897b11d57039ce00884b5020eb8254bee5a0af01b2038cece03bae41035567bd34b36a9c62c2ae6d

**Comment by elena-zh** [comment]
API returns 2 referrals, however, should be 3
![image](https://user-images.githubusercontent.com/70885163/177129381-d67b0deb-4a56-459f-91f1-079ca805d466.png)

**Comment by anxolin** [comment]
As leandro is pointing out, this might be related to the same problem that is causing https://github.com/cowprotocol/cowswap/issues/771

**Comment by elena-zh** [comment]
The issue is also reproducible on Staging: 
I have placed a successful order under `0xE2CceD6Cf49aE6ccdfFD4deD87f479F54164d689 `account with referral link address `https://cowswap.staging.gnosisdev.com/#/?referral=0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d`

Referral data was recorded under the appdatahash for the order `https://api.cow.fi/mainnet/api/v1/orders/0xd84c29edba002b50aa263f7907669639f15ab26af4e12869c276dcacdc604674e2cced6cf49ae6ccdffd4ded87f479f54164d68962c56b2c`
![image](https://user-images.githubusercontent.com/70885163/177538286-aa8f5b24-f5b8-4513-9e3d-dba844b795b3.png)

Number of trades is changes for the referral link follower: 
![image](https://user-images.githubusercontent.com/70885163/177538447-f54fe8ae-e360-44e4-a1da-b742de296acd.png)


But the number of referrals is not changed for the referee account 
![image](https://user-images.githubusercontent.com/70885163/177538595-88ca0a40-8ecb-4201-b7e5-be8c72ec782c.png)
![image](https://user-images.githubusercontent.com/70885163/177538792-a04dc1d8-47f3-458b-a18e-db67736b8e7d.png)

**Comment by josojo** [comment]
Hm... somehow the auto-deploy of the correct code got stuck. I reinitiated the process and it should work tomorrow morning with for the address: 0xe2cced6cf49ae6ccdffd4ded87f479f54164d689.

In production, it is expected to not yet work. If necessary, we can deploy it tomorrow as well.

**Comment by elena-zh** [comment]
Hey @josojo , I still do not see that this trade https://barn.explorer.cow.fi/orders/0xd5c64bff3be25bb14b38213b7971cc30897b11d57039ce00884b5020eb8254bee5a0af01b2038cece03bae41035567bd34b36a9c62c2ae6d (placed by accout you mentioned above `0xe2cced6cf49ae6ccdffd4ded87f479f54164d689`)  is included into referrals data for this address `0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d`

**Comment by josojo** [comment]
Finally, you should see it:
![image](https://user-images.githubusercontent.com/7348154/177810192-34b21c2e-52ce-4e9e-bb45-a3dc75906ca3.png)
