### ISSUE TITLE
Changing amounts in From/To fields for wrap/unwrap transactions is recorded as 'Swap' event

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#773]
Related to #764, #665

1. Open Swap page
2. Select ETH/WETH token pair
3. Change an amount in the From or TO tokens

**AR**: event_category is 'swap'
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9d813116-7084-4fb0-ab33-c6e74964e95d )
**ER**:  event_category is 'wrapped native token'

**Comment by MindyCoW** [comment]
Tagging myself here to follow this issue @MindyCoW
