### ISSUE TITLE
'Cancel order' button is blinking when hover a mouse on it in the activity modal 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#793]
Reported in https://github.com/cowprotocol/cowswap/pull/609#issuecomment-1178892179

1. Place an order
2. Close confirmation modals
3. Open Activity modal and hover a mouse on the Cancel order' button under the order status

**AR**: the button is blinking, it is hard to press on it
Video: https://watch.screencastify.com/v/RxAWdu0wNGVieuS0uklx

**ER**: the button is not blinking

**Comment by elena-zh** [comment]
I'm changing the issue priority due to it is too difficult to press on the Cancel button in the activity modal now

**Comment by alongoni** [comment]
Solved in #609
