### ISSUE TITLE
ETH amount is not visible in the wrap my ETH section  in the dark mode

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#804]
Open Cowswap app in the dark mode
Select a native token in the From field, specify an amount to sell
Select To token 

**AR**: ETH amount is not visible in the wrap my ETH section  in the dark mode
![amount.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f3e853eb-9a89-47f6-91b9-89613c736790)![not vis.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/70478683-5455-4c42-9a7f-16ce14968931)

**ER**: amount should be visible

**Comment by W3stside** [comment]
Ahha ok I'll fix it 1 sec
