### ISSUE TITLE
Re-enable auto-merge

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#814]
# Summary

We use to have auto-merge setup in the previous repo.
Apply the same rules here and to all related repos:
- [x] Cowswap
- [ ] Explorer
- [ ] SDK
- [ ] Cow.fi
- [ ] app-data

**Comment by elena-zh** [comment]
@alfetopito , can this be closed?

**Comment by alfetopito** [comment]
Oh wow!
I guess, I haven't came back to it in awhile... 😆
