### ISSUE TITLE
'Unsuppoted token' error in quote request when switch network to Ethereum

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#821]
I noticed that I can see failed quote requests with an 'unsupported token' error when switch to Ethereun network. 
Toke address in this case is `0xc778417E063141139Fce010982780140Aa0cD5Ab` , and it corresponds to the WETH address in [Ropsten](https://ropsten.etherscan.io/address/0xc778417e063141139fce010982780140aa0cd5ab)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f99bb65b-3bc1-4ad3-b73e-777f1ba537b0)![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a9a7dba8-33f9-47d0-9966-f9e862e4f82e)![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0b46473b-9b0c-4a91-9d4a-367aabb30076)

**Comment by elena-zh** [comment]
I was also able to catch 'Insufficient validTo' error response while I was testing this. 
But it happened only once
![insuff valid to](https://user-images.githubusercontent.com/70885163/180428465-2859fa2b-12af-48c7-b844-e97e39a9875d.jpg)

**Comment by W3stside** [comment]
Ropsten and Rinkeby have the same WETH address: https://rinkeby.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab

aside from that I cannot reproduce this - tried switching back and forth between rinkeby and ethereum to no avail

**Comment by W3stside** [comment]
has your test been sitting open for some time by any chance?

**Comment by elena-zh** [comment]
> has your test been sitting open for some time by any chance?

Yes, I faced 'Insufficient validTo' error after the tab had been opened for a several hours, and I switched to it

**Comment by elena-zh** [comment]
I have been able to reproduce it once again: the tad was opened for 1 hour, then I switched a network in the app 
![image](https://user-images.githubusercontent.com/70885163/180438735-9dff9925-b06e-4318-89cd-4c8c9aa7b1e5.png)

**Comment by elena-zh** [comment]
> Ropsten and Rinkeby have the same WETH address: https://rinkeby.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab
> 
> aside from that I cannot reproduce this - tried switching back and forth between rinkeby and ethereum to no avail

yes, I face this issue when I switch from Rinkeby to Mainnet

**Comment by W3stside** [comment]
I cannot reproduce this, can you send a video? otherwise will close

**Comment by elena-zh** [comment]
Here is the video: https://watch.screencastify.com/v/RToIk588quHrLmf2QXFe

**Comment by elena-zh** [comment]
Do I need to record a video with 'insufficientValidTo' error for you? 
![image](https://user-images.githubusercontent.com/70885163/181006799-6e8b1376-b159-4efc-9d31-1d806a867380.png)

I am still able to see it when the tab is opened for an hour or so.

**Comment by elena-zh** [comment]
Another use-case how to reproduce the issue: 
1. select a token pair with not enough liquidity in a network (f.e. WETH-SUB in Ethereum)
2. change a network (to GC as an example)

**AR**: 'Unsuppoted token' error in quote request 
![image](https://user-images.githubusercontent.com/70885163/191047429-ef006325-9450-4dbf-8da8-10c23ae3b233.png)

**Comment by elena-zh** [comment]
No longer reproducible
