### ISSUE TITLE
Able to import 2 the same token lists

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#83]
Reproducible in Prod/Stage/Dev

I have just added another link of a token list source.

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6b864722-5e8e-481d-bfcc-3d3ccd759f35)

Please, see the video for the details:
https://images.zenhubusercontent.com/192335743/a6f715ab-8d11-4778-aa74-7d4776e64d69/untitled__jul_28__2021_3_45_pm.mp4

> Original issue https://github.com/gnosis/cowswap/issues/1083 by @elena-zh

**Comment by elena-zh** [comment]
Still reproducible 
![image](https://user-images.githubusercontent.com/70885163/169277274-7021eacc-262d-4178-99c7-cefd84135f87.png)
