### ISSUE TITLE
Lots of 404 errors for quote/account requests in Staging

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#833]
1. Open https://cowswap.staging.gnosisdev.com/#/swap?chain=goerli
2. Connect to a wallet in Gorli
3. Specify a token pair to trade (WETH/USDC at least)
4. Open console

**AR**: Lots of 404 errors for quote/account requests in Staging resulting in 'Error loading price. Try again later.' message on the swap form
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ca7105a4-82dd-4658-8a62-cd2e085e83e1)![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/16c1619e-5453-42ac-ad02-fcf9494a1dad)

**ER**: it should be possible to trade at least with WETH/USDC token pair

**Comment by alfetopito** [comment]
This is due the prod backend not yet been deployed.

Goerli has been temporarily disabled until then.
