### ISSUE TITLE
Broken modal without any interaction

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#84]
**Description**
I left the website open for a while and didn't do anything. 
When I returned I got the following screen 
<img width="1419" alt="Bildschirmfoto 2021-07-29 um 09 23 41" src="https://user-images.githubusercontent.com/34510341/127449686-023ea0d1-b45b-48c0-9b37-d41b6fc3b594.png">

**How to Reproduce**
1. Go to https://pr1075--gpswapui.review.gnosisdev.com/#/swap
2. Open Swap interface
3. Wait 
4. _Eventually_ you will see the error

Maybe related to this https://gnosisinc.slack.com/archives/CC3C5SMB5/p1627465705025200 ? 

> Original issue https://github.com/gnosis/cowswap/issues/1092 by @MareenG

**Comment by elena-zh** [comment]
I was no longer able to reproduce the issue
