### ISSUE TITLE
More analytic events

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#840]
**Description**

Improve some issues with the new analytics, and add some additional events:

**Important**
- [ ] Add slippage as a dimension?  See thread https://cowservices.slack.com/archives/C036L44JY77/p1659378950925809
- [ ] Progress bar: Track the "Close"
- [ ] Can we anonymise users but track them when they are back. (i.e. hashed address). Check with mgm/legal

**Other nice to have:**
- [ ] **Approve Workflow**: Hanging approving (Wallet Connect) https://github.com/cowprotocol/cowswap/pull/660#issuecomment-1150025142 
Next:
- [x] **Reject Claim COW for locked GNO**: Incorrect event for Rejecting TX (Wallet Connect) https://github.com/cowprotocol/cowswap/pull/658#issuecomment-1150010118
- [x] **Reject for unwrap/wrap/claim transactions using WC wallet, I still see 'Error signing' GA event instead of 'Reject' https://github.com/cowprotocol/cowswap/pull/655#issuecomment-1149771629
- [ ] https://github.com/cowprotocol/cowswap/issues/661
- [x] https://github.com/cowprotocol/cowswap/issues/638
- [ ] https://github.com/cowprotocol/cowswap/issues/639 ?
- [ ] When reject signing order with SC wallet (Safe), it shows an incorrect GA event (Error signing instead of Reject)

Follow up
- [ ] Both the approve token and the wrap have hooks which don't handle displaying error in case of an error (or rejection)
- [ ] Split Cancelation events: https://github.com/cowprotocol/cowswap/pull/631#issuecomment-1148460745
- [ ] Review TODO events and add them to this list https://docs.google.com/spreadsheets/d/1AwcuvmPaAyIRuKayOEp1cKcVGD3MLOpfS8UWA04fBtY/edit#gid=0
- [ ] Abstract the use of analytics behind a utils. Refactor all `reportAnalytics` methods
- [ ] Add alternative analytics (depend on the abstracting)
- [ ] Reitetate after trying to do the funnel, I'm sure we will have other requirements based on our first experiences

**Comment by anxolin** [comment]
@nenadV91 can we maybe update/close this issue, and create a new one for all tasks you plan to do in Analytics.

**Comment by elena-zh** [comment]
Discussed with Nenad: the issue can be closed.
