### ISSUE TITLE
Issues with search on Account page

### ISSUE THREAD

**Issue by W3stside** [cowprotocol/cowswap#844]
Based on comment

Hey @W3stside , great job!
However, still some issues from my side: 
1. I noticed that search by address may show 'no results'. But when switch between favourites and all tokens tab, token appear. See the [video](https://watch.screencastify.com/v/WIir7ilJXTyHlq1Pzr5a). Not always reproducible, but I have been able to face it twice
2. There is no search by number. See: there is a token that contains '1' in name, but search by '1' shows no results
![1](https://user-images.githubusercontent.com/70885163/180973626-d4afeaa7-2269-4d04-b472-fa740b0a7677.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/70885163/180973632-8890349a-d5d9-4697-b5c5-bfd2f5a8e915.jpg)
3. When I search by address, and there is preceding/trailing space in the field, search returns no results' 
![image](https://user-images.githubusercontent.com/70885163/180973862-89cc3da7-af86-47fc-b722-3126ea48ce67.png)
4. Placeholder is not fully visible in the mobile view. I'd make the placeholder's font smaller a bit to make the description fully visible
![image](https://user-images.githubusercontent.com/70885163/180974239-3032b424-6fd2-4788-8931-e6518c4c9380.png)

5. When I flip some pages (navigate to the 2nd page, as an example), then run a search, I'm still on the 2nd page. It may cause 'search no results' issue when there is no so many tokens to display on 2 pages (see the [video](https://watch.screencastify.com/v/G27IcC3cNRC3Z7xyJR7g)). So it would e great to reset pagination when search for a token/clear out the search field. should be fixed [c40ed30](https://github.com/cowprotocol/cowswap/pull/657/commits/c40ed3018161caed151542fdb368a28c1b1e38e7)
I have just realized that it might be connected with the 1st issue I have described above)
6. Again, It still would be nice to add a cross icon to reset a value in the search field
7. And it would be nice to clear out the search field when switch between networks. 

Thanks

_Originally posted by @elena-zh in https://github.com/cowprotocol/cowswap/issues/657#issuecomment-1195252970_

**Comment by elena-zh** [comment]
Additional issues to fix https://github.com/cowprotocol/cowswap/pull/657#pullrequestreview-1053824234

**Comment by anxolin** [comment]
1. This will depend on @michelbio design, but I think we should probably use tabs instead of a select
2. I wouldn't allow to search by number, question is if we need numbers
3. This is a quick fix @W3stside or @nenadV91 could do
4. We can make the text simpler too: i.e. `Search by symbol or address`
5. This is a quick fix @W3stside or @nenadV91 could do
6. nitpick, i wouldn't put much effort in this one

**Comment by W3stside** [comment]
5 is done [here](https://github.com/cowprotocol/cowswap/pull/657/commits/c40ed3018161caed151542fdb368a28c1b1e38e7)

**Comment by elena-zh** [comment]
@W3stside , 5 is not done in #657 
See the video: https://watch.screencastify.com/v/nT2ce6yTMdqLt2HefLyz
And the issue is reproducible in DEV: https://watch.screencastify.com/v/V1zyWgkzfxWfNiC3XF8Y
