### ISSUE TITLE
NPS modal does not appear when an order is Open for more than 5 minutes

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#864]
Related to #860

1. Using 2 different accounts, place two identical orders for the same pair, in a way that there is a price impact (I placed in 2 different browsers)
2. Wait till One of them is executed
3. Open the 2nd order and wait for 5 min 

**AR**: the modal does not appear. See the video: https://watch.screencastify.com/v/0fmmeJW7Ad37LR3cKcOq

**ER**: After 5 min pending, NPS modal should be displayed

**Comment by anxolin** [comment]
@alfetopito I would think this one is because of the local storage? We don't show the NPS message if it was displayed recently

@elena-zh we can easily create a testing URL that reduces the time to 10s and show you how to delete the local storage
