### ISSUE TITLE
Input not detected

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#87]
**Description**
The value in the from field was not detected

**How to Reproduce**
1. Go to https://pr1075--gpswapui.review.gnosisdev.com/#/swap
2. Chose ETH as a from token and any other to token 
3. Change the from token  (ETH) to USDT, USDC

**Expected behavior**
Value should be detected

**Screenshots**

https://user-images.githubusercontent.com/34510341/127456279-7dc3f09b-4ec0-4acc-97a1-1707bc48804b.mov

It is detected once I enter a new amount

https://user-images.githubusercontent.com/34510341/127456323-105739dd-20c5-4df0-8478-293c446e6b36.mov

> Original issue https://github.com/gnosis/cowswap/issues/1097 by @MareenG

**Comment by elena-zh** [comment]
No loner reproducible
