### ISSUE TITLE
Pending order tooltip appears again when close it and reload the page in Expert mode

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#872]
1. Place an order in Expert mode
2. Close Order Submitted modal
3. Close Pending order tooltip
4. Refresh the page

**AR**: Pending order tooltip appears again.
It appears again when open activity modal, then refresh the page
https://watch.screencastify.com/v/3xwHfr430W7Sicie8RwR

**ER**: the logic is:

- when I close the tooltip, it does not appear again when order is pending (even if I refresh the page). it appears again when I place another order
- when I open activity modal, the tooltip is closes and does not appear again while the order is pending  (even if I refresh the page). it appears again when I place another order
- and when I press on the 'do not show it again', it never appears again

**Comment by alfetopito** [comment]
Tried locally and using the [PR](https://github.com/cowprotocol/cowswap/pull/871) link https://pr871--cowswap.review.gnosisdev.com/#/swap?chain=rinkeby

Cannot reproduce
https://user-images.githubusercontent.com/43217/182615039-dfb10b1f-f57f-4057-b9fb-95aceedc48e2.mov

**Comment by alfetopito** [comment]
Now I noticed that in the video you shared you are using expert mode, while I am not.
Will try to reproduce with that

**Comment by alfetopito** [comment]
Yep, can reproduce with Expert mode turned on everywhere, inclusively on Prod


https://user-images.githubusercontent.com/43217/182616008-07688696-27e2-4bac-af61-5824eba4f428.mov

**Comment by elena-zh** [comment]
Yes.. 😒
I have also reproduced it in Prod in the expert mode. 
So I updated the issue description and unlinked issues with the recent PRs. 
Thank you, @alfetopito !
