### ISSUE TITLE
'Swap' button is enabled when Safe becomes read-only

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#873]
Related to safe-global/safe-react#857 and safe-global/safe-react#870
1. Open the Safe app, connect to a wallet with an owner account in the eponymous network
2. Open the Cowswap app inside the Safe app
3. Specify a token pair
4. Change Safe state to read-only:
 - Change a network in the connected wallet
 - Change an account (not an owner)
 - Disconnect a wallet

**AR**: Swap button is still enabled,  user can press on it and create a pending order.
Video: https://watch.screencastify.com/v/zsMnqA1Q1Z25INgiAAXu

**ER**: Swap button becomes disabled when the safe is in 'read-only'

**Note**: the same is with inverse flow: button stays in read-only when the safe is not in this mode.

**Comment by shoom3301** [comment]
It's blocked by https://github.com/safe-global/safe-react/issues/4039

**Comment by shoom3301** [comment]
Another scenario:
1. Connect an account that in Readonly mode
2. Change account to another one that is an owner
AR: UI still display Readonly
ER: UI updated corresponding to a new account

Refreshing the page solves the problem.
