### ISSUE TITLE
Connection modal: Terms and conditions link navigates to the Swap page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#875]
Open connection modal and press on the Terms and Conditions link

**AR**: user is navigated to the Swap page

**ER**: user is navigated to the Terms and Conditions page

**Comment by anxolin** [comment]
Moving it to the sprint since its a quick fix

**Comment by anxolin** [comment]
@nenadV91 this is a broken link, should be a quick fix. Can you look into it?
