### ISSUE TITLE
Background in common base slider 

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#88]
**Description**
For reduced desktop size the slider in the common base section has some kind of background. This is not present on mobile device

https://user-images.githubusercontent.com/34510341/127464601-1c0360e6-5f6f-4132-b2b0-6b477c885a61.mov

https://user-images.githubusercontent.com/34510341/127464620-98d3c69d-c0a9-4238-883a-4d35908fc666.mov

> Original issue https://github.com/gnosis/cowswap/issues/1100 by @MareenG

**Comment by elena-zh** [comment]
Seems to be fixed
