### ISSUE TITLE
Colors while Token lists are loading

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#89]
When opening the manage token list section the colors of the token lists are not displayed correctly.

https://user-images.githubusercontent.com/34510341/127473562-a190cbc0-9ab1-405a-b0be-6693db5eb9a6.mov

Really low prio :) 

> Original issue https://github.com/gnosis/cowswap/issues/1107 by @MareenG

**Comment by elena-zh** [comment]
No longer reproducible
