### ISSUE TITLE
Safe +Gorli: the order is in Signing status when it is pre-signed and executed 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#895]
1. Open Cowswap app in Gorli
2. Connect to the Safe app using WC OR open the app in the Safe
3. Place an order
4. Sigh and execute transaction in the Safe
5. Open Cowswap app and track the order status

**AR**: the order is 'Signing' and they are not executed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/35c6f013-1c61-47de-a83b-29e7a2b927de)

**ER**: the order is 'Open'

**Comment by elena-zh** [comment]
Just to mention that today I have been able to place orders in Gorli safe, and it worked fine: 
![image](https://user-images.githubusercontent.com/70885163/183653063-a61c7fb9-f323-483a-980d-16c10dc9533a.png)

**Comment by anxolin** [comment]
Does it happen always, or was a one-off?

**Comment by elena-zh** [comment]
One of the orders (`0xa70ccef062707012c233e2c698cb29259ec4015c706f2521c539662517181935e9b79591e270b3bcd0cc7e84f7b7de74ba3d0e2f62f27e2d`) even has 'Filled on' label (hence, executed). But is displayed as 'Signing'
![image](https://user-images.githubusercontent.com/70885163/183677151-46770fe4-863e-485e-8474-d4716e097251.png)

**Comment by alfetopito** [comment]
Could that have been related to the backend issues?
Is it still happening for new orders?

**Comment by elena-zh** [comment]
I have retested it, and the issue is no longer reproducible. So I'm closing it for now.
