### ISSUE TITLE
Create a sticky header for desktop

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#92]
**Description**
- Make the desktop header sticky on scroll. No changes on mobile.

**Proposal**
From: https://github.com/gnosis/cowswap/issues/487#issuecomment-826695317

I think what would be a better approach, is to have our navigation 'sticky' when you're scrolling. The about page is part of our main menu (SWAP | ABOUT) and should thus be approached like that (as opposed to a modal).

As a rough example (would not use this blur, but just for DEMO purposes:)
https://user-images.githubusercontent.com/31534717/116064515-61b4cf00-a686-11eb-93fc-a14a383456e9.mov

Main menu always visible (also on mobile) using a sticky on scroll header.
Increased the page width to max. 700px to give more the impression of a content page (in contrast to our Swap container).

> Original issue https://github.com/gnosis/cowswap/issues/1119 by @fairlighteth

**Comment by elena-zh** [comment]
Hey @fairlighteth , is this still relevant?
