### ISSUE TITLE
Show gas prices in the UI

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#94]
**Description**

Show gas prices in the UI, to better understand why the fee costs whatever it costs

**Proposal**

:point_up: 

**Alternatives**

Don't :grin: 

**Additional context**
 
Suggested during Kaffeasldas community call

> Original issue https://github.com/gnosis/cowswap/issues/1143 by @alfetopito

**Comment by alfetopito** [comment]
Addressed with the uni-merge https://github.com/cowprotocol/cowswap/pull/374
