### ISSUE TITLE
[Brave] - MM connection issues

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#95]
**Description**
I tried to connect my MM in Brave but the MM modal did not pop up automatically. 
Only when clicking on the MM icon myself I could enter my log in details. 
I checked if this was the case for other dapps e.g for Uni. But there it worked as usual.

**How to Reproduce**
Prerequisite: MM logged out
1. Open Cowswap
2. Connect Wallet
3. Choose MM 
4. Wait 
5. No Popup modal to sign into MM appeared
6. Go to UNI and repeat the same steps
7. MM modal pops up asking you to log in 

**Expected behavior**
The MM sign in modal should pop up in Cowswap. 
The user should not have to click on the MM icon. 

**Additional context**
There was no pending action or similar in MM.
I closed and reopened the browser afterwards it worked fine. 
Putting it as low prio as it is currently not reproducible. 

> Original issue https://github.com/gnosis/cowswap/issues/1147 by @MareenG

**Comment by elena-zh** [comment]
I'm not able to reproduce this issue
