### ISSUE TITLE
CowSay: CowFortune

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#952]
Create a dynamic widget with a CowSay (see https://en.wikipedia.org/wiki/Cowsay) to advertise some features of CoW Protocol, or just be funny! 

The idea is to educate and make a more enjoyable user experience.

This issue will include:
- [ ] Figma prototype
- [ ] How to read and mantain the fortune pills
- [ ] Implementation (maybe this part we will delegate, once defined, TBD)

**Comment by elena-zh** [comment]
Implemented
