### ISSUE TITLE
Expert mode: error message area overlaps Swap button + message is displayed when change amounts

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#96]
Reproducible in Prod/Stage

1. Switch the expert mode on
2. Specify tokens in From/To fields, an amount to swap
3. Press on the Swap button
4. Cancel the transaction in the connected wallet

**AR:** error message appears. its area overlaps Swap button area. 
Moreover, the message is displayed when change amounts/play with numbers/change type of transaction from Sell to Buy, etc.
![overlap.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c1680a7b-f486-45d6-bbb7-32502b1736f2)

**ER**: error message area does not overlap Swap button area
Error message is not displayed when change amounts/play with numbers/change type of transaction from Sell to Buy, etc

> Original issue https://github.com/gnosis/cowswap/issues/1150 by @elena-zh

**Comment by elena-zh** [comment]
Still reproducible and might be annoying to see a rejection message until a iser reloads the page
![remove](https://user-images.githubusercontent.com/70885163/172846281-bcab1bf8-ca62-4f13-927b-14185e43166d.jpg)

**Comment by elena-zh** [comment]
There is no error message now
