### ISSUE TITLE
[1.21]iPhone: app is auto-zoomed in when type into the search field on Tokens page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#980]
Related to #948 and #932

1. Open Tokens page (#/account/tokens)  in iPhone real device
2. Type into the search field

**AR**: the app is auto-zoomed in. See details in https://cowservices.slack.com/archives/C0361CDG8GP/p1661765815475519

**ER**: the app is not auto-zoomed it.

**Comment by fairlighteth** [comment]
Did a quick review and thus far found that it might have to do with the meta viewport attribute. Looking at https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
it might be related to the fact we have:
`<meta name="viewport" content="width=device-width,initial-scale=1">`

and in this StackOverflow they recommend using:
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`

So by adding the `maximum-scale-1`
