### ISSUE TITLE
Network selector is displayed beyond pop-ups

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#992]
Discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1661771523512779

An attempt to fix: https://github.com/cowprotocol/cowswap/pull/932/commits/754ac0517ad16366f42b0390c4729f89644085f0

However, it caused #985 issue, so the change was reverted in #986

Description: 
Network selector is displayed beyond pop-ups
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7882139d-50e5-4010-8b1b-345ae8da5a26)

It would be great to show it above pop-ups

**Comment by alfetopito** [comment]
I though this was fixed! :O

**Comment by elena-zh** [comment]
Nope! 
@nenadV91 rolled back the fix as it caused side issues with z-index (links in the description), so I opened the task to do the 2nd try to fix it.

**Comment by elena-zh** [comment]
Fixed
